 ============================================================
-- FIX: Deploy door_punches table + process_door_punch RPC
-- Run this in Supabase SQL Editor to enable the ponche system
-- ====--========================================================

-- 1. Create door_punches table
CREATE TABLE IF NOT EXISTS public.door_punches (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  staff_id     uuid   REFERENCES public.profiles(id) ON DELETE CASCADE,
  punch_type   text   NOT NULL CHECK (punch_type IN ('check_in','check_out')),
  punched_at   timestamp with time zone DEFAULT now() NOT NULL,
  date         date   DEFAULT current_date NOT NULL,
  parent_notified boolean DEFAULT false,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT door_punches_student_type_date UNIQUE (student_id, punch_type, date),
  CONSTRAINT door_punches_staff_type_date   UNIQUE (staff_id,   punch_type, date),
  CONSTRAINT door_punches_one_subject CHECK (
    (student_id IS NOT NULL AND staff_id IS NULL) OR
    (student_id IS NULL     AND staff_id IS NOT NULL)
  )
);
ALTER TABLE public.door_punches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "punches_staff_all"   ON public.door_punches;
DROP POLICY IF EXISTS "punches_parent_read" ON public.door_punches;
CREATE POLICY "punches_staff_all" ON public.door_punches FOR ALL
  USING (get_my_role() IN ('directora','asistente','maestra','admin'));
CREATE POLICY "punches_parent_read" ON public.door_punches FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.students s
    WHERE s.id = door_punches.student_id AND s.parent_id = auth.uid()
  ));

-- Indexes
CREATE INDEX IF NOT EXISTS idx_door_punches_date    ON public.door_punches(date);
CREATE INDEX IF NOT EXISTS idx_door_punches_student ON public.door_punches(student_id, date);
CREATE INDEX IF NOT EXISTS idx_door_punches_staff   ON public.door_punches(staff_id, date);

-- 2. Create process_door_punch function
CREATE OR REPLACE FUNCTION public.process_door_punch(p_code text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_student  record;
  v_staff    record;
  v_settings record;
  v_today    date := current_date;
  v_now      timestamp with time zone := now();
  v_type     text;
  v_name     text;
  v_role     text;
  v_parent   uuid;
  v_existing record;
  v_attendance record;
  v_status   text := 'present';
BEGIN
  -- 1. Search student by matricula
  SELECT * INTO v_student FROM public.students
  WHERE matricula = p_code AND is_active = true LIMIT 1;

  IF FOUND THEN
    v_name   := v_student.name;
    v_role   := 'Estudiante';
    v_parent := v_student.parent_id;
    SELECT * INTO v_settings FROM public.school_settings WHERE id = 1;

    SELECT * INTO v_existing FROM public.door_punches
    WHERE student_id = v_student.id AND date = v_today AND punch_type = 'check_in';

    IF NOT FOUND THEN
      v_type := 'check_in';
      IF v_settings.check_in_end IS NOT NULL AND v_now::time > v_settings.check_in_end THEN
        v_status := 'late';
      END IF;
      -- Write to attendance
      SELECT * INTO v_attendance FROM public.attendance
      WHERE student_id = v_student.id AND date = v_today;
      IF v_attendance.id IS NULL THEN
        INSERT INTO public.attendance (student_id, classroom_id, date, status, check_in)
        VALUES (v_student.id, v_student.classroom_id, v_today, v_status, v_now);
      END IF;
      INSERT INTO public.door_punches (student_id, punch_type, punched_at, date)
      VALUES (v_student.id, 'check_in', v_now, v_today) ON CONFLICT DO NOTHING;
    ELSE
      SELECT * INTO v_existing FROM public.door_punches
      WHERE student_id = v_student.id AND date = v_today AND punch_type = 'check_out';
      IF NOT FOUND THEN
        v_type := 'check_out';
        SELECT * INTO v_attendance FROM public.attendance
        WHERE student_id = v_student.id AND date = v_today;
        IF v_attendance.id IS NOT NULL THEN
          UPDATE public.attendance SET check_out = v_now, status = 'retirado' WHERE id = v_attendance.id;
        END IF;
        INSERT INTO public.door_punches (student_id, punch_type, punched_at, date)
        VALUES (v_student.id, 'check_out', v_now, v_today) ON CONFLICT DO NOTHING;
      ELSE
        RETURN jsonb_build_object('success', false, 'message', v_name || ' ya registró entrada y salida hoy');
      END IF;
    END IF;

    RETURN jsonb_build_object(
      'success', true, 'type', v_type, 'name', v_name, 'role', v_role,
      'student_id', v_student.id,
      'parent_id', v_parent,
      'time', to_char(v_now AT TIME ZONE 'America/Santo_Domingo', 'HH12:MI AM')
    );
  END IF;

  -- 2. Search staff by access_code, notes, or matricula
  SELECT * INTO v_staff FROM public.profiles
  WHERE (notes = p_code OR matricula = p_code OR access_code = p_code)
    AND role IN ('maestra','asistente','directora','admin') LIMIT 1;

  IF NOT FOUND THEN
    BEGIN
      SELECT * INTO v_staff FROM public.profiles
      WHERE id = p_code::uuid AND role IN ('maestra','asistente','directora','admin') LIMIT 1;
    EXCEPTION WHEN OTHERS THEN NULL;
    END;
  END IF;

  IF FOUND THEN
    v_name := v_staff.name;
    v_role := initcap(v_staff.role);

    -- Staff only writes to door_punches — NOT attendance (student_id is bigint, staff id is uuid)
    SELECT * INTO v_existing FROM public.door_punches
    WHERE staff_id = v_staff.id AND date = v_today AND punch_type = 'check_in';

    IF NOT FOUND THEN
      v_type := 'check_in';
      INSERT INTO public.door_punches (staff_id, punch_type, punched_at, date)
      VALUES (v_staff.id, 'check_in', v_now, v_today) ON CONFLICT DO NOTHING;
    ELSE
      SELECT * INTO v_existing FROM public.door_punches
      WHERE staff_id = v_staff.id AND date = v_today AND punch_type = 'check_out';
      IF NOT FOUND THEN
        v_type := 'check_out';
        INSERT INTO public.door_punches (staff_id, punch_type, punched_at, date)
        VALUES (v_staff.id, 'check_out', v_now, v_today) ON CONFLICT DO NOTHING;
      ELSE
        RETURN jsonb_build_object('success', false, 'message', v_name || ' ya registró entrada y salida hoy');
      END IF;
    END IF;

    RETURN jsonb_build_object(
      'success', true, 'type', v_type, 'name', v_name, 'role', v_role,
      'parent_id', null,
      'time', to_char(v_now AT TIME ZONE 'America/Santo_Domingo', 'HH12:MI AM')
    );
  END IF;

  RETURN jsonb_build_object('success', false, 'message', 'QR no registrado en el sistema');
END;
$$;

GRANT EXECUTE ON FUNCTION public.process_door_punch(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.process_door_punch(text) TO anon;
