-- ============================================================
-- Migración: Sistema de Pre-inscripciones
-- Crea la tabla student_preregistrations
-- ============================================================

-- Tabla de Pre-inscripciones
CREATE TABLE IF NOT EXISTS public.student_preregistrations (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name          text NOT NULL,
  birth_date            date,
  gender                text,
  blood_type            text,
  allergies             text,
  section               text,
  schedule              text,
  
  -- Tutor 1 (Principal)
  p1_name               text NOT NULL,
  p1_relationship       text,
  p1_phone              text,
  p1_email              text,
  p1_address            text,
  
  -- Tutor 2 (Opcional)
  p2_name               text,
  p2_relationship       text,
  p2_phone              text,
  p2_email              text,
  
  -- Contacto de Emergencia
  emergency_name        text,
  emergency_phone       text,
  emergency_relationship text,
  
  -- Información adicional
  reference             text,
  comments              text,
  
  -- Estado y fechas
  status                text DEFAULT 'pending' CHECK (status IN ('pending', 'admitted', 'rejected', 'converted')),
  reviewed_at           timestamp with time zone,
  reviewed_by           uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  
  -- Metadata
  created_at            timestamp with time zone DEFAULT now() NOT NULL,
  updated_at            timestamp with time zone DEFAULT now() NOT NULL
);

-- Índices para rendimiento
CREATE INDEX IF NOT EXISTS idx_preregistrations_status ON public.student_preregistrations(status);
CREATE INDEX IF NOT EXISTS idx_preregistrations_created ON public.student_preregistrations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_preregistrations_student_name ON public.student_preregistrations(lower(student_name));

-- Trigger para actualizar updated_at automáticamente
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS update_student_preregistrations_updated_at ON public.student_preregistrations;
CREATE TRIGGER update_student_preregistrations_updated_at
  BEFORE UPDATE ON public.student_preregistrations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Habilitar RLS
ALTER TABLE public.student_preregistrations ENABLE ROW LEVEL SECURITY;

-- Políticas RLS: Permitir inserción anónima (para el formulario público)
DROP POLICY IF EXISTS "Permitir inserción anónima de preinscripciones" ON public.student_preregistrations;
CREATE POLICY "Permitir inserción anónima de preinscripciones"
  ON public.student_preregistrations
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- Políticas RLS: Permitir lectura y escritura a usuarios autenticados (directora, asistente)
DROP POLICY IF EXISTS "Permitir lectura completa a autenticados" ON public.student_preregistrations;
CREATE POLICY "Permitir lectura completa a autenticados"
  ON public.student_preregistrations
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Permitir actualización a autenticados" ON public.student_preregistrations;
CREATE POLICY "Permitir actualización a autenticados"
  ON public.student_preregistrations
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- Función RPC: Convertir preinscripción a estudiante
-- ============================================================
CREATE OR REPLACE FUNCTION public.convert_preregistration(
  p_preinsc_id bigint,
  p_school_year_id bigint,
  p_classroom_id bigint DEFAULT NULL,
  p_payment_plan_id bigint DEFAULT NULL,
  p_matricula text DEFAULT NULL
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_preinsc record;
  v_student_id bigint;
  v_enrollment_id bigint;
  v_profile_id uuid;
BEGIN
  -- Obtener datos de la preinscripción
  SELECT * INTO v_preinsc FROM student_preregistrations WHERE id = p_preinsc_id;
  
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Preinscripción no encontrada';
  END IF;
  
  IF v_preinsc.status = 'converted' THEN
    RAISE EXCEPTION 'Esta preinscripción ya ha sido convertida';
  END IF;

  -- 1. Crear estudiante
  INSERT INTO students (
    name,
    birth_date,
    classroom_id,
    allergies,
    matricula,
    p1_name,
    p1_phone,
    p1_email,
    p2_name,
    p2_phone,
    created_at
  ) VALUES (
    v_preinsc.student_name,
    v_preinsc.birth_date,
    p_classroom_id,
    v_preinsc.allergies,
    p_matricula,
    v_preinsc.p1_name,
    v_preinsc.p1_phone,
    v_preinsc.p1_email,
    v_preinsc.p2_name,
    v_preinsc.p2_phone,
    now()
  ) RETURNING id INTO v_student_id;

  -- 2. Crear inscripción
  INSERT INTO student_enrollments (
    student_id,
    school_year_id,
    classroom_id,
    payment_plan_id,
    status,
    preinscription_date,
    created_at
  ) VALUES (
    v_student_id,
    p_school_year_id,
    p_classroom_id,
    p_payment_plan_id,
    'admitted',
    v_preinsc.created_at,
    now()
  ) RETURNING id INTO v_enrollment_id;

  -- 3. Actualizar estado de preinscripción
  UPDATE student_preregistrations
  SET status = 'converted',
      reviewed_at = now()
  WHERE id = p_preinsc_id;

  -- 4. Si hay plan de pago, crear cargos automáticos
  IF p_payment_plan_id IS NOT NULL THEN
    -- Esta lógica se puede expandir para crear cargos automáticos
    -- Por ahora solo registramos la inscripción
    NULL;
  END IF;

  RETURN jsonb_build_object(
    'success', true,
    'student_id', v_student_id,
    'enrollment_id', v_enrollment_id
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.convert_preregistration TO authenticated;

-- ============================================================
-- Completado
-- ============================================================
