
-- ============================================================
-- REPORTS SYSTEM - Sistema de Reportes y Incidencias Multi-Nivel
-- ============================================================

-- 1. LIMPIEZA PREVIA
DROP TABLE IF EXISTS public.report_history CASCADE;
DROP TABLE IF EXISTS public.reports CASCADE;
DROP VIEW IF EXISTS public.v_reports_dashboard;
DROP FUNCTION IF EXISTS public.create_report CASCADE;
DROP FUNCTION IF EXISTS public.update_report_status CASCADE;
DROP FUNCTION IF EXISTS public.get_reports CASCADE;
DROP FUNCTION IF EXISTS public.get_monthly_reports_by_classroom CASCADE;
DROP FUNCTION IF EXISTS public.notify_on_report_change CASCADE;

-- 2. TABLA PRINCIPAL DE REPORTES
CREATE TABLE public.reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  reporter_type text CHECK (reporter_type IN ('padre','maestra','asistente','directora')) NOT NULL,
  report_type text CHECK (report_type IN ('queja_maestra','queja_directora','incidente_estudiante','otro')) NOT NULL,
  target_teacher_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  target_student_id bigint REFERENCES public.students(id) ON DELETE SET NULL,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE SET NULL,
  category text NOT NULL,
  description text NOT NULL,
  severity text CHECK (severity IN ('leve','media','alta')) DEFAULT 'media',
  status text CHECK (status IN ('pending','in_review','resolved','closed')) DEFAULT 'pending',
  is_anonymous boolean DEFAULT false,
  evidence_url text,
  response text,
  response_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  response_at timestamp with time zone,
  resolved_at timestamp with time zone,
  closed_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 3. TABLA DE HISTORIAL DE CAMBIOS
CREATE TABLE public.report_history (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id bigint REFERENCES public.reports(id) ON DELETE CASCADE NOT NULL,
  changed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  old_status text,
  new_status text,
  comment text,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

-- 4. ÍNDICES DE RENDIMIENTO
CREATE INDEX idx_reports_reporter ON public.reports(reporter_id);
CREATE INDEX idx_reports_status ON public.reports(status);
CREATE INDEX idx_reports_type ON public.reports(report_type);
CREATE INDEX idx_reports_created_at ON public.reports(created_at DESC);
CREATE INDEX idx_report_history_report_id ON public.report_history(report_id);

-- 5. ENABLE RLS
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_history ENABLE ROW LEVEL SECURITY;

-- 6. POLÍTICAS RLS

-- Padres pueden ver sus propios reportes
DROP POLICY IF EXISTS "reports_padre_select" ON public.reports;
CREATE POLICY "reports_padre_select" ON public.reports FOR SELECT
  USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'padre'
    AND reporter_id = auth.uid()
  );

-- Padres pueden crear reportes
DROP POLICY IF EXISTS "reports_padre_insert" ON public.reports;
CREATE POLICY "reports_padre_insert" ON public.reports FOR INSERT
  WITH CHECK (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'padre'
    AND reporter_id = auth.uid()
  );

-- Maestras pueden ver reportes sobre ellas o incidentes que crearon
DROP POLICY IF EXISTS "reports_maestra_select" ON public.reports;
CREATE POLICY "reports_maestra_select" ON public.reports FOR SELECT
  USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'maestra'
    AND (
      reporter_id = auth.uid()
      OR target_teacher_id = auth.uid()
      OR EXISTS (
        SELECT 1 FROM public.students s
        JOIN public.classrooms c ON c.id = s.classroom_id
        WHERE s.id = target_student_id AND c.teacher_id = auth.uid()
      )
    )
  );

-- Maestras pueden crear incidentes de estudiantes
DROP POLICY IF EXISTS "reports_maestra_insert" ON public.reports;
CREATE POLICY "reports_maestra_insert" ON public.reports FOR INSERT
  WITH CHECK (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) = 'maestra'
    AND reporter_id = auth.uid()
  );

-- Directora y Asistente pueden ver todos los reportes
DROP POLICY IF EXISTS "reports_staff_select" ON public.reports;
CREATE POLICY "reports_staff_select" ON public.reports FOR SELECT
  USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('directora','asistente','admin')
  );

-- Directora y Asistente pueden actualizar reportes
DROP POLICY IF EXISTS "reports_staff_update" ON public.reports;
CREATE POLICY "reports_staff_update" ON public.reports FOR UPDATE
  USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('directora','asistente','admin')
  );

-- Historial: solo staff puede ver
DROP POLICY IF EXISTS "report_history_staff" ON public.report_history;
CREATE POLICY "report_history_staff" ON public.report_history FOR SELECT
  USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('directora','asistente','admin')
  );

-- Historial: solo staff puede insertar
DROP POLICY IF EXISTS "report_history_staff_insert" ON public.report_history;
CREATE POLICY "report_history_staff_insert" ON public.report_history FOR INSERT
  WITH CHECK (
    (SELECT role FROM public.profiles WHERE id = auth.uid()) IN ('directora','asistente','admin')
  );

-- 7. FUNCIONES RPC

-- Crear reporte
CREATE OR REPLACE FUNCTION public.create_report(
  p_report_type text,
  p_category text,
  p_description text,
  p_target_teacher_id uuid DEFAULT NULL,
  p_target_student_id bigint DEFAULT NULL,
  p_classroom_id bigint DEFAULT NULL,
  p_severity text DEFAULT 'media',
  p_is_anonymous boolean DEFAULT false,
  p_evidence_url text DEFAULT NULL
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_reporter_id uuid := auth.uid();
  v_reporter_type text;
  v_report_id bigint;
BEGIN
  SELECT role INTO v_reporter_type FROM public.profiles WHERE id = v_reporter_id;
  
  INSERT INTO public.reports (
    reporter_id, reporter_type, report_type, target_teacher_id, target_student_id,
    classroom_id, category, description, severity, is_anonymous, evidence_url
  ) VALUES (
    v_reporter_id, v_reporter_type, p_report_type, p_target_teacher_id, p_target_student_id,
    p_classroom_id, p_category, p_description, p_severity, p_is_anonymous, p_evidence_url
  ) RETURNING id INTO v_report_id;
  
  -- Insertar en historial
  INSERT INTO public.report_history (report_id, changed_by, old_status, new_status, comment)
  VALUES (v_report_id, v_reporter_id, NULL, 'pending', 'Reporte creado');
  
  RETURN jsonb_build_object('success', true, 'report_id', v_report_id);
END;
$$;
GRANT EXECUTE ON FUNCTION public.create_report TO authenticated;

-- Actualizar estado del reporte
CREATE OR REPLACE FUNCTION public.update_report_status(
  p_report_id bigint,
  p_new_status text,
  p_response text DEFAULT NULL,
  p_comment text DEFAULT NULL
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_role text;
  v_old_status text;
  v_staff_id uuid := auth.uid();
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = v_staff_id;
  IF v_role NOT IN ('directora','asistente','admin') THEN
    RETURN jsonb_build_object('success', false, 'error', 'No autorizado');
  END IF;
  
  SELECT status INTO v_old_status FROM public.reports WHERE id = p_report_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('success', false, 'error', 'Reporte no encontrado');
  END IF;
  
  UPDATE public.reports 
  SET 
    status = p_new_status,
    response = COALESCE(p_response, response),
    response_by = CASE WHEN p_response IS NOT NULL THEN v_staff_id ELSE response_by END,
    response_at = CASE WHEN p_response IS NOT NULL THEN now() ELSE response_at END,
    resolved_at = CASE WHEN p_new_status = 'resolved' THEN now() ELSE resolved_at END,
    closed_at = CASE WHEN p_new_status = 'closed' THEN now() ELSE closed_at END,
    updated_at = now()
  WHERE id = p_report_id;
  
  -- Insertar en historial
  INSERT INTO public.report_history (report_id, changed_by, old_status, new_status, comment)
  VALUES (p_report_id, v_staff_id, v_old_status, p_new_status, p_comment);
  
  RETURN jsonb_build_object('success', true);
END;
$$;
GRANT EXECUTE ON FUNCTION public.update_report_status TO authenticated;

-- Obtener reportes (para dashboard)
CREATE OR REPLACE FUNCTION public.get_reports(p_status text DEFAULT NULL)
RETURNS TABLE (
  id bigint,
  reporter_name text,
  reporter_type text,
  report_type text,
  target_teacher_name text,
  target_student_name text,
  classroom_name text,
  category text,
  description text,
  severity text,
  status text,
  is_anonymous boolean,
  evidence_url text,
  response text,
  response_by_name text,
  response_at timestamp with time zone,
  created_at timestamp with time zone
) LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT 
    r.id,
    CASE WHEN r.is_anonymous THEN 'Anónimo' ELSE p_reporter.name END AS reporter_name,
    r.reporter_type,
    r.report_type,
    p_teacher.name AS target_teacher_name,
    s.name AS target_student_name,
    c.name AS classroom_name,
    r.category,
    r.description,
    r.severity,
    r.status,
    r.is_anonymous,
    r.evidence_url,
    r.response,
    p_resp.name AS response_by_name,
    r.response_at,
    r.created_at
  FROM public.reports r
  LEFT JOIN public.profiles p_reporter ON p_reporter.id = r.reporter_id
  LEFT JOIN public.profiles p_teacher ON p_teacher.id = r.target_teacher_id
  LEFT JOIN public.students s ON s.id = r.target_student_id
  LEFT JOIN public.classrooms c ON c.id = r.classroom_id
  LEFT JOIN public.profiles p_resp ON p_resp.id = r.response_by
  WHERE (p_status IS NULL OR r.status = p_status)
  ORDER BY r.created_at DESC;
$$;
GRANT EXECUTE ON FUNCTION public.get_reports TO authenticated;

-- Reporte mensual por aula
CREATE OR REPLACE FUNCTION public.get_monthly_reports_by_classroom(p_month date)
RETURNS TABLE (
  classroom_name text,
  total_reports bigint,
  pending bigint,
  resolved bigint,
  avg_resolution_days numeric
) LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT
    c.name AS classroom_name,
    COUNT(*) AS total_reports,
    COUNT(*) FILTER (WHERE r.status = 'pending') AS pending,
    COUNT(*) FILTER (WHERE r.status = 'resolved' OR r.status = 'closed') AS resolved,
    AVG(EXTRACT(EPOCH FROM (COALESCE(r.resolved_at, r.closed_at, now()) - r.created_at))/86400)::numeric(10,2) AS avg_resolution_days
  FROM public.reports r
  LEFT JOIN public.classrooms c ON c.id = r.classroom_id
  WHERE DATE_TRUNC('month', r.created_at) = DATE_TRUNC('month', p_month)
  GROUP BY c.name
  ORDER BY COUNT(*) DESC;
$$;
GRANT EXECUTE ON FUNCTION public.get_monthly_reports_by_classroom TO authenticated;

-- Vista de dashboard
CREATE OR REPLACE VIEW public.v_reports_dashboard AS
SELECT
  COUNT(*) AS total_reports,
  COUNT(*) FILTER (WHERE status = 'pending') AS pending,
  COUNT(*) FILTER (WHERE status = 'in_review') AS in_review,
  COUNT(*) FILTER (WHERE status = 'resolved') AS resolved,
  COUNT(*) FILTER (WHERE status = 'closed') AS closed,
  COUNT(*) FILTER (WHERE severity = 'alta') AS high_severity,
  COUNT(*) FILTER (WHERE report_type = 'queja_maestra') AS teacher_complaints,
  COUNT(*) FILTER (WHERE report_type = 'incidente_estudiante') AS student_incidents
FROM public.reports;

-- Trigger para notificaciones (placeholder, se puede expandir con OneSignal)
CREATE OR REPLACE FUNCTION public.notify_on_report_change()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  -- Aquí se integraría con OneSignal para enviar notificaciones push
  -- Por ahora, solo registramos en system_events
  INSERT INTO public.system_events (type, payload)
  VALUES ('report_change', jsonb_build_object(
    'report_id', NEW.id,
    'old_status', OLD.status,
    'new_status', NEW.status,
    'reporter_id', NEW.reporter_id
  ));
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trigger_report_change ON public.reports;
CREATE TRIGGER trigger_report_change
AFTER UPDATE ON public.reports
FOR EACH ROW EXECUTE FUNCTION public.notify_on_report_change();

-- 8. GRANT PERMISOS
GRANT ALL ON public.reports TO authenticated;
GRANT ALL ON public.report_history TO authenticated;
GRANT SELECT ON public.v_reports_dashboard TO authenticated;
