﻿-- ============================================================
--MONTESSORIS — Schema Consolidado v2.0
-- Incluye: tablas, RLS, funciones, triggers y migraciones
-- Ejecutar en Supabase SQL Editor de arriba a abajo.
-- Última actualización: 2026
-- Supabase Project ID: yswizaskeftxpcphixiy
-- Supabase REST API: https://yswizaskeftxpcphixiy.supabase.co/rest/v1/
-- ============================================================

-- ── 0. LIMPIEZA DE FUNCIONES ANTERIORES ──────────────────────
DO $$
DECLARE fn record;
BEGIN
  FOR fn IN
    SELECT p.oid, p.proname, n.nspname
    FROM pg_proc p JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.proname IN (
        'financial_summary_month','generate_report_card','close_period',
        'mark_conversation_read','user_is_participant','generate_monthly_charges',
        'get_current_period','get_tasks_for_period','get_posts_for_period',
        'activate_period','get_student_history','is_period_open','get_active_period',
        'get_student_total_debt','is_teacher_of_classroom','is_parent_of_student',
        'is_parent_of_classroom','is_teacher_of_student','get_my_classroom_ids',
        'run_payment_cycle','get_unread_counts','get_dashboard_kpis',
        'get_monthly_financial_report_by_classroom','attendance_last_7_days',
        'find_or_create_private_conversation','get_direct_messages',
        'send_notification','get_my_role','can_access_app','handle_new_user',
        'handle_new_post_teacher_info','update_post_comments_count',
        'update_post_likes_count','handle_student_chat_creation',
        'notify_parent_on_new_charge','create_students_snapshot',
        'create_payments_snapshot','cleanup_old_login_attempts',
        'assign_student_to_classroom','assign_students_bulk','set_updated_at',
        'upload_payment_proof','generate_monthly_charges','calculate_mora',
        'preview_payment_cycle','check_payment_cycle_health',
        'process_door_punch','process_student_punch','approve_payment',
        'delete_payment','waive_payment_mora','reset_payment_to_pending',
        'calc_mora','is_email_under_attack','activate_period',
        'get_posts_for_parent','get_posts_for_period','mark_messages_read',
        'search_students','update_staff_permits_timestamp'
      )
  LOOP
    EXECUTE format('DROP FUNCTION IF EXISTS %I.%I(%s) CASCADE',
      fn.nspname, fn.proname,
      pg_get_function_identity_arguments(fn.oid));
  END LOOP;
END $$;

-- ── 1. EXTENSIONES ──────────────────────────────────────────
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ── 2. TABLAS ────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.profiles (
  id                  uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email               text UNIQUE,
  name                text,
  matricula           text UNIQUE,
  role                text CHECK (role IN ('directora','maestra','padre','asistente','admin')),
  avatar_url          text,
  phone               text,
  bio                 text,
  notes               text,
  access_code         text UNIQUE,
  onesignal_player_id text,
  qr_code             text,
  deleted_at          timestamp with time zone,
  accepted_terms      boolean DEFAULT false,
  accepted_terms_at   timestamp with time zone,
  last_sign_in_at     timestamp with time zone,
  search_vector       tsvector GENERATED ALWAYS AS (
    to_tsvector('simple', coalesce(name,'') || ' ' || coalesce(email,'') || ' ' || coalesce(phone,''))
  ) STORED,
  created_at          timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.classrooms (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       text NOT NULL,
  level      text,
  capacity   integer DEFAULT 20,
  teacher_id uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  is_live    boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.students (
  id                      bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                    text NOT NULL,
  classroom_id            bigint REFERENCES public.classrooms(id) ON DELETE SET NULL,
  parent_id               uuid REFERENCES public.profiles(id),
  is_active               boolean DEFAULT true,
  avatar_url              text,
  matricula               text,
  age                     integer,
  age_type                text DEFAULT 'años' CHECK (age_type IN ('años','meses')),
  schedule                text,
  start_date              date,
  blood_type              text,
  allergies               text,
  authorized_pickup       text,
  authorized_pickup_phone text,
  p1_name                 text, p1_phone text, p1_email text,
  p1_job                  text, p1_address text, p1_emergency_contact text,
  p2_name                 text, p2_phone text, p2_email text,
  p2_job                  text, p2_address text, p2_emergency_contact text,
  monthly_fee             numeric DEFAULT 0,
  prolongado_fee          numeric DEFAULT 0,
  due_day                 integer DEFAULT 5,
  qr_code                 text,
  deleted_at              timestamp with time zone,
  search_vector           tsvector GENERATED ALWAYS AS (
    to_tsvector('simple',
      coalesce(name,'') || ' ' || coalesce(matricula,'') || ' ' ||
      coalesce(p1_name,'') || ' ' || coalesce(p1_phone,''))
  ) STORED,
  created_at              timestamp with time zone DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_students_matricula ON public.students(matricula) WHERE matricula IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.attendance (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id bigint REFERENCES public.classrooms(id),
  date         date DEFAULT current_date,
  status       text CHECK (status IN ('present','absent','late','retirado')),
  check_in     timestamp with time zone,
  check_out    timestamp with time zone,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, date)
);

CREATE TABLE IF NOT EXISTS public.attendance_requests (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint REFERENCES public.students(id) ON DELETE CASCADE,
  date       date NOT NULL,
  reason     text NOT NULL,
  note       text,
  status     text DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')),
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.periods (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name         text NOT NULL,
  start_date   date NOT NULL,
  end_date     date NOT NULL,
  status       text DEFAULT 'open' CHECK (status IN ('open','closed')),
  is_active    boolean DEFAULT false,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.tasks (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id   bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  teacher_id     uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  period_id      bigint REFERENCES public.periods(id) ON DELETE SET NULL,
  title          text NOT NULL,
  description    text,
  due_date       timestamp with time zone,
  file_url       text,
  grading_system text DEFAULT 'letter_stars',
  created_at     timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.task_evidences (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id      bigint REFERENCES public.tasks(id) ON DELETE CASCADE,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  parent_id    uuid REFERENCES public.profiles(id),
  file_url     text,
  comment      text,
  status       text DEFAULT 'submitted',
  grade_letter text CHECK (grade_letter IN ('A','B','C','D')),
  stars        integer CHECK (stars >= 1 AND stars <= 5),
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(task_id, student_id)
);

CREATE TABLE IF NOT EXISTS public.posts (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id   bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  teacher_id     uuid REFERENCES public.profiles(id),
  period_id      bigint REFERENCES public.periods(id) ON DELETE SET NULL,
  content        text,
  media_url      text,
  media_type     text,
  image_url      text,
  images         text[] DEFAULT '{}',
  title          text,
  teacher_name   text,
  teacher_avatar text,
  likes_count    integer DEFAULT 0,
  comments_count integer DEFAULT 0,
  updated_at     timestamp with time zone DEFAULT now(),
  created_at     timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.comments (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id    bigint REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id    uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  user_name  text,
  content    text NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.likes (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id       bigint REFERENCES public.posts(id) ON DELETE CASCADE,
  user_id       uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  reaction_type text DEFAULT 'like',
  created_at    timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(post_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.conversations (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type         text DEFAULT 'direct_message'
               CHECK (type IN ('direct_message','private','classroom','group')),
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE SET NULL,
  updated_at   timestamp with time zone DEFAULT now(),
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.conversation_participants (
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE,
  user_id         uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  PRIMARY KEY(conversation_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.messages (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  conversation_id bigint REFERENCES public.conversations(id) ON DELETE CASCADE,
  sender_id       uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  receiver_id     uuid REFERENCES public.profiles(id),
  content         text NOT NULL,
  is_read         boolean DEFAULT false,
  read_at         timestamp with time zone,
  created_at      timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.notifications (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  title      text NOT NULL,
  message    text NOT NULL,
  type       text DEFAULT 'info',
  link       text,
  is_read    boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.payments (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id    bigint REFERENCES public.students(id) ON DELETE CASCADE,
  amount        numeric(10,2) NOT NULL,
  concept       text DEFAULT 'Mensualidad',
  status        text DEFAULT 'pending',
  month_paid    text,
  due_date      date,
  paid_date     timestamp with time zone,
  method        text,
  bank          text,
  reference     text,
  transfer_date date,
  proof_url     text,
  evidence_url  text,
  notes         text,
  validated_by  uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  recorded_by   uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  last_reminder_sent timestamp with time zone,
  deleted_at    timestamp with time zone,
  updated_at    timestamp with time zone DEFAULT now(),
  created_at    timestamp with time zone DEFAULT now() NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_payments_unique_student_month
  ON public.payments(student_id, month_paid) WHERE month_paid IS NOT NULL AND deleted_at IS NULL;

CREATE TABLE IF NOT EXISTS public.payment_audit_log (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  payment_id  bigint,
  action      text NOT NULL,
  old_status  text,
  new_status  text,
  changed_by  uuid REFERENCES public.profiles(id),
  changed_at  timestamp with time zone DEFAULT now() NOT NULL,
  details     jsonb DEFAULT '{}'
);
ALTER TABLE public.payment_audit_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "audit_log_staff" ON public.payment_audit_log;
CREATE POLICY "audit_log_staff" ON public.payment_audit_log FOR SELECT
  USING (
    (SELECT role FROM public.profiles WHERE id = auth.uid() LIMIT 1)
    IN ('directora','asistente','admin')
  );

CREATE TABLE IF NOT EXISTS public.incidents (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  teacher_id   uuid REFERENCES public.profiles(id),
  severity     text CHECK (severity IN ('leve','media','alta')),
  status       text DEFAULT 'received'
               CHECK (status IN ('received','review','resolved','archived')),
  description  text,
  reported_at  timestamp with time zone DEFAULT now() NOT NULL,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.daily_logs (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  date         date DEFAULT current_date,
  mood         text, food text, nap text, eating text, sleeping text,
  activities   text, notes text,
  infant_data  jsonb DEFAULT '[]'::jsonb,
  status       text DEFAULT 'published' CHECK (status IN ('draft','published')),
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, date)
);

CREATE TABLE IF NOT EXISTS public.classroom_gallery (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  image_url    text NOT NULL,
  caption      text,
  date         date DEFAULT current_date,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.classroom_chat (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  user_id      uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  message      text NOT NULL,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.grades (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id bigint REFERENCES public.classrooms(id),
  period_id    bigint REFERENCES public.periods(id),
  subject      text, score numeric(4,2), period text,
  teacher_id   uuid REFERENCES public.profiles(id),
  notes        text,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.report_cards (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id      bigint REFERENCES public.students(id) ON DELETE CASCADE,
  classroom_id    bigint REFERENCES public.classrooms(id),
  period_id       bigint REFERENCES public.periods(id),
  task_avg        numeric(4,2), formal_avg numeric(4,2), final_score numeric(4,2),
  level           text, teacher_comment text,
  generated_at    timestamp with time zone DEFAULT now(),
  UNIQUE(student_id, period_id)
);

CREATE TABLE IF NOT EXISTS public.inquiries (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id    uuid REFERENCES public.profiles(id) NOT NULL,
  student_id   bigint REFERENCES public.students(id),
  subject      text, message text NOT NULL, response text,
  status       text DEFAULT 'pending', priority text DEFAULT 'medium',
  folio        text, attachment_url text,
  updated_at   timestamp with time zone,
  responded_at timestamp with time zone,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.school_settings (
  id               int PRIMARY KEY DEFAULT 1,
  phone            text DEFAULT '(829) 803-8424',
  business_hours   text DEFAULT 'Lun-Vie: 7am - 6pm',
  generation_day   int DEFAULT 25,
  due_day          int DEFAULT 5,
  check_in_start   time DEFAULT '07:30:00',
  check_in_end     time DEFAULT '08:30:00',
  check_out_start  time DEFAULT '16:00:00',
  check_out_end    time DEFAULT '17:30:00',
  open_time        time DEFAULT '07:00:00',
  close_time       time DEFAULT '18:00:00',
  work_days        text DEFAULT '["Lun","Mar","Mié","Jue","Vie"]',
  updated_at       timestamp with time zone DEFAULT now()
);
INSERT INTO public.school_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

CREATE TABLE IF NOT EXISTS public.system_events (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type         text NOT NULL, payload jsonb,
  status       text DEFAULT 'pending' CHECK (status IN ('pending','processing','completed','failed')),
  processed_at timestamp with time zone,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.terms_acceptance (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  accepted_at   timestamp with time zone DEFAULT now() NOT NULL,
  terms_version text DEFAULT '1.0' NOT NULL,
  UNIQUE(user_id, terms_version)
);

CREATE TABLE IF NOT EXISTS public.meetings (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title       text NOT NULL, description text, room_name text NOT NULL,
  start_time  timestamp with time zone,
  type        text DEFAULT 'classroom', target_id bigint,
  host_id     uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  status      text DEFAULT 'scheduled' CHECK (status IN ('scheduled','live','ended','cancelled')),
  created_at  timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  action     text NOT NULL,
  payload    jsonb,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.data_snapshots (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type        text NOT NULL,
  data        jsonb,
  created_at  timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE IF NOT EXISTS public.login_attempts (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email      text, ip_hash text, success boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.door_punches (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id   bigint REFERENCES public.students(id) ON DELETE CASCADE,
  staff_id     uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  punch_type   text NOT NULL CHECK (punch_type IN ('check_in','check_out')),
  punched_at   timestamp with time zone DEFAULT now() NOT NULL,
  date         date DEFAULT current_date NOT NULL,
  parent_notified boolean DEFAULT false,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT door_punches_student_type_date UNIQUE (student_id, punch_type, date),
  CONSTRAINT door_punches_staff_type_date   UNIQUE (staff_id, punch_type, date),
  CONSTRAINT door_punches_one_subject CHECK (
    (student_id IS NOT NULL AND staff_id IS NULL) OR
    (student_id IS NULL AND staff_id IS NOT NULL)
  )
);

-- Tabla de permisos de personal
DO $$ BEGIN
  CREATE TYPE permit_status AS ENUM ('pending','approved','rejected');
  CREATE TYPE permit_type   AS ENUM ('permission','absence','medical','other');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.staff_permits (
  id          uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  staff_id    uuid REFERENCES public.profiles(id) ON DELETE CASCADE,
  type        permit_type DEFAULT 'permission',
  reason      text NOT NULL,
  start_date  date NOT NULL,
  end_date    date NOT NULL,
  status      permit_status DEFAULT 'pending',
  approved_by uuid REFERENCES public.profiles(id),
  comments    text,
  evidence_url text,
  created_at  timestamp with time zone DEFAULT now(),
  updated_at  timestamp with time zone DEFAULT now()
);

GRANT ALL ON public.staff_permits TO authenticated;

-- ── 3. ÍNDICES DE RENDIMIENTO ────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_students_search_vector     ON public.students USING GIN (search_vector);
CREATE INDEX IF NOT EXISTS idx_profiles_search_vector     ON public.profiles USING GIN (search_vector);
CREATE INDEX IF NOT EXISTS idx_students_name_lower        ON public.students (lower(name));
CREATE INDEX IF NOT EXISTS idx_students_parent            ON public.students (parent_id);
CREATE INDEX IF NOT EXISTS idx_students_classroom         ON public.students (classroom_id);
CREATE INDEX IF NOT EXISTS idx_students_active_fee        ON public.students (is_active, monthly_fee) WHERE is_active = true AND monthly_fee > 0;
CREATE INDEX IF NOT EXISTS idx_payments_month_paid        ON public.payments (month_paid);
CREATE INDEX IF NOT EXISTS idx_payments_student_month     ON public.payments (student_id, month_paid);
CREATE INDEX IF NOT EXISTS idx_payments_status            ON public.payments (status);
CREATE INDEX IF NOT EXISTS idx_payments_month_status      ON public.payments (month_paid, status) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_payments_overdue_reminder  ON public.payments (status, due_date, last_reminder_sent) WHERE status = 'overdue';
CREATE INDEX IF NOT EXISTS idx_profiles_role              ON public.profiles (role);
CREATE INDEX IF NOT EXISTS idx_profiles_name_lower        ON public.profiles (lower(name));
CREATE INDEX IF NOT EXISTS idx_notifications_user_unread  ON public.notifications (user_id, is_read) WHERE is_read = false;
CREATE INDEX IF NOT EXISTS idx_messages_conversation      ON public.messages (conversation_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_attendance_classroom_date  ON public.attendance (classroom_id, date);
CREATE INDEX IF NOT EXISTS idx_attendance_student_date    ON public.attendance (student_id, date);
CREATE INDEX IF NOT EXISTS idx_posts_created_at           ON public.posts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_posts_classroom_id         ON public.posts (classroom_id) WHERE classroom_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_door_punches_date          ON public.door_punches (date);
CREATE INDEX IF NOT EXISTS idx_door_punches_student       ON public.door_punches (student_id, date);
CREATE INDEX IF NOT EXISTS idx_door_punches_staff         ON public.door_punches (staff_id, date);
CREATE INDEX IF NOT EXISTS idx_tasks_period               ON public.tasks (period_id, classroom_id);
CREATE INDEX IF NOT EXISTS idx_posts_period               ON public.posts (period_id, classroom_id);
CREATE INDEX IF NOT EXISTS idx_grades_period              ON public.grades (period_id, student_id);
CREATE INDEX IF NOT EXISTS idx_login_attempts_email_time  ON public.login_attempts (email, created_at DESC, success);
CREATE INDEX IF NOT EXISTS idx_audit_logs_payload         ON public.audit_logs USING GIN (payload jsonb_path_ops) WHERE payload IS NOT NULL;

-- ── 4. RLS ENABLE ────────────────────────────────────────────
ALTER TABLE public.profiles              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classrooms            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.students              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance_requests   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_evidences        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.posts                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.comments              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.likes                 ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_participants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payments              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.incidents             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.daily_logs            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_gallery     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_chat        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.grades                ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.periods               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.report_cards          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.inquiries             ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.school_settings       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.system_events         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.terms_acceptance      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings              ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.data_snapshots        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.login_attempts        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.door_punches          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_permits         ENABLE ROW LEVEL SECURITY;

-- ── 5. FUNCIONES AUXILIARES ───────────────────────────────────

CREATE OR REPLACE FUNCTION public.get_my_role()
RETURNS text LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT role FROM public.profiles WHERE id = auth.uid() LIMIT 1;
$$;
GRANT EXECUTE ON FUNCTION public.get_my_role() TO authenticated, anon;

CREATE OR REPLACE FUNCTION public.is_teacher_of_classroom(p_classroom_id bigint)
RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.classrooms WHERE id = p_classroom_id AND teacher_id = auth.uid());
$$;

CREATE OR REPLACE FUNCTION public.is_parent_of_student(p_student_id bigint)
RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.students WHERE id = p_student_id AND parent_id = auth.uid());
$$;

CREATE OR REPLACE FUNCTION public.is_parent_of_classroom(p_classroom_id bigint)
RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.students WHERE classroom_id = p_classroom_id AND parent_id = auth.uid());
$$;

CREATE OR REPLACE FUNCTION public.is_teacher_of_student(p_student_id bigint)
RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.students s
    JOIN public.classrooms c ON c.id = s.classroom_id
    WHERE s.id = p_student_id AND c.teacher_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION public.get_my_classroom_ids()
RETURNS TABLE(ret_id bigint) LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT s.classroom_id::bigint FROM public.students s
  WHERE s.parent_id = auth.uid() AND s.classroom_id IS NOT NULL AND s.deleted_at IS NULL;
$$;

CREATE OR REPLACE FUNCTION public.user_is_participant(p_conversation_id bigint, p_user_id uuid)
RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.conversation_participants
    WHERE conversation_id = p_conversation_id AND user_id = p_user_id
  );
$$;

CREATE OR REPLACE FUNCTION public.is_period_open(p_period_id bigint)
RETURNS boolean LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT EXISTS (SELECT 1 FROM public.periods WHERE id = p_period_id AND status = 'open');
$$;

CREATE OR REPLACE FUNCTION public.assign_student_to_classroom(p_student_id bigint, p_classroom_id bigint)
RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  UPDATE public.students SET classroom_id = p_classroom_id WHERE id = p_student_id;
$$;
GRANT EXECUTE ON FUNCTION public.assign_student_to_classroom(bigint, bigint) TO authenticated;

CREATE OR REPLACE FUNCTION public.assign_students_bulk(p_student_ids bigint[], p_classroom_id bigint)
RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  UPDATE public.students SET classroom_id = p_classroom_id WHERE id = ANY(p_student_ids);
$$;
GRANT EXECUTE ON FUNCTION public.assign_students_bulk(bigint[], bigint) TO authenticated;

-- ── 6. FUNCIONES DE NEGOCIO ───────────────────────────────────

-- Mora calculada en servidor: RD$50/día, cada 7 días = bloque de RD$500
CREATE OR REPLACE FUNCTION public.calc_mora(p_due_date date)
RETURNS numeric LANGUAGE plpgsql IMMUTABLE AS $$
DECLARE v_days int; BEGIN
  v_days := (CURRENT_DATE - p_due_date)::int;
  IF v_days <= 0 THEN RETURN 0; END IF;
  RETURN (v_days / 7) * 500 + (v_days % 7) * 50;
END;
$$;

-- Vista de pagos con mora calculada
CREATE OR REPLACE VIEW public.v_payments_with_mora AS
SELECT p.*, public.calc_mora(p.due_date) AS mora_amount,
  p.amount + public.calc_mora(p.due_date) AS total_due,
  (CURRENT_DATE - p.due_date)::int AS days_late,
  s.name AS student_name, s.p1_name AS parent_name, s.p1_email AS parent_email,
  c.name AS classroom_name
FROM public.payments p
LEFT JOIN public.students s ON s.id = p.student_id
LEFT JOIN public.classrooms c ON c.id = s.classroom_id
WHERE p.deleted_at IS NULL;
GRANT SELECT ON public.v_payments_with_mora TO authenticated;

-- Ciclo de pagos con regla de gracia
CREATE OR REPLACE FUNCTION public.run_payment_cycle()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_gen_day int; v_due_day int;
  v_today   int := extract(day from current_date)::int;
  v_cur_m   int := extract(month from current_date)::int;
  v_cur_y   int := extract(year  from current_date)::int;
  v_tgt_m   int; v_tgt_y int; v_due_m int; v_due_y int;
  v_gen_cnt int := 0; v_exp_cnt int := 0;
  v_due_date date; v_month_key text;
  v_role text;
BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role NOT IN ('directora','asistente','admin') THEN
    RAISE EXCEPTION 'Acceso denegado';
  END IF;
  SELECT COALESCE(generation_day,25), COALESCE(due_day,5) INTO v_gen_day, v_due_day
  FROM public.school_settings WHERE id = 1;
  IF v_gen_day IS NULL THEN RETURN jsonb_build_object('error','school_settings no encontrado'); END IF;
  v_tgt_m := v_cur_m + 1; v_tgt_y := v_cur_y;
  IF v_tgt_m > 12 THEN v_tgt_m := 1; v_tgt_y := v_tgt_y + 1; END IF;
  v_month_key := v_tgt_y || '-' || LPAD(v_tgt_m::text,2,'0');
  v_due_m := v_tgt_m + 1; v_due_y := v_tgt_y;
  IF v_due_m > 12 THEN v_due_m := 1; v_due_y := v_due_y + 1; END IF;
  v_due_date := make_date(v_due_y, v_due_m, v_due_day);
  INSERT INTO public.payments (student_id, amount, status, due_date, month_paid, concept)
  SELECT s.id, s.monthly_fee, 'pending', v_due_date, v_month_key, 'Mensualidad'
  FROM public.students s
  WHERE s.is_active = true AND s.monthly_fee > 0 AND s.deleted_at IS NULL
    AND (s.start_date IS NULL OR (
      CASE WHEN extract(day from s.start_date) < v_gen_day
        THEN make_date(extract(year from s.start_date)::int, extract(month from s.start_date)::int, 1) + interval '1 month'
        ELSE make_date(extract(year from s.start_date)::int, extract(month from s.start_date)::int, 1) + interval '2 months'
      END <= make_date(v_tgt_y, v_tgt_m, 1)))
    AND NOT EXISTS (SELECT 1 FROM public.payments p
      WHERE p.student_id = s.id AND p.month_paid = v_month_key AND p.deleted_at IS NULL);
  GET DIAGNOSTICS v_gen_cnt = ROW_COUNT;
  UPDATE public.payments SET status = 'overdue'
  WHERE status = 'pending' AND due_date < CURRENT_DATE AND deleted_at IS NULL;
  GET DIAGNOSTICS v_exp_cnt = ROW_COUNT;
  RETURN jsonb_build_object('generated', v_gen_cnt, 'expired', v_exp_cnt, 'month', v_month_key);
END;
$$;
GRANT EXECUTE ON FUNCTION public.run_payment_cycle() TO authenticated;

-- Exoneración de mora
CREATE OR REPLACE FUNCTION public.waive_payment_mora(p_payment_id bigint, p_reason text DEFAULT 'Mora exonerada')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  UPDATE public.payments SET due_date = CURRENT_DATE, last_reminder_sent = NULL,
    notes = COALESCE(notes || ' | ', '') || p_reason || ' (' || to_char(now(),'DD/MM/YYYY') || ')'
  WHERE id = p_payment_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('error','Pago no encontrado'); END IF;
  RETURN jsonb_build_object('success', true, 'payment_id', p_payment_id);
END;
$$;
GRANT EXECUTE ON FUNCTION public.waive_payment_mora(bigint, text) TO authenticated;

-- Aprobar pago (RPC seguro)
CREATE OR REPLACE FUNCTION public.approve_payment(p_payment_id bigint, p_notes text DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_role text; BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role NOT IN ('directora','asistente','admin') THEN RETURN jsonb_build_object('error','No autorizado'); END IF;
  UPDATE public.payments SET status='paid', paid_date=now(), validated_by=auth.uid(), notes=COALESCE(p_notes,notes)
  WHERE id = p_payment_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('error','Pago no encontrado'); END IF;
  RETURN jsonb_build_object('success', true, 'payment_id', p_payment_id);
END;
$$;
GRANT EXECUTE ON FUNCTION public.approve_payment(bigint, text) TO authenticated;

-- Eliminar pago (soft delete)
CREATE OR REPLACE FUNCTION public.delete_payment(p_payment_id bigint, p_reason text DEFAULT 'Eliminado')
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_role text; BEGIN
  SELECT role INTO v_role FROM public.profiles WHERE id = auth.uid();
  IF v_role NOT IN ('directora','asistente','admin') THEN RETURN jsonb_build_object('error','No autorizado'); END IF;
  UPDATE public.payments SET deleted_at=now(), notes=COALESCE(notes||' | ','')||p_reason WHERE id=p_payment_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('error','Pago no encontrado'); END IF;
  RETURN jsonb_build_object('success', true, 'payment_id', p_payment_id);
END;
$$;
GRANT EXECUTE ON FUNCTION public.delete_payment(bigint, text) TO authenticated;

-- Chat: buscar o crear conversación privada
CREATE OR REPLACE FUNCTION public.find_or_create_private_conversation(p_user1 uuid, p_user2 uuid)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_conv_id bigint; BEGIN
  SELECT cp1.conversation_id INTO v_conv_id
  FROM public.conversation_participants cp1
  JOIN public.conversation_participants cp2 ON cp2.conversation_id = cp1.conversation_id AND cp2.user_id = p_user2
  JOIN public.conversations c ON c.id = cp1.conversation_id AND c.type = 'direct_message'
  WHERE cp1.user_id = p_user1 LIMIT 1;
  IF v_conv_id IS NOT NULL THEN RETURN v_conv_id; END IF;
  INSERT INTO public.conversations (type) VALUES ('direct_message') RETURNING id INTO v_conv_id;
  INSERT INTO public.conversation_participants (conversation_id, user_id) VALUES (v_conv_id, p_user1),(v_conv_id, p_user2) ON CONFLICT DO NOTHING;
  RETURN v_conv_id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.find_or_create_private_conversation(uuid, uuid) TO authenticated;

-- Chat: mensajes directos con info del sender
DROP FUNCTION IF EXISTS public.get_direct_messages(uuid);
CREATE OR REPLACE FUNCTION public.get_direct_messages(p_other_user_id uuid)
RETURNS TABLE (id bigint, conversation_id bigint, sender_id uuid, receiver_id uuid,
  content text, is_read boolean, created_at timestamp with time zone,
  sender_name text, sender_avatar text)
LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT m.id, m.conversation_id, m.sender_id, m.receiver_id, m.content, m.is_read, m.created_at,
    p.name AS sender_name, p.avatar_url AS sender_avatar
  FROM public.messages m
  LEFT JOIN public.profiles p ON m.sender_id = p.id
  WHERE m.conversation_id = (
    SELECT c.id FROM public.conversations c
    WHERE c.type IN ('direct_message','private')
      AND EXISTS (SELECT 1 FROM public.conversation_participants x WHERE x.conversation_id = c.id AND x.user_id = auth.uid())
      AND EXISTS (SELECT 1 FROM public.conversation_participants y WHERE y.conversation_id = c.id AND y.user_id = p_other_user_id)
    LIMIT 1
  )
  ORDER BY m.created_at ASC
  LIMIT 50;
$$;
GRANT EXECUTE ON FUNCTION public.get_direct_messages(uuid) TO authenticated;

-- Chat: marcar mensajes como leídos
CREATE OR REPLACE FUNCTION public.mark_messages_read(p_conversation_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL OR p_conversation_id IS NULL THEN RETURN; END IF;
  UPDATE public.messages SET is_read = true
  WHERE conversation_id = p_conversation_id AND sender_id <> auth.uid() AND (is_read IS NULL OR is_read = false);
END;
$$;
GRANT EXECUTE ON FUNCTION public.mark_messages_read(bigint) TO authenticated;

-- Chat: conteo de mensajes no leídos
CREATE OR REPLACE FUNCTION public.get_unread_counts()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_user_id uuid := auth.uid(); v_result jsonb; BEGIN
  IF v_user_id IS NULL THEN RETURN '{}'::jsonb; END IF;
  SELECT jsonb_object_agg(m.sender_id, m.cnt) INTO v_result
  FROM (
    SELECT m.sender_id, count(*) AS cnt
    FROM public.messages m
    JOIN public.conversation_participants cp ON cp.conversation_id = m.conversation_id AND cp.user_id = v_user_id
    WHERE m.sender_id <> v_user_id AND (m.is_read IS NULL OR m.is_read = false)
    GROUP BY m.sender_id
  ) m;
  v_result := jsonb_set(COALESCE(v_result,'{}'), '{total}',
    to_jsonb(COALESCE((SELECT SUM(value::bigint) FROM jsonb_each_text(COALESCE(v_result,'{}'))),0)));
  RETURN v_result;
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_unread_counts() TO authenticated;

-- Ponche de puerta (asistencia QR) con zona horaria RD
CREATE OR REPLACE FUNCTION public.process_door_punch(p_code text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_student record; v_staff record; v_settings record;
  v_today   date := (now() AT TIME ZONE 'America/Santo_Domingo')::date;
  v_now     timestamp with time zone := now();
  v_local   time := (v_now AT TIME ZONE 'America/Santo_Domingo')::time;
  v_type    text; v_name text; v_role text; v_parent uuid;
  v_exist   record; v_att record; v_status text := 'present';
BEGIN
  IF p_code IS NULL OR length(trim(p_code)) < 3 THEN
    RETURN jsonb_build_object('success',false,'message','Código QR inválido');
  END IF;
  SELECT * INTO v_student FROM public.students WHERE matricula = trim(p_code) AND is_active = true LIMIT 1;
  IF FOUND THEN
    v_name := v_student.name; v_role := 'Estudiante'; v_parent := v_student.parent_id;
    SELECT * INTO v_settings FROM public.school_settings WHERE id = 1;
    SELECT * INTO v_exist FROM public.door_punches WHERE student_id = v_student.id AND date = v_today AND punch_type = 'check_in';
    IF NOT FOUND THEN
      v_type := 'check_in';
      IF v_settings.check_in_end IS NOT NULL AND v_local > v_settings.check_in_end THEN v_status := 'late'; END IF;
      SELECT * INTO v_att FROM public.attendance WHERE student_id = v_student.id AND date = v_today;
      IF v_att.id IS NULL THEN
        INSERT INTO public.attendance (student_id, classroom_id, date, status, check_in)
        VALUES (v_student.id, v_student.classroom_id, v_today, v_status, v_now);
      ELSE
        UPDATE public.attendance SET status = v_status, check_in = v_now WHERE id = v_att.id;
      END IF;
      INSERT INTO public.door_punches (student_id, punch_type, punched_at, date) VALUES (v_student.id,'check_in',v_now,v_today) ON CONFLICT DO NOTHING;
    ELSE
      SELECT * INTO v_exist FROM public.door_punches WHERE student_id = v_student.id AND date = v_today AND punch_type = 'check_out';
      IF NOT FOUND THEN
        v_type := 'check_out'; v_status := 'retirado';
        SELECT * INTO v_att FROM public.attendance WHERE student_id = v_student.id AND date = v_today;
        IF v_att.id IS NOT NULL THEN UPDATE public.attendance SET check_out = v_now, status = 'retirado' WHERE id = v_att.id; END IF;
        INSERT INTO public.door_punches (student_id, punch_type, punched_at, date) VALUES (v_student.id,'check_out',v_now,v_today) ON CONFLICT DO NOTHING;
      ELSE
        RETURN jsonb_build_object('success',false,'message',v_name||' ya registró entrada y salida hoy');
      END IF;
    END IF;
    INSERT INTO public.system_events (type, payload) VALUES ('student_punch',
      jsonb_build_object('student_id',v_student.id,'parent_id',v_parent,'type',v_type,'status',v_status));
    RETURN jsonb_build_object('success',true,'type',v_type,'name',v_name,'role',v_role,
      'status',v_status,'student_id',v_student.id,'parent_id',v_parent,
      'time',to_char(v_now AT TIME ZONE 'America/Santo_Domingo','HH12:MI AM'));
  END IF;
  SELECT * INTO v_staff FROM public.profiles
  WHERE (notes=trim(p_code) OR matricula=trim(p_code) OR access_code=trim(p_code))
    AND role IN ('maestra','asistente','directora','admin') LIMIT 1;
  IF NOT FOUND THEN BEGIN SELECT * INTO v_staff FROM public.profiles WHERE id=trim(p_code)::uuid AND role IN ('maestra','asistente','directora','admin') LIMIT 1; EXCEPTION WHEN OTHERS THEN NULL; END; END IF;
  IF FOUND THEN
    v_name := v_staff.name; v_role := initcap(v_staff.role);
    SELECT * INTO v_exist FROM public.door_punches WHERE staff_id = v_staff.id AND date = v_today AND punch_type = 'check_in';
    IF NOT FOUND THEN
      v_type := 'check_in';
      INSERT INTO public.door_punches (staff_id,punch_type,punched_at,date) VALUES (v_staff.id,'check_in',v_now,v_today) ON CONFLICT DO NOTHING;
    ELSE
      SELECT * INTO v_exist FROM public.door_punches WHERE staff_id = v_staff.id AND date = v_today AND punch_type = 'check_out';
      IF NOT FOUND THEN
        v_type := 'check_out';
        INSERT INTO public.door_punches (staff_id,punch_type,punched_at,date) VALUES (v_staff.id,'check_out',v_now,v_today) ON CONFLICT DO NOTHING;
      ELSE RETURN jsonb_build_object('success',false,'message',v_name||' ya registró entrada y salida hoy'); END IF;
    END IF;
    RETURN jsonb_build_object('success',true,'type',v_type,'name',v_name,'role',v_role,
      'student_id',null,'parent_id',null,'time',to_char(v_now AT TIME ZONE 'America/Santo_Domingo','HH12:MI AM'));
  END IF;
  RETURN jsonb_build_object('success',false,'message','QR no registrado en el sistema');
END;
$$;
GRANT EXECUTE ON FUNCTION public.process_door_punch(text) TO authenticated, anon;

-- Notificación de nuevo pago
CREATE OR REPLACE FUNCTION public.send_notification(p_user_id uuid, p_type text, p_message text, p_data jsonb DEFAULT '{}', p_link text DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.notifications (user_id, title, message, type, link, is_read, created_at)
  VALUES (p_user_id, p_type, p_message, p_type, p_link, false, now()) ON CONFLICT DO NOTHING;
EXCEPTION WHEN OTHERS THEN NULL;
END;
$$;
GRANT EXECUTE ON FUNCTION public.send_notification(uuid, text, text, jsonb, text) TO authenticated;

-- Preview del ciclo de pagos
CREATE OR REPLACE FUNCTION public.preview_payment_cycle()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_gen_day int; v_cur_m int := extract(month from current_date)::int;
  v_cur_y int := extract(year from current_date)::int;
  v_tgt_m int; v_tgt_y int; v_month_key text;
  v_count int; v_total numeric; v_grace int; v_existing int;
BEGIN
  SELECT COALESCE(generation_day,25) INTO v_gen_day FROM public.school_settings WHERE id=1;
  v_tgt_m := v_cur_m + 1; v_tgt_y := v_cur_y;
  IF v_tgt_m > 12 THEN v_tgt_m := 1; v_tgt_y := v_tgt_y + 1; END IF;
  v_month_key := v_tgt_y||'-'||LPAD(v_tgt_m::text,2,'0');
  SELECT count(*), COALESCE(sum(monthly_fee+COALESCE(prolongado_fee,0)),0) INTO v_count, v_total
  FROM public.students s WHERE s.is_active=true AND (s.monthly_fee>0 OR COALESCE(s.prolongado_fee,0)>0)
    AND (s.start_date IS NULL OR (
      CASE WHEN extract(day from s.start_date)<v_gen_day
        THEN make_date(extract(year from s.start_date)::int,extract(month from s.start_date)::int,1)+interval'1 month'
        ELSE make_date(extract(year from s.start_date)::int,extract(month from s.start_date)::int,1)+interval'2 months'
      END <= make_date(v_tgt_y,v_tgt_m,1)))
    AND NOT EXISTS (SELECT 1 FROM public.payments p WHERE p.student_id=s.id AND p.month_paid=v_month_key AND p.deleted_at IS NULL);
  SELECT count(DISTINCT student_id) INTO v_existing FROM public.payments WHERE month_paid=v_month_key AND deleted_at IS NULL;
  RETURN jsonb_build_object('target_month',v_month_key,'count',v_count,'total_amount',v_total,'existing_count',v_existing);
END;
$$;
GRANT EXECUTE ON FUNCTION public.preview_payment_cycle() TO authenticated;

-- Healthcheck del ciclo
CREATE OR REPLACE FUNCTION public.check_payment_cycle_health()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_gen_day int; v_today int := extract(day from current_date)::int; v_month_key text; v_ok boolean; BEGIN
  SELECT generation_day INTO v_gen_day FROM public.school_settings WHERE id=1;
  IF v_today < v_gen_day THEN RETURN jsonb_build_object('status','ok','message','Aún no llega el día de generación'); END IF;
  v_month_key := to_char(current_date+interval'1 month','YYYY-MM');
  SELECT EXISTS(SELECT 1 FROM public.payments WHERE month_paid=v_month_key AND concept='Mensualidad' AND deleted_at IS NULL) INTO v_ok;
  IF v_ok THEN RETURN jsonb_build_object('status','ok','message','Ciclo ejecutado correctamente');
  ELSE RETURN jsonb_build_object('status','error','message','El ciclo de pagos no se ha ejecutado todavía'); END IF;
END;
$$;
GRANT EXECUTE ON FUNCTION public.check_payment_cycle_health() TO authenticated;

-- Posts para padre (sin RLS)
CREATE OR REPLACE FUNCTION public.get_posts_for_parent(p_classroom_id bigint DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_result jsonb; BEGIN
  SELECT jsonb_agg(jsonb_build_object(
    'id',p.id,'content',p.content,'media_url',p.media_url,'media_type',p.media_type,
    'image_url',p.image_url,'created_at',p.created_at,'classroom_id',p.classroom_id,
    'teacher_id',p.teacher_id,
    'teacher',jsonb_build_object('name',COALESCE(pr.name,p.teacher_name,'Maestra'),'avatar_url',COALESCE(pr.avatar_url,p.teacher_avatar),'role',pr.role),
    'likes',COALESCE((SELECT jsonb_agg(jsonb_build_object('user_id',l.user_id,'id',l.id)) FROM public.likes l WHERE l.post_id=p.id),'[]'),
    'comments',COALESCE((SELECT jsonb_agg(jsonb_build_object('id',c.id,'content',c.content,'user_name',c.user_name,'user_id',c.user_id,'created_at',c.created_at) ORDER BY c.created_at) FROM public.comments c WHERE c.post_id=p.id),'[]')
  ) ORDER BY p.created_at DESC) INTO v_result
  FROM public.posts p LEFT JOIN public.profiles pr ON pr.id=p.teacher_id
  WHERE p.classroom_id IS NULL OR (p_classroom_id IS NOT NULL AND p.classroom_id=p_classroom_id);
  RETURN COALESCE(v_result,'[]');
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_posts_for_parent(bigint) TO authenticated, anon;

-- Búsqueda full-text de estudiantes
CREATE OR REPLACE FUNCTION public.search_students(query text)
RETURNS SETOF public.students LANGUAGE sql STABLE AS $$
  SELECT * FROM public.students
  WHERE search_vector @@ plainto_tsquery('simple', query)
     OR lower(name) LIKE lower('%'||query||'%')
     OR lower(COALESCE(matricula,'')) LIKE lower('%'||query||'%')
  ORDER BY ts_rank(search_vector, plainto_tsquery('simple', query)) DESC LIMIT 50;
$$;

-- Verificar email bajo ataque
CREATE OR REPLACE FUNCTION public.is_email_under_attack(p_email text)
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public AS $$
  SELECT COUNT(*) >= 10 FROM public.login_attempts
  WHERE email=p_email AND success=false AND created_at > NOW()-INTERVAL'1 hour';
$$;
GRANT EXECUTE ON FUNCTION public.is_email_under_attack(text) TO authenticated;

-- Trigger staff_permits updated_at
CREATE OR REPLACE FUNCTION public.update_staff_permits_timestamp()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;

-- ── 7. TRIGGERS ──────────────────────────────────────────────

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.profiles (id, email, name, role, accepted_terms)
  VALUES (NEW.id, NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'name', split_part(NEW.email,'@',1)),
    COALESCE(NEW.raw_user_meta_data->>'role','padre'), false)
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.handle_new_post_teacher_info()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.teacher_id IS NOT NULL THEN
    NEW.teacher_name   := (SELECT name FROM public.profiles WHERE id=NEW.teacher_id LIMIT 1);
    NEW.teacher_avatar := (SELECT avatar_url FROM public.profiles WHERE id=NEW.teacher_id LIMIT 1);
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS on_new_post_populate_teacher ON public.posts;
CREATE TRIGGER on_new_post_populate_teacher BEFORE INSERT ON public.posts FOR EACH ROW EXECUTE FUNCTION public.handle_new_post_teacher_info();

CREATE OR REPLACE FUNCTION public.update_post_comments_count()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP='INSERT' THEN UPDATE public.posts SET comments_count=comments_count+1 WHERE id=NEW.post_id; RETURN NEW;
  ELSIF TG_OP='DELETE' THEN UPDATE public.posts SET comments_count=GREATEST(0,comments_count-1) WHERE id=OLD.post_id; RETURN OLD;
  END IF; RETURN NULL;
END;
$$;
DROP TRIGGER IF EXISTS on_comment_change_update_count ON public.comments;
CREATE TRIGGER on_comment_change_update_count AFTER INSERT OR DELETE ON public.comments FOR EACH ROW EXECUTE FUNCTION public.update_post_comments_count();

CREATE OR REPLACE FUNCTION public.update_post_likes_count()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF TG_OP='INSERT' THEN UPDATE public.posts SET likes_count=likes_count+1 WHERE id=NEW.post_id; RETURN NEW;
  ELSIF TG_OP='DELETE' THEN UPDATE public.posts SET likes_count=GREATEST(0,likes_count-1) WHERE id=OLD.post_id; RETURN OLD;
  END IF; RETURN NULL;
END;
$$;
DROP TRIGGER IF EXISTS on_like_change_update_count ON public.likes;
CREATE TRIGGER on_like_change_update_count AFTER INSERT OR DELETE ON public.likes FOR EACH ROW EXECUTE FUNCTION public.update_post_likes_count();

CREATE OR REPLACE FUNCTION public.handle_student_chat_creation()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_teacher_id uuid; v_cls_chat bigint; v_dm_chat bigint; BEGIN
  IF NEW.classroom_id IS NULL OR NEW.parent_id IS NULL THEN RETURN NEW; END IF;
  v_teacher_id := (SELECT teacher_id FROM public.classrooms WHERE id=NEW.classroom_id);
  IF v_teacher_id IS NULL THEN RETURN NEW; END IF;
  v_cls_chat := (SELECT id FROM public.conversations WHERE type='classroom' AND classroom_id=NEW.classroom_id LIMIT 1);
  IF v_cls_chat IS NULL THEN
    INSERT INTO public.conversations (type, classroom_id) VALUES ('classroom', NEW.classroom_id) RETURNING id INTO v_cls_chat;
  END IF;
  INSERT INTO public.conversation_participants (conversation_id, user_id)
    VALUES (v_cls_chat, NEW.parent_id),(v_cls_chat, v_teacher_id) ON CONFLICT DO NOTHING;
  v_dm_chat := (SELECT conv.id FROM public.conversations conv
    WHERE conv.type='direct_message'
      AND EXISTS (SELECT 1 FROM public.conversation_participants cp WHERE cp.conversation_id=conv.id AND cp.user_id=NEW.parent_id)
      AND EXISTS (SELECT 1 FROM public.conversation_participants cp WHERE cp.conversation_id=conv.id AND cp.user_id=v_teacher_id)
    LIMIT 1);
  IF v_dm_chat IS NULL THEN
    INSERT INTO public.conversations (type) VALUES ('direct_message') RETURNING id INTO v_dm_chat;
    INSERT INTO public.conversation_participants (conversation_id, user_id) VALUES (v_dm_chat, NEW.parent_id),(v_dm_chat, v_teacher_id);
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS on_student_upsert_chat ON public.students;
CREATE TRIGGER on_student_upsert_chat AFTER INSERT OR UPDATE OF classroom_id, parent_id ON public.students FOR EACH ROW EXECUTE FUNCTION public.handle_student_chat_creation();

CREATE OR REPLACE FUNCTION public.notify_parent_on_new_charge()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_parent_id uuid; v_student_name text; BEGIN
  IF NEW.status='pending' AND NEW.amount>0 THEN
    SELECT parent_id, name INTO v_parent_id, v_student_name FROM public.students WHERE id=NEW.student_id;
    IF v_parent_id IS NOT NULL THEN
      INSERT INTO public.notifications (user_id, title, message, type, link)
      VALUES (v_parent_id, 'Nuevo Cargo Generado',
        'Se generó un cargo de $'||NEW.amount::text||' para '||COALESCE(v_student_name,'Estudiante')||' ('||COALESCE(NEW.month_paid,'Mensualidad')||').',
        'alert', 'panel_padres.html#payments');
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS on_new_payment_charge ON public.payments;
CREATE TRIGGER on_new_payment_charge AFTER INSERT ON public.payments FOR EACH ROW EXECUTE FUNCTION public.notify_parent_on_new_charge();

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END;
$$;
DROP TRIGGER IF EXISTS set_updated_at_posts         ON public.posts;
DROP TRIGGER IF EXISTS set_updated_at_conversations ON public.conversations;
DROP TRIGGER IF EXISTS set_updated_at_inquiries     ON public.inquiries;
DROP TRIGGER IF EXISTS set_updated_at_payments      ON public.payments;
CREATE TRIGGER set_updated_at_posts         BEFORE UPDATE ON public.posts         FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER set_updated_at_conversations BEFORE UPDATE ON public.conversations  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER set_updated_at_inquiries     BEFORE UPDATE ON public.inquiries      FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER set_updated_at_payments      BEFORE UPDATE ON public.payments       FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

DROP TRIGGER IF EXISTS tr_update_staff_permits_timestamp ON public.staff_permits;
CREATE TRIGGER tr_update_staff_permits_timestamp BEFORE UPDATE ON public.staff_permits FOR EACH ROW EXECUTE FUNCTION public.update_staff_permits_timestamp();

-- Auditoría inmutable de pagos
CREATE OR REPLACE FUNCTION public.fn_audit_payment()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_action text; v_payload jsonb; BEGIN
  IF TG_OP='INSERT' THEN
    v_action:='payment.created';
    v_payload:=jsonb_build_object('payment_id',NEW.id,'student_id',NEW.student_id,'amount',NEW.amount,'month',NEW.month_paid,'status',NEW.status);
  ELSIF TG_OP='UPDATE' THEN
    IF OLD.status IS DISTINCT FROM NEW.status OR OLD.amount IS DISTINCT FROM NEW.amount THEN
      v_action:=CASE WHEN NEW.status='paid' AND OLD.status!='paid' THEN 'payment.approved'
                     WHEN NEW.status='overdue' THEN 'payment.overdue'
                     WHEN NEW.status='rejected' THEN 'payment.rejected'
                     ELSE 'payment.updated' END;
      v_payload:=jsonb_build_object('payment_id',NEW.id,'old_status',OLD.status,'new_status',NEW.status,'amount',NEW.amount,'month',NEW.month_paid);
    ELSE RETURN NEW; END IF;
  ELSIF TG_OP='DELETE' THEN
    v_action:='payment.deleted';
    v_payload:=jsonb_build_object('payment_id',OLD.id,'student_id',OLD.student_id,'amount',OLD.amount,'month',OLD.month_paid);
  END IF;
  INSERT INTO public.audit_logs (user_id, action, payload, created_at) VALUES (auth.uid(), v_action, v_payload, now());
  RETURN COALESCE(NEW, OLD);
END;
$$;
DROP TRIGGER IF EXISTS trg_audit_payment ON public.payments;
CREATE TRIGGER trg_audit_payment AFTER INSERT OR UPDATE OR DELETE ON public.payments FOR EACH ROW EXECUTE FUNCTION public.fn_audit_payment();

-- ── 8. POLÍTICAS RLS ─────────────────────────────────────────

-- Eliminar políticas existentes
DO $$
DECLARE pol record;
BEGIN
  FOR pol IN SELECT policyname, tablename FROM pg_policies WHERE schemaname='public' LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I', pol.policyname, pol.tablename);
  END LOOP;
END $$;

-- PROFILES
CREATE POLICY "profiles_select" ON public.profiles FOR SELECT USING (
  deleted_at IS NULL AND (auth.uid()=id OR get_my_role() IN ('directora','asistente','maestra','admin') OR auth.uid() IS NOT NULL)
);
CREATE POLICY "profiles_insert" ON public.profiles FOR INSERT WITH CHECK (
  auth.uid()=id OR get_my_role() IN ('directora','asistente','admin')
);
CREATE POLICY "profiles_update" ON public.profiles FOR UPDATE USING (
  (auth.uid()=id OR get_my_role() IN ('directora','asistente','admin')) AND deleted_at IS NULL
);
CREATE POLICY "profiles_delete" ON public.profiles FOR DELETE USING (get_my_role() IN ('directora','asistente','admin'));

-- CLASSROOMS
CREATE POLICY "classrooms_staff" ON public.classrooms FOR ALL
  USING (get_my_role() IN ('directora','asistente','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','admin'));
CREATE POLICY "classrooms_teacher" ON public.classrooms FOR SELECT USING (teacher_id=auth.uid());
CREATE POLICY "classrooms_parent"  ON public.classrooms FOR SELECT USING (id IN (SELECT ret_id FROM public.get_my_classroom_ids()));

-- STUDENTS
CREATE POLICY "students_staff" ON public.students FOR ALL
  USING (get_my_role() IN ('directora','asistente','admin') AND deleted_at IS NULL)
  WITH CHECK (get_my_role() IN ('directora','asistente','admin'));
CREATE POLICY "students_teacher"          ON public.students FOR SELECT USING (is_teacher_of_student(id) AND deleted_at IS NULL);
CREATE POLICY "students_parent_own"       ON public.students FOR SELECT USING (parent_id=auth.uid() AND deleted_at IS NULL);
CREATE POLICY "students_parent_update"    ON public.students FOR UPDATE USING (parent_id=auth.uid() AND deleted_at IS NULL) WITH CHECK (parent_id=auth.uid());
CREATE POLICY "students_parent_classmates" ON public.students FOR SELECT USING (
  classroom_id IN (SELECT ret_id FROM public.get_my_classroom_ids()) AND deleted_at IS NULL
);

-- ATTENDANCE
CREATE POLICY "attendance_staff"   ON public.attendance FOR ALL USING (get_my_role() IN ('directora','asistente','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','admin'));
CREATE POLICY "attendance_teacher" ON public.attendance FOR ALL USING (is_teacher_of_classroom(classroom_id)) WITH CHECK (is_teacher_of_classroom(classroom_id));
CREATE POLICY "attendance_parent"  ON public.attendance FOR SELECT USING (EXISTS (SELECT 1 FROM public.students WHERE id=attendance.student_id AND parent_id=auth.uid()));

-- ATTENDANCE REQUESTS
CREATE POLICY "att_req_staff"          ON public.attendance_requests FOR ALL USING (get_my_role() IN ('directora','asistente','maestra','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','maestra','admin'));
CREATE POLICY "att_req_parent_insert"  ON public.attendance_requests FOR INSERT WITH CHECK (is_parent_of_student(student_id));
CREATE POLICY "att_req_parent_select"  ON public.attendance_requests FOR SELECT USING (is_parent_of_student(student_id));

-- TASKS
CREATE POLICY "tasks_staff"   ON public.tasks FOR ALL USING (get_my_role() IN ('directora','asistente','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','admin'));
CREATE POLICY "tasks_teacher" ON public.tasks FOR ALL USING (is_teacher_of_classroom(classroom_id)) WITH CHECK (is_teacher_of_classroom(classroom_id));
CREATE POLICY "tasks_parent"  ON public.tasks FOR SELECT USING (is_parent_of_classroom(classroom_id));

-- TASK EVIDENCES
CREATE POLICY "evidences_staff"          ON public.task_evidences FOR ALL USING (get_my_role() IN ('directora','asistente','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','admin'));
CREATE POLICY "evidences_teacher"        ON public.task_evidences FOR ALL USING (EXISTS (SELECT 1 FROM public.tasks t WHERE t.id=task_evidences.task_id AND is_teacher_of_classroom(t.classroom_id))) WITH CHECK (EXISTS (SELECT 1 FROM public.tasks t WHERE t.id=task_evidences.task_id AND is_teacher_of_classroom(t.classroom_id)));
CREATE POLICY "evidences_parent_insert"  ON public.task_evidences FOR INSERT WITH CHECK (auth.uid()=parent_id);
CREATE POLICY "evidences_parent_select"  ON public.task_evidences FOR SELECT USING (auth.uid()=parent_id OR EXISTS (SELECT 1 FROM public.students WHERE id=task_evidences.student_id AND parent_id=auth.uid()));

-- POSTS
CREATE POLICY "posts_select" ON public.posts FOR SELECT USING (auth.uid() IS NOT NULL AND (get_my_role() IN ('directora','asistente','admin','maestra') OR classroom_id IS NULL OR is_teacher_of_classroom(classroom_id) OR is_parent_of_classroom(classroom_id)));
CREATE POLICY "posts_insert" ON public.posts FOR INSERT WITH CHECK (get_my_role() IN ('directora','asistente','maestra','admin'));
CREATE POLICY "posts_update" ON public.posts FOR UPDATE USING (get_my_role() IN ('directora','asistente','admin') OR auth.uid()=teacher_id);
CREATE POLICY "posts_delete" ON public.posts FOR DELETE USING (get_my_role() IN ('directora','asistente','admin') OR auth.uid()=teacher_id);

-- COMMENTS
CREATE POLICY "comments_select" ON public.comments FOR SELECT USING (EXISTS (SELECT 1 FROM public.posts p WHERE p.id=comments.post_id AND (get_my_role() IN ('directora','asistente','admin','maestra') OR p.classroom_id IS NULL OR is_teacher_of_classroom(p.classroom_id) OR is_parent_of_classroom(p.classroom_id))));
CREATE POLICY "comments_insert" ON public.comments FOR INSERT WITH CHECK (auth.uid()=user_id AND EXISTS (SELECT 1 FROM public.posts p WHERE p.id=comments.post_id AND (get_my_role() IN ('directora','asistente','maestra','admin') OR p.classroom_id IS NULL OR is_parent_of_classroom(p.classroom_id))));
CREATE POLICY "comments_delete" ON public.comments FOR DELETE USING (auth.uid()=user_id OR get_my_role() IN ('directora','asistente','maestra','admin'));

-- LIKES
CREATE POLICY "likes_select" ON public.likes FOR SELECT USING (EXISTS (SELECT 1 FROM public.posts p WHERE p.id=likes.post_id AND (get_my_role() IN ('directora','asistente','admin','maestra') OR p.classroom_id IS NULL OR is_teacher_of_classroom(p.classroom_id) OR is_parent_of_classroom(p.classroom_id))));
CREATE POLICY "likes_insert" ON public.likes FOR INSERT WITH CHECK (auth.uid()=user_id);
CREATE POLICY "likes_delete" ON public.likes FOR DELETE USING (auth.uid()=user_id);

-- CONVERSATIONS
CREATE POLICY "conv_select" ON public.conversations FOR SELECT USING (get_my_role() IN ('directora','asistente','admin') OR user_is_participant(id, auth.uid()));
CREATE POLICY "conv_insert" ON public.conversations FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "conv_update" ON public.conversations FOR UPDATE USING (user_is_participant(id, auth.uid()));

-- CONVERSATION PARTICIPANTS
CREATE POLICY "cp_select" ON public.conversation_participants FOR SELECT USING (get_my_role() IN ('directora','asistente','admin') OR user_id=auth.uid());
CREATE POLICY "cp_insert" ON public.conversation_participants FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);
CREATE POLICY "cp_delete" ON public.conversation_participants FOR DELETE USING (user_id=auth.uid());

-- MESSAGES
CREATE POLICY "msg_select" ON public.messages FOR SELECT USING (get_my_role() IN ('directora','asistente','admin') OR user_is_participant(conversation_id, auth.uid()));
CREATE POLICY "msg_insert" ON public.messages FOR INSERT WITH CHECK (auth.uid()=sender_id AND user_is_participant(conversation_id, auth.uid()));
CREATE POLICY "msg_update" ON public.messages FOR UPDATE USING (get_my_role() IN ('directora','maestra','asistente','admin') OR sender_id=auth.uid());

-- NOTIFICATIONS
CREATE POLICY "notifications_all" ON public.notifications FOR ALL USING (auth.uid()=user_id OR get_my_role() IN ('directora','asistente','admin'));

-- PAYMENTS (sin condición deleted_at en USING para que el staff pueda ver todos)
CREATE POLICY "payments_staff_all" ON public.payments FOR ALL
  USING (COALESCE((SELECT role FROM public.profiles WHERE id=auth.uid() LIMIT 1),'') IN ('directora','asistente','admin'))
  WITH CHECK (COALESCE((SELECT role FROM public.profiles WHERE id=auth.uid() LIMIT 1),'') IN ('directora','asistente','admin'));
CREATE POLICY "payments_parent_select" ON public.payments FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.students WHERE id=payments.student_id AND parent_id=auth.uid() AND deleted_at IS NULL)
  AND deleted_at IS NULL
);
CREATE POLICY "payments_parent_insert" ON public.payments FOR INSERT WITH CHECK (
  EXISTS (SELECT 1 FROM public.students WHERE id=payments.student_id AND parent_id=auth.uid())
);

-- INCIDENTS
CREATE POLICY "incidents_insert" ON public.incidents FOR INSERT WITH CHECK (auth.uid()=teacher_id);
CREATE POLICY "incidents_select" ON public.incidents FOR SELECT USING (auth.uid()=teacher_id OR get_my_role() IN ('directora','asistente','admin') OR is_parent_of_student(student_id));
CREATE POLICY "incidents_update" ON public.incidents FOR UPDATE USING (get_my_role() IN ('directora','asistente','maestra','admin'));

-- DAILY LOGS
CREATE POLICY "daily_logs_staff"   ON public.daily_logs FOR ALL USING (get_my_role() IN ('directora','asistente','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','admin'));
CREATE POLICY "daily_logs_teacher" ON public.daily_logs FOR ALL USING (is_teacher_of_classroom(classroom_id)) WITH CHECK (is_teacher_of_classroom(classroom_id));
CREATE POLICY "daily_logs_parent"  ON public.daily_logs FOR SELECT USING (EXISTS (SELECT 1 FROM public.students WHERE id=daily_logs.student_id AND parent_id=auth.uid()));

-- GALLERY & CHAT AULA
CREATE POLICY "gallery_teacher"      ON public.classroom_gallery FOR ALL USING (is_teacher_of_classroom(classroom_id)) WITH CHECK (is_teacher_of_classroom(classroom_id));
CREATE POLICY "gallery_parent"       ON public.classroom_gallery FOR SELECT USING (is_parent_of_classroom(classroom_id));
CREATE POLICY "classroom_chat_select" ON public.classroom_chat FOR SELECT USING (is_teacher_of_classroom(classroom_id) OR is_parent_of_classroom(classroom_id));
CREATE POLICY "classroom_chat_insert" ON public.classroom_chat FOR INSERT WITH CHECK (auth.uid()=user_id AND (is_teacher_of_classroom(classroom_id) OR is_parent_of_classroom(classroom_id)));

-- GRADES
CREATE POLICY "grades_staff"  ON public.grades FOR ALL USING (get_my_role() IN ('directora','asistente','maestra','admin')) WITH CHECK (get_my_role() IN ('directora','admin') OR (get_my_role() IN ('maestra','asistente') AND (period_id IS NULL OR public.is_period_open(period_id))));
CREATE POLICY "grades_parent" ON public.grades FOR SELECT USING (is_parent_of_student(student_id));

-- PERIODS
CREATE POLICY "periods_staff"  ON public.periods FOR ALL USING (get_my_role() IN ('directora','asistente','maestra','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','maestra','admin'));
CREATE POLICY "periods_parent" ON public.periods FOR SELECT USING (classroom_id IN (SELECT ret_id FROM public.get_my_classroom_ids()));

-- REPORT CARDS
CREATE POLICY "report_cards_staff"  ON public.report_cards FOR ALL USING (get_my_role() IN ('directora','asistente','maestra','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','maestra','admin'));
CREATE POLICY "report_cards_parent" ON public.report_cards FOR SELECT USING (EXISTS (SELECT 1 FROM public.students WHERE id=report_cards.student_id AND parent_id=auth.uid()));

-- INQUIRIES
CREATE POLICY "inquiries_staff"         ON public.inquiries FOR ALL USING (get_my_role() IN ('directora','asistente','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','admin'));
CREATE POLICY "inquiries_parent_select" ON public.inquiries FOR SELECT USING (auth.uid()=parent_id);
CREATE POLICY "inquiries_parent_insert" ON public.inquiries FOR INSERT WITH CHECK (auth.uid()=parent_id);

-- SCHOOL SETTINGS
CREATE POLICY "settings_staff" ON public.school_settings FOR ALL USING (get_my_role() IN ('directora','asistente','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','admin'));
CREATE POLICY "settings_read"  ON public.school_settings FOR SELECT USING (auth.uid() IS NOT NULL);

-- SYSTEM EVENTS
CREATE POLICY "system_events_staff" ON public.system_events FOR ALL USING (get_my_role() IN ('directora','asistente','admin')) WITH CHECK (get_my_role() IN ('directora','asistente','admin'));

-- TERMS ACCEPTANCE
CREATE POLICY "terms_own" ON public.terms_acceptance FOR ALL USING (auth.uid()=user_id);

-- AUDIT LOGS
CREATE POLICY "audit_logs_staff" ON public.audit_logs FOR SELECT USING (get_my_role() IN ('directora','asistente','admin'));
CREATE POLICY "audit_logs_insert" ON public.audit_logs FOR INSERT WITH CHECK (true);

-- LOGIN ATTEMPTS
CREATE POLICY "login_attempts_insert" ON public.login_attempts FOR INSERT WITH CHECK (true);
CREATE POLICY "login_attempts_admin"  ON public.login_attempts FOR SELECT USING (get_my_role()='admin');

-- DOOR PUNCHES
CREATE POLICY "punches_staff_all"   ON public.door_punches FOR ALL USING (get_my_role() IN ('directora','asistente','maestra','admin'));
CREATE POLICY "punches_parent_read" ON public.door_punches FOR SELECT USING (EXISTS (SELECT 1 FROM public.students s WHERE s.id=door_punches.student_id AND s.parent_id=auth.uid()));

-- STAFF PERMITS
CREATE POLICY "staff_view_own_permits"  ON public.staff_permits FOR SELECT USING (auth.uid()=staff_id);
CREATE POLICY "staff_create_permits"    ON public.staff_permits FOR INSERT WITH CHECK (auth.uid()=staff_id);
CREATE POLICY "admin_view_all_permits"  ON public.staff_permits FOR SELECT USING (get_my_role() IN ('directora','asistente','admin'));
CREATE POLICY "admin_manage_permits"    ON public.staff_permits FOR UPDATE USING (get_my_role() IN ('directora','asistente','admin'));

-- ── 9. PERFIL ADMIN INICIAL ───────────────────────────────────
INSERT INTO public.profiles (id, email, name, role, accepted_terms, created_at)
VALUES ('c1e72617-ab8f-44c0-b1eb-cdd92eda62e7','impulsodigital@gmail.com','Administrador','admin',true,now())
ON CONFLICT (id) DO UPDATE SET role='admin', accepted_terms=true;

-- ── 10. STORAGE BUCKETS ───────────────────────────────────────
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('avatars','avatars',true,5242880,ARRAY['image/jpeg','image/jpg','image/png','image/webp','image/gif'])
ON CONFLICT (id) DO UPDATE SET public=true, file_size_limit=5242880;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('karpus-uploads','karpus-uploads',true,5242880,ARRAY['image/jpeg','image/jpg','image/png','image/webp','image/gif','application/pdf'])
ON CONFLICT (id) DO UPDATE SET public=true, file_size_limit=5242880;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('classroom_media','classroom_media',true,52428800,ARRAY['image/jpeg','image/png','image/webp','image/gif','video/mp4','video/webm','video/quicktime','application/pdf'])
ON CONFLICT (id) DO UPDATE SET public=true;

DROP POLICY IF EXISTS "avatars_select"           ON storage.objects;
DROP POLICY IF EXISTS "avatars_insert"           ON storage.objects;
DROP POLICY IF EXISTS "avatars_update"           ON storage.objects;
DROP POLICY IF EXISTS "avatars_delete"           ON storage.objects;
DROP POLICY IF EXISTS "karpus_uploads_select"    ON storage.objects;
DROP POLICY IF EXISTS "karpus_uploads_insert"    ON storage.objects;
DROP POLICY IF EXISTS "karpus_uploads_update"    ON storage.objects;
DROP POLICY IF EXISTS "karpus_uploads_delete"    ON storage.objects;
DROP POLICY IF EXISTS "classroom_media_select"   ON storage.objects;
DROP POLICY IF EXISTS "classroom_media_insert"   ON storage.objects;
DROP POLICY IF EXISTS "classroom_media_update"   ON storage.objects;

CREATE POLICY "avatars_select"        ON storage.objects FOR SELECT USING (bucket_id='avatars');
CREATE POLICY "avatars_insert"        ON storage.objects FOR INSERT WITH CHECK (bucket_id='avatars' AND auth.role()='authenticated');
CREATE POLICY "avatars_update"        ON storage.objects FOR UPDATE USING (bucket_id='avatars' AND auth.role()='authenticated');
CREATE POLICY "avatars_delete"        ON storage.objects FOR DELETE USING (bucket_id='avatars' AND auth.role()='authenticated');
CREATE POLICY "karpus_uploads_select" ON storage.objects FOR SELECT USING (bucket_id='karpus-uploads');
CREATE POLICY "karpus_uploads_insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id='karpus-uploads' AND auth.role()='authenticated');
CREATE POLICY "karpus_uploads_update" ON storage.objects FOR UPDATE USING (bucket_id='karpus-uploads' AND auth.role()='authenticated');
CREATE POLICY "karpus_uploads_delete" ON storage.objects FOR DELETE USING (bucket_id='karpus-uploads' AND auth.role()='authenticated');
CREATE POLICY "classroom_media_select" ON storage.objects FOR SELECT USING (bucket_id='classroom_media');
CREATE POLICY "classroom_media_insert" ON storage.objects FOR INSERT WITH CHECK (bucket_id='classroom_media' AND auth.role()='authenticated');
CREATE POLICY "classroom_media_update" ON storage.objects FOR UPDATE USING (bucket_id='classroom_media' AND auth.role()='authenticated');

-- ── 11. GRANTS FINALES ────────────────────────────────────────
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO authenticated;

-- ── VERIFICACIÓN ──────────────────────────────────────────────
SELECT 'profiles'    AS tabla, count(*) FROM public.profiles
UNION ALL SELECT 'students',   count(*) FROM public.students
UNION ALL SELECT 'classrooms', count(*) FROM public.classrooms
UNION ALL SELECT 'payments',   count(*) FROM public.payments
UNION ALL SELECT 'door_punches', count(*) FROM public.door_punches;
