-- ============================================================
-- 🧾 BOLETA EN VIVO (Live Report Card)
-- Add-on del Constructor de Evaluaciones.
--  - Config por evaluación: áreas y módulos por período (default 5×5)
--  - Vínculo de tareas con módulos de la boleta (tasks.eval_module_id)
--  - Notas de la boleta por estudiante+período (fortalezas/debilidades/comentario)
--  - Auditoría de calificaciones (eval_score_history + trigger)
-- Autor: Karpus Kids · Fecha: 2026-08-05
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. CONFIG POR EVALUACIÓN (default 5 áreas × 5 módulos)
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.eval_evaluations
  ADD COLUMN IF NOT EXISTS default_areas   integer DEFAULT 5 CHECK (default_areas   >= 1 AND default_areas   <= 10);
ALTER TABLE public.eval_evaluations
  ADD COLUMN IF NOT EXISTS default_modules integer DEFAULT 5 CHECK (default_modules >= 1 AND default_modules <= 10);

-- ─────────────────────────────────────────────────────────────
-- 2. VÍNCULO DE TAREAS CON LA BOLETA
--    Cuando la maestra califica una tarea vinculada, la nota se
--    escribe automáticamente en eval_scores del módulo elegido.
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS eval_module_id bigint REFERENCES public.eval_modules(id) ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────
-- 3. NOTAS DE LA BOLETA (por estudiante y período)
--    fortalezas / debilidades / comentario del docente.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.eval_boleta_notes (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE,
  student_id   bigint REFERENCES public.students(id)   ON DELETE CASCADE,
  period_id    bigint REFERENCES public.eval_periods(id) ON DELETE CASCADE,
  strengths    text,
  weaknesses   text,
  comment      text,
  created_by   uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at   timestamptz DEFAULT now() NOT NULL,
  updated_at   timestamptz DEFAULT now() NOT NULL,
  UNIQUE (student_id, period_id)
);

-- ─────────────────────────────────────────────────────────────
-- 4. AUDITORÍA DE CALIFICACIONES
--    Registra quién creó/editó/eliminó cada calificación.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.eval_score_history (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  score_id    bigint REFERENCES public.eval_scores(id) ON DELETE SET NULL,
  module_id   bigint REFERENCES public.eval_modules(id)   ON DELETE SET NULL,
  activity_id bigint REFERENCES public.eval_activities(id) ON DELETE SET NULL,
  student_id  bigint REFERENCES public.students(id) ON DELETE CASCADE,
  action      text NOT NULL CHECK (action IN ('created','updated','deleted')),
  old_value   jsonb,
  new_value   jsonb,
  changed_by  uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at  timestamptz DEFAULT now() NOT NULL
);

-- ─────────────────────────────────────────────────────────────
-- 5. RLS
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.eval_boleta_notes   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eval_score_history   ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE
  _tables text[] := ARRAY['eval_boleta_notes','eval_score_history'];
  _t text;
BEGIN
  FOREACH _t IN ARRAY _tables LOOP
    EXECUTE format('DROP POLICY IF EXISTS "staff_all_%s" ON public.%I', _t, _t);
    EXECUTE format(
      'CREATE POLICY "staff_all_%s" ON public.%I FOR ALL
         TO authenticated
         USING (COALESCE(get_my_role(),'''') IN (''directora'',''admin'',''asistente'',''encargada'',''maestra''))
         WITH CHECK (COALESCE(get_my_role(),'''') IN (''directora'',''admin'',''asistente'',''encargada'',''maestra''))', _t, _t);
  END LOOP;

  EXECUTE 'DROP POLICY IF EXISTS "parent_read_eval_boleta_notes" ON public.eval_boleta_notes';
  EXECUTE 'CREATE POLICY "parent_read_eval_boleta_notes" ON public.eval_boleta_notes FOR SELECT
             TO authenticated
             USING (is_parent_of_student(student_id))';

  EXECUTE 'DROP POLICY IF EXISTS "parent_read_eval_score_history" ON public.eval_score_history';
  EXECUTE 'CREATE POLICY "parent_read_eval_score_history" ON public.eval_score_history FOR SELECT
             TO authenticated
             USING (is_parent_of_student(student_id))';
END $$;

-- ─────────────────────────────────────────────────────────────
-- 6. ÍNDICES
-- ─────────────────────────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_eval_notes_student ON public.eval_boleta_notes (student_id, period_id);
CREATE INDEX IF NOT EXISTS idx_eval_hist_score    ON public.eval_score_history (score_id);
CREATE INDEX IF NOT EXISTS idx_eval_hist_student  ON public.eval_score_history (student_id);
CREATE INDEX IF NOT EXISTS idx_eval_hist_created  ON public.eval_score_history (created_at);

-- ─────────────────────────────────────────────────────────────
-- 7. TRIGGER DE AUDITORÍA (eval_scores → eval_score_history)
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.eval_score_audit()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_user uuid := auth.uid();
BEGIN
  IF TG_OP = 'INSERT' THEN
    INSERT INTO public.eval_score_history
      (score_id, module_id, activity_id, student_id, action, old_value, new_value, changed_by)
    VALUES
      (NEW.id, NEW.module_id, NEW.activity_id, NEW.student_id, 'created', NULL,
       jsonb_build_object('value', NEW.value, 'stars', NEW.stars, 'level', NEW.level,
                          'yesno', NEW.yesno, 'checklist', NEW.checklist,
                          'rubric', NEW.rubric, 'observation', NEW.observation),
       v_user);
    RETURN NEW;
  ELSIF TG_OP = 'UPDATE' THEN
    IF OLD IS DISTINCT FROM NEW THEN
      INSERT INTO public.eval_score_history
        (score_id, module_id, activity_id, student_id, action, old_value, new_value, changed_by)
      VALUES
        (NEW.id, NEW.module_id, NEW.activity_id, NEW.student_id, 'updated',
         jsonb_build_object('value', OLD.value, 'stars', OLD.stars, 'level', OLD.level,
                            'yesno', OLD.yesno, 'checklist', OLD.checklist,
                            'rubric', OLD.rubric, 'observation', OLD.observation),
         jsonb_build_object('value', NEW.value, 'stars', NEW.stars, 'level', NEW.level,
                            'yesno', NEW.yesno, 'checklist', NEW.checklist,
                            'rubric', NEW.rubric, 'observation', NEW.observation),
         v_user);
    END IF;
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    INSERT INTO public.eval_score_history
      (score_id, module_id, activity_id, student_id, action, old_value, new_value, changed_by)
    VALUES
      (OLD.id, OLD.module_id, OLD.activity_id, OLD.student_id, 'deleted',
       jsonb_build_object('value', OLD.value, 'stars', OLD.stars, 'level', OLD.level,
                          'yesno', OLD.yesno, 'checklist', OLD.checklist,
                          'rubric', OLD.rubric, 'observation', OLD.observation),
       NULL, v_user);
    RETURN OLD;
  END IF;
  RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS trg_eval_scores_audit ON public.eval_scores;
CREATE TRIGGER trg_eval_scores_audit
  AFTER INSERT OR UPDATE OR DELETE ON public.eval_scores
  FOR EACH ROW EXECUTE FUNCTION public.eval_score_audit();

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
