-- ============================================================
-- 20260804_classroom_daily_schedule.sql
-- Cronología del aula persistida por día (maestra → padres).
--
-- La maestra guarda aquí el plan del día (eventos con hora,
-- duración, emoji, color) y el panel de padres lo muestra en
-- tiempo real marcando el evento activo / siguiente.
--
-- Idempotente: seguro de re-ejecutar.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.classroom_daily_schedule (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id  bigint NOT NULL REFERENCES public.classrooms(id) ON DELETE CASCADE,
  schedule_date date NOT NULL DEFAULT CURRENT_DATE,
  events        jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at    timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (classroom_id, schedule_date)
);

CREATE INDEX IF NOT EXISTS idx_classroom_daily_schedule_classroom_date
  ON public.classroom_daily_schedule(classroom_id, schedule_date);

ALTER TABLE public.classroom_daily_schedule ENABLE ROW LEVEL SECURITY;

-- Staff puede crear/editar/borrar el plan del día de su aula.
DROP POLICY IF EXISTS "classroom_daily_schedule_staff_all" ON public.classroom_daily_schedule;
CREATE POLICY "classroom_daily_schedule_staff_all" ON public.classroom_daily_schedule FOR ALL
  USING (COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada'));

-- Cualquier usuario autenticado (padres) puede leer el plan.
DROP POLICY IF EXISTS "classroom_daily_schedule_read" ON public.classroom_daily_schedule;
CREATE POLICY "classroom_daily_schedule_read" ON public.classroom_daily_schedule FOR SELECT
  USING (auth.role() = 'authenticated');

-- Realtime para que el panel de padres vea los cambios al instante.
DO $$
BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.classroom_daily_schedule;
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
