-- ============================================================
-- MIGRATION: Master Rule Enforcement + Competency Evaluation
-- Date: 2026-07-23
-- Purpose: Enforce the 50 master rules at the database level
--          AND build a professional competency-based evaluation
--          system for early childhood education.
-- ============================================================

-- ============================================================
-- PART 1: COMPETENCY EVALUATION SCHEMA
-- ============================================================

-- Academic areas (Matemática, Lenguaje, Arte, Psicomotricidad, Desarrollo Infantil)
CREATE TABLE IF NOT EXISTS public.academic_areas (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name          text NOT NULL,
  description   text,
  icon          text DEFAULT 'book',
  sort_order    int DEFAULT 1,
  is_active     boolean DEFAULT true,
  created_at    timestamp with time zone DEFAULT now() NOT NULL
);

-- Default areas for early childhood
INSERT INTO public.academic_areas (name, description, icon, sort_order) VALUES
  ('Lenguaje', 'Reconocimiento de letras, vocabulario, expresión oral y comprensión', 'languages', 1),
  ('Matemática', 'Números, formas, colores, relaciones espaciales y lógica', 'calculator', 2),
  ('Desarrollo Infantil', 'Social, emocional, cognitivo y autonomía', 'heart', 3),
  ('Psicomotricidad', 'Control motriz, coordinación, equilibrio y lateralidad', 'activity', 4),
  ('Arte y Creatividad', 'Expresión artística, música, pintura y manualidades', 'palette', 5),
  ('Ciencias Naturales', 'Exploración del entorno, naturaleza y cuidado del cuerpo', 'leaf', 6),
  ('Formación Valores', 'Valores, normas, convivencia y respeto', 'star', 7)
ON CONFLICT DO NOTHING;

-- Competencies per area
CREATE TABLE IF NOT EXISTS public.competencies (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  area_id         bigint NOT NULL REFERENCES public.academic_areas(id) ON DELETE CASCADE,
  name            text NOT NULL,
  description     text,
  level_order     int DEFAULT 1,
  is_active       boolean DEFAULT true,
  created_at      timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_competencies_area ON public.competencies(area_id);

-- Pre-populate competencies
INSERT INTO public.competencies (area_id, name, description, level_order) VALUES
  -- Lenguaje
  ((SELECT id FROM public.academic_areas WHERE name='Lenguaje' LIMIT 1), 'Reconoce vocales y consonantes', 'Identifica y diferencia letras del abecedario', 1),
  ((SELECT id FROM public.academic_areas WHERE name='Lenguaje' LIMIT 1), 'Pronuncia palabras correctamente', 'Articula sonidos con claridad', 2),
  ((SELECT id FROM public.academic_areas WHERE name='Lenguaje' LIMIT 1), 'Escucha y sigue instrucciones', 'Comprende y ejecuta indicaciones de 2-3 pasos', 3),
  ((SELECT id FROM public.academic_areas WHERE name='Lenguaje' LIMIT 1), 'Cuenta historias con coherencia', 'Narra eventos con inicio, desarrollo y cierre', 4),
  ((SELECT id FROM public.academic_areas WHERE name='Lenguaje' LIMIT 1), 'Identifica su nombre escrito', 'Reconoce su nombre en papel', 5),
  -- Matemática
  ((SELECT id FROM public.academic_areas WHERE name='Matemática' LIMIT 1), 'Cuenta del 1 al 20', 'Conteo progresivo y regresivo', 1),
  ((SELECT id FROM public.academic_areas WHERE name='Matemática' LIMIT 1), 'Reconoce figuras geométricas', 'Identifica círculo, cuadrado, triángulo, rectángulo', 2),
  ((SELECT id FROM public.academic_areas WHERE name='Matemática' LIMIT 1), 'Identifica y nombra colores', 'Reconoce colores primarios y secundarios', 3),
  ((SELECT id FROM public.academic_areas WHERE name='Matemática' LIMIT 1), 'Clasifica por tamaño y forma', 'Ordena de grande a pequeño, agrupa por características', 4),
  ((SELECT id FROM public.academic_areas WHERE name='Matemática' LIMIT 1), 'Relaciones de cantidad', 'Comprende conceptos de más, menos, igual', 5),
  -- Desarrollo Infantil
  ((SELECT id FROM public.academic_areas WHERE name='Desarrollo Infantil' LIMIT 1), 'Social: Comparte y coopera', 'Interactúa positivamente con sus compañeros', 1),
  ((SELECT id FROM public.academic_areas WHERE name='Desarrollo Infantil' LIMIT 1), 'Emocional: Identifica sus emociones', 'Nombra cómo se siente y reconoce emociones en otros', 2),
  ((SELECT id FROM public.academic_areas WHERE name='Desarrollo Infantil' LIMIT 1), 'Cognitivo: Resuelve problemas simples', 'Busca soluciones ante situaciones cotidianas', 3),
  ((SELECT id FROM public.academic_areas WHERE name='Desarrollo Infantil' LIMIT 1), 'Autonomía: Realiza tareas solo', 'Se viste, come y se asea con independencia', 4),
  -- Psicomotricidad
  ((SELECT id FROM public.academic_areas WHERE name='Psicomotricidad' LIMIT 1), 'Control motriz grueso', 'Corre, salta, camina en línea recta', 1),
  ((SELECT id FROM public.academic_areas WHERE name='Psicomotricidad' LIMIT 1), 'Coordinación mano-ojo', 'Traza, corta, pega con precisión', 2),
  ((SELECT id FROM public.academic_areas WHERE name='Psicomotricidad' LIMIT 1), 'Equilibrio y lateralidad', 'Se mantiene en un pie, distingue derecha e izquierda', 3),
  -- Arte y Creatividad
  ((SELECT id FROM public.academic_areas WHERE name='Arte y Creatividad' LIMIT 1), 'Expresión artística libre', 'Dibuja, pinta y crea con imaginación', 1),
  ((SELECT id FROM public.academic_areas WHERE name='Arte y Creatividad' LIMIT 1), 'Expresión musical', 'Canta canciones, sigue ritmos, toca instrumentos', 2),
  ((SELECT id FROM public.academic_areas WHERE name='Arte y Creatividad' LIMIT 1), 'Manualidades y construcción', 'Arma figuras con plastilina, papel y otros materiales', 3)
ON CONFLICT DO NOTHING;

-- Competency scores (evaluations per student per competency per period)
CREATE TABLE IF NOT EXISTS public.competency_scores (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id      bigint NOT NULL REFERENCES public.students(id) ON DELETE CASCADE,
  competency_id   bigint NOT NULL REFERENCES public.competencies(id) ON DELETE CASCADE,
  period_id       bigint NOT NULL REFERENCES public.periods(id) ON DELETE CASCADE,
  school_year_id  bigint NOT NULL REFERENCES public.school_years(id) ON DELETE CASCADE,
  classroom_id    bigint REFERENCES public.classrooms(id),
  -- Star rating: 1-5 (★☆☆☆☆ to ★★★★★)
  stars           integer CHECK (stars >= 1 AND stars <= 5),
  -- Level label
  level           text CHECK (level IN ('excelente','bueno','proceso','apoyo')),
  -- Optional numeric score for compatibility
  numeric_score   numeric(5,2) CHECK (numeric_score >= 0 AND numeric_score <= 100),
  -- Teacher observations per competency
  observation     text,
  -- Who evaluated
  evaluated_by    uuid REFERENCES public.profiles(id),
  evaluated_at    timestamp with time zone DEFAULT now(),
  created_at      timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(student_id, competency_id, period_id)
);

CREATE INDEX IF NOT EXISTS idx_comp_scores_student ON public.competency_scores(student_id);
CREATE INDEX IF NOT EXISTS idx_comp_scores_period ON public.competency_scores(period_id);
CREATE INDEX IF NOT EXISTS idx_comp_scores_year ON public.competency_scores(school_year_id);
CREATE INDEX IF NOT EXISTS idx_comp_scores_classroom ON public.competency_scores(classroom_id);

-- Link tasks to competencies and areas
DO $$ BEGIN
  ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS area_id bigint REFERENCES public.academic_areas(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS competency_id bigint REFERENCES public.competencies(id);
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS max_score numeric(5,2) DEFAULT 100;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS weight numeric(5,2) DEFAULT 1;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.tasks ADD COLUMN IF NOT EXISTS task_type text DEFAULT 'tarea' CHECK (task_type IN ('tarea','evaluacion','proyecto','observacion'));
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- Enhance report_cards with competency data
DO $$ BEGIN
  ALTER TABLE public.report_cards ADD COLUMN IF NOT EXISTS competency_summary jsonb DEFAULT '{}'::jsonb;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.report_cards ADD COLUMN IF NOT EXISTS areas_summary jsonb DEFAULT '{}'::jsonb;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN
  ALTER TABLE public.report_cards ADD COLUMN IF NOT EXISTS teacher_observations text;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================
-- PART 2: MASTER RULE ENFORCEMENT FUNCTIONS
-- ============================================================

-- RULE 1: Only one active school year at a time
CREATE OR REPLACE FUNCTION public.enforce_single_active_year()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.is_current = true THEN
    UPDATE public.school_years SET is_current = false WHERE id != NEW.id AND is_current = true;
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_single_active_year ON public.school_years;
CREATE TRIGGER trg_single_active_year
  BEFORE INSERT OR UPDATE OF is_current ON public.school_years
  FOR EACH ROW EXECUTE FUNCTION public.enforce_single_active_year();

-- RULES 3,12: Block attendance/tasks writes when period is closed
CREATE OR REPLACE FUNCTION public.enforce_period_not_closed()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_period record; v_year record; v_user_role text;
BEGIN
  v_user_role := (SELECT role FROM public.profiles WHERE id = auth.uid());

  -- Director/admin can always write (emergency override)
  IF v_user_role IN ('directora', 'admin') THEN RETURN NEW; END IF;

  -- Check if period exists and is closed
  IF TG_TABLE_NAME = 'attendance' AND NEW.period_id IS NOT NULL THEN
    SELECT * INTO v_period FROM public.periods WHERE id = NEW.period_id;
    IF FOUND AND (v_period.status = 'closed' OR COALESCE(v_period.is_blocked, false) = true) THEN
      RAISE EXCEPTION 'REGRA #12: No se puede registrar asistencia en un período cerrado.';
    END IF;
  END IF;

  IF TG_TABLE_NAME IN ('tasks', 'task_evidences') THEN
    IF NEW.period_id IS NOT NULL THEN
      SELECT * INTO v_period FROM public.periods WHERE id = NEW.period_id;
      IF FOUND AND (v_period.status = 'closed' OR COALESCE(v_period.is_blocked, false) = true) THEN
        RAISE EXCEPTION 'REGRA #12: No se puede crear/modificar tareas en un período cerrado.';
      END IF;
    END IF;
  END IF;

  IF TG_TABLE_NAME IN ('grades', 'competency_scores') THEN
    IF NEW.period_id IS NOT NULL THEN
      SELECT * INTO v_period FROM public.periods WHERE id = NEW.period_id;
      IF FOUND AND (v_period.status = 'closed' OR COALESCE(v_period.is_blocked, false) = true) THEN
        RAISE EXCEPTION 'REGRA #13: No se pueden modificar calificaciones de un período cerrado.';
      END IF;
    END IF;
  END IF;

  IF TG_TABLE_NAME = 'posts' THEN
    IF NEW.period_id IS NOT NULL THEN
      SELECT * INTO v_period FROM public.periods WHERE id = NEW.period_id;
      IF FOUND AND (v_period.status = 'closed' OR COALESCE(v_period.is_blocked, false) = true) THEN
        RAISE EXCEPTION 'REGRA #20: No se puede publicar en un período cerrado.';
      END IF;
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

-- Apply enforcement triggers
DROP TRIGGER IF EXISTS trg_enforce_period_attendance ON public.attendance;
CREATE TRIGGER trg_enforce_period_attendance
  BEFORE INSERT OR UPDATE ON public.attendance
  FOR EACH ROW EXECUTE FUNCTION public.enforce_period_not_closed();

DROP TRIGGER IF EXISTS trg_enforce_period_tasks ON public.tasks;
CREATE TRIGGER trg_enforce_period_tasks
  BEFORE INSERT OR UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.enforce_period_not_closed();

DROP TRIGGER IF EXISTS trg_enforce_period_grades ON public.grades;
CREATE TRIGGER trg_enforce_period_grades
  BEFORE INSERT OR UPDATE ON public.grades
  FOR EACH ROW EXECUTE FUNCTION public.enforce_period_not_closed();

DROP TRIGGER IF EXISTS trg_enforce_period_posts ON public.posts;
CREATE TRIGGER trg_enforce_period_posts
  BEFORE INSERT OR UPDATE ON public.posts
  FOR EACH ROW EXECUTE FUNCTION public.enforce_period_not_closed();

DROP TRIGGER IF EXISTS trg_enforce_period_comp_scores ON public.competency_scores;
CREATE TRIGGER trg_enforce_period_comp_scores
  BEFORE INSERT OR UPDATE ON public.competency_scores
  FOR EACH ROW EXECUTE FUNCTION public.enforce_period_not_closed();

DROP TRIGGER IF EXISTS trg_enforce_period_task_evidences ON public.task_evidences;
CREATE TRIGGER trg_enforce_period_task_evidences
  BEFORE INSERT OR UPDATE ON public.task_evidences
  FOR EACH ROW EXECUTE FUNCTION public.enforce_period_not_closed();

-- RULE 3: Block attendance if school year is closed
CREATE OR REPLACE FUNCTION public.enforce_year_not_closed()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_year record; v_user_role text;
BEGIN
  v_user_role := (SELECT role FROM public.profiles WHERE id = auth.uid());
  IF v_user_role IN ('directora', 'admin') THEN RETURN NEW; END IF;

  IF NEW.school_year_id IS NOT NULL THEN
    SELECT * INTO v_year FROM public.school_years WHERE id = NEW.school_year_id;
    IF FOUND AND v_year.status = 'closed' THEN
      RAISE EXCEPTION 'REGRA #3: No se puede registrar datos en un Año Escolar cerrado.';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_year_payments ON public.payments;
CREATE TRIGGER trg_enforce_year_payments
  BEFORE INSERT OR UPDATE ON public.payments
  FOR EACH ROW EXECUTE FUNCTION public.enforce_year_not_closed();

DROP TRIGGER IF EXISTS trg_enforce_year_tasks ON public.tasks;
CREATE TRIGGER trg_enforce_year_tasks
  BEFORE INSERT OR UPDATE ON public.tasks
  FOR EACH ROW EXECUTE FUNCTION public.enforce_year_not_closed();

DROP TRIGGER IF EXISTS trg_enforce_year_posts ON public.posts;
CREATE TRIGGER trg_enforce_year_posts
  BEFORE INSERT OR UPDATE ON public.posts
  FOR EACH ROW EXECUTE FUNCTION public.enforce_year_not_closed();

DROP TRIGGER IF EXISTS trg_enforce_year_grades ON public.grades;
CREATE TRIGGER trg_enforce_year_grades
  BEFORE INSERT OR UPDATE ON public.grades
  FOR EACH ROW EXECUTE FUNCTION public.enforce_year_not_closed();

DROP TRIGGER IF EXISTS trg_enforce_year_attendance ON public.attendance;
CREATE TRIGGER trg_enforce_year_attendance
  BEFORE INSERT OR UPDATE ON public.attendance
  FOR EACH ROW EXECUTE FUNCTION public.enforce_year_not_closed();

DROP TRIGGER IF EXISTS trg_enforce_year_incidents ON public.incidents;
CREATE TRIGGER trg_enforce_year_incidents
  BEFORE INSERT OR UPDATE ON public.incidents
  FOR EACH ROW EXECUTE FUNCTION public.enforce_year_not_closed();

-- RULE 8: Cannot enroll in closed year
CREATE OR REPLACE FUNCTION public.enforce_enrollment_year_open()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_year record;
BEGIN
  SELECT * INTO v_year FROM public.school_years WHERE id = NEW.school_year_id;
  IF FOUND AND v_year.status = 'closed' THEN
    RAISE EXCEPTION 'REGRA #8: No se pueden matricular estudiantes en un Año Escolar cerrado.';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_enrollment_year ON public.student_enrollments;
CREATE TRIGGER trg_enforce_enrollment_year
  BEFORE INSERT OR UPDATE ON public.student_enrollments
  FOR EACH ROW EXECUTE FUNCTION public.enforce_enrollment_year_open();

-- RULE 26: No duplicate active enrollment for same student/year
CREATE OR REPLACE FUNCTION public.enforce_single_enrollment_per_year()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_count int;
BEGIN
  SELECT count(*) INTO v_count
  FROM public.student_enrollments
  WHERE student_id = NEW.student_id
  AND school_year_id = NEW.school_year_id
  AND status IN ('activo','inscrito','admitido','reinscrito')
  AND id IS DISTINCT FROM NEW.id;
  IF v_count > 0 THEN
    RAISE EXCEPTION 'REGRA #26: Ya existe una matrícula activa para este estudiante en este año escolar.';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_single_enrollment ON public.student_enrollments;
CREATE TRIGGER trg_enforce_single_enrollment
  BEFORE INSERT OR UPDATE ON public.student_enrollments
  FOR EACH ROW EXECUTE FUNCTION public.enforce_single_enrollment_per_year();

-- RULE 9: Every enrollment must belong to a school year
CREATE OR REPLACE FUNCTION public.enforce_enrollment_has_year()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.school_year_id IS NULL THEN
    RAISE EXCEPTION 'REGRA #9: Toda matrícula debe pertenecer a un Año Escolar.';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_enrollment_year_not_null ON public.student_enrollments;
CREATE TRIGGER trg_enforce_enrollment_year_not_null
  BEFORE INSERT ON public.student_enrollments
  FOR EACH ROW EXECUTE FUNCTION public.enforce_enrollment_has_year();

-- RULE 21: Cannot enroll if inscription is closed
CREATE OR REPLACE FUNCTION public.enforce_inscription_open()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_year record; v_user_role text;
BEGIN
  v_user_role := (SELECT role FROM public.profiles WHERE id = auth.uid());
  IF v_user_role IN ('directora', 'admin') THEN RETURN NEW; END IF;

  SELECT * INTO v_year FROM public.school_years WHERE id = NEW.school_year_id;
  IF FOUND AND COALESCE(v_year.enrollment_open, false) = false THEN
    RAISE EXCEPTION 'REGRA #21: Las inscripciones están cerradas para este año escolar.';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_enforce_inscription_open ON public.student_enrollments;
CREATE TRIGGER trg_enforce_inscription_open
  BEFORE INSERT ON public.student_enrollments
  FOR EACH ROW EXECUTE FUNCTION public.enforce_inscription_open();

-- ============================================================
-- PART 3: COMPETENCY EVALUATION RPCs
-- ============================================================

-- Get competency scores for a student in a period
CREATE OR REPLACE FUNCTION public.get_student_competencies(
  p_student_id bigint,
  p_period_id bigint
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_result jsonb;
BEGIN
  SELECT jsonb_agg(jsonb_build_object(
    'area_name', aa.name, 'area_icon', aa.icon,
    'competency_name', c.name, 'competency_description', c.description,
    'stars', cs.stars, 'level', cs.level, 'numeric_score', cs.numeric_score,
    'observation', cs.observation, 'competency_id', cs.competency_id
  ) ORDER BY aa.sort_order, c.level_order) INTO v_result
  FROM public.competency_scores cs
  JOIN public.competencies c ON c.id = cs.competency_id
  JOIN public.academic_areas aa ON aa.id = c.area_id
  WHERE cs.student_id = p_student_id AND cs.period_id = p_period_id;
  RETURN COALESCE(v_result, '[]'::jsonb);
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_student_competencies(bigint, bigint) TO authenticated;

-- Get area averages for a classroom in a period
CREATE OR REPLACE FUNCTION public.get_classroom_area_averages(
  p_classroom_id bigint,
  p_period_id bigint
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_result jsonb;
BEGIN
  SELECT jsonb_agg(jsonb_build_object(
    'area_id', aa.id, 'area_name', aa.name, 'area_icon', aa.icon,
    'avg_stars', ROUND(AVG(cs.stars), 1),
    'avg_score', ROUND(AVG(cs.numeric_score), 1),
    'student_count', count(DISTINCT cs.student_id),
    'competency_count', count(DISTINCT cs.competency_id)
  ) ORDER BY aa.sort_order) INTO v_result
  FROM public.competency_scores cs
  JOIN public.competencies c ON c.id = cs.competency_id
  JOIN public.academic_areas aa ON aa.id = c.area_id
  WHERE cs.classroom_id = p_classroom_id AND cs.period_id = p_period_id;
  RETURN COALESCE(v_result, '[]'::jsonb);
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_classroom_area_averages(bigint, bigint) TO authenticated;

-- Get institutional averages across all areas for a period
CREATE OR REPLACE FUNCTION public.get_institutional_averages(p_period_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_result jsonb;
BEGIN
  SELECT jsonb_build_object(
    'areas', jsonb_agg(jsonb_build_object(
      'area_name', aa.name, 'area_icon', aa.icon,
      'avg_stars', ROUND(AVG(cs.stars), 1),
      'avg_score', ROUND(AVG(cs.numeric_score), 1),
      'evaluated', count(DISTINCT cs.student_id)
    ) ORDER BY aa.sort_order),
    'total_evaluated', (SELECT count(DISTINCT student_id) FROM public.competency_scores WHERE period_id = p_period_id),
    'total_students', (SELECT count(*) FROM public.students s
      JOIN public.student_enrollments se ON se.student_id = s.id
      WHERE se.status IN ('activo','inscrito','reinscrito')),
    'global_avg_stars', (SELECT ROUND(AVG(stars), 1) FROM public.competency_scores WHERE period_id = p_period_id),
    'global_avg_score', (SELECT ROUND(AVG(numeric_score), 1) FROM public.competency_scores WHERE period_id = p_period_id)
  ) INTO v_result
  FROM public.competency_scores cs
  JOIN public.competencies c ON c.id = cs.competency_id
  JOIN public.academic_areas aa ON aa.id = c.area_id
  WHERE cs.period_id = p_period_id;

  RETURN COALESCE(v_result, '{}'::jsonb);
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_institutional_averages(bigint) TO authenticated;

-- Get complete academic record for a student (all years/periods)
CREATE OR REPLACE FUNCTION public.get_student_academic_record(p_student_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_result jsonb;
BEGIN
  SELECT jsonb_agg(jsonb_build_object(
    'period_id', rc.period_id, 'period_name', p.name,
    'school_year_id', rc.school_year_id, 'school_year_name', sy.name,
    'classroom_name', c.name,
    'task_avg', rc.task_avg, 'formal_avg', rc.formal_avg,
    'final_score', rc.final_score, 'level', rc.level,
    'teacher_comment', rc.teacher_comment,
    'competency_summary', rc.competency_summary,
    'areas_summary', rc.areas_summary,
    'teacher_observations', rc.teacher_observations,
    'generated_at', rc.generated_at
  ) ORDER BY sy.start_date DESC, p.start_date DESC) INTO v_result
  FROM public.report_cards rc
  JOIN public.periods p ON p.id = rc.period_id
  JOIN public.school_years sy ON sy.id = rc.school_year_id
  LEFT JOIN public.classrooms c ON c.id = rc.classroom_id
  WHERE rc.student_id = p_student_id;

  RETURN jsonb_build_object('student_id', p_student_id, 'records', COALESCE(v_result, '[]'::jsonb));
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_student_academic_record(bigint) TO authenticated;

-- Update close_period to include competency report card generation
CREATE OR REPLACE FUNCTION public.close_period(p_period_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_period periods%ROWTYPE; v_user_id uuid; v_role text; v_student record;
  v_avg numeric(5,2); v_task_avg numeric(5,2); v_formal_avg numeric(5,2); v_level text;
  v_cards_updated int := 0; v_comp_summary jsonb; v_areas_summary jsonb;
BEGIN
  v_user_id := auth.uid();
  SELECT role INTO v_role FROM public.profiles WHERE id = v_user_id;
  IF v_role NOT IN ('directora','admin') THEN RETURN jsonb_build_object('error', 'Solo la directora puede cerrar periodos'); END IF;
  SELECT * INTO v_period FROM public.periods WHERE id = p_period_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('error', 'Periodo no encontrado'); END IF;
  IF v_period.status = 'closed' THEN RETURN jsonb_build_object('error', 'El periodo ya esta cerrado'); END IF;

  FOR v_student IN
    SELECT s.id AS student_id, s.name AS student_name, se.classroom_id
    FROM public.student_enrollments se
    JOIN public.students s ON s.id = se.student_id
    WHERE se.school_year_id = v_period.school_year_id
    AND se.status IN ('activo','inscrito','reinscrito')
  LOOP
    -- Task average
    SELECT ROUND(AVG(CASE WHEN te.numeric_score IS NOT NULL AND te.numeric_score >= 0 THEN te.numeric_score WHEN te.stars IS NOT NULL AND te.stars > 0 THEN te.stars * 20 WHEN te.grade_letter = 'A' THEN 95 WHEN te.grade_letter = 'B' THEN 85 WHEN te.grade_letter = 'C' THEN 75 WHEN te.grade_letter = 'D' THEN 60 WHEN te.grade_letter = 'E' THEN 40 ELSE NULL END), 2) INTO v_task_avg
    FROM public.task_evidences te JOIN public.tasks t ON t.id = te.task_id
    WHERE te.student_id = v_student.student_id AND te.status = 'graded' AND t.created_at BETWEEN v_period.start_date AND v_period.end_date + INTERVAL '1 day';

    -- Formal grades average
    SELECT ROUND(AVG(CASE WHEN g.numeric_score IS NOT NULL AND g.numeric_score >= 0 THEN g.numeric_score WHEN g.score IS NOT NULL AND g.score > 0 THEN g.score * 20 ELSE NULL END), 2) INTO v_formal_avg
    FROM public.grades g WHERE g.student_id = v_student.student_id AND g.period_id = p_period_id;

    -- Final average
    IF v_task_avg IS NOT NULL AND v_formal_avg IS NOT NULL THEN v_avg := ROUND((v_task_avg * 0.6) + (v_formal_avg * 0.4), 2);
    ELSIF v_task_avg IS NOT NULL THEN v_avg := v_task_avg;
    ELSIF v_formal_avg IS NOT NULL THEN v_avg := v_formal_avg;
    ELSE v_avg := NULL; END IF;

    v_level := CASE WHEN v_avg IS NULL THEN 'Sin calificar' WHEN v_avg >= 95 THEN 'Excelente' WHEN v_avg >= 85 THEN 'Muy Bueno' WHEN v_avg >= 75 THEN 'Bueno' WHEN v_avg >= 60 THEN 'Aceptable' WHEN v_avg >= 50 THEN 'Requiere Mejoras' ELSE 'Bajo Desempeno' END;

    -- Competency summary (star averages per area)
    SELECT COALESCE(jsonb_object_agg(aa.name, jsonb_build_object(
      'avg_stars', area_avg, 'icon', aa.icon
    )), '{}'::jsonb) INTO v_areas_summary
    FROM (
      SELECT cs2.competency_id, c2.area_id, ROUND(AVG(cs2.stars), 1) AS area_avg
      FROM public.competency_scores cs2
      JOIN public.competencies c2 ON c2.id = cs2.competency_id
      WHERE cs2.student_id = v_student.student_id AND cs2.period_id = p_period_id
      GROUP BY c2.area_id
    ) sub
    JOIN public.academic_areas aa ON aa.id = sub.area_id;

    INSERT INTO public.report_cards (student_id, classroom_id, period_id, school_year_id, task_avg, formal_avg, final_score, level, competency_summary, areas_summary, created_at)
    VALUES (v_student.student_id, v_student.classroom_id, p_period_id, v_period.school_year_id, v_task_avg, v_formal_avg, v_avg, v_level,
      (SELECT COALESCE(jsonb_agg(jsonb_build_object('competency', c3.name, 'area', aa2.name, 'stars', cs3.stars, 'level', cs3.level)), '[]'::jsonb)
       FROM public.competency_scores cs3 JOIN public.competencies c3 ON c3.id = cs3.competency_id JOIN public.academic_areas aa2 ON aa2.id = c3.area_id
       WHERE cs3.student_id = v_student.student_id AND cs3.period_id = p_period_id),
      v_areas_summary, now())
    ON CONFLICT (student_id, period_id) DO UPDATE SET
      task_avg = EXCLUDED.task_avg, formal_avg = EXCLUDED.formal_avg,
      final_score = EXCLUDED.final_score, level = EXCLUDED.level,
      competency_summary = EXCLUDED.competency_summary, areas_summary = EXCLUDED.areas_summary,
      school_year_id = EXCLUDED.school_year_id;
    v_cards_updated := v_cards_updated + 1;
  END LOOP;

  -- Close period
  UPDATE public.periods SET status = 'closed', is_active = false, is_blocked = true, closed_at = now(), closed_by = v_user_id WHERE id = p_period_id;
  INSERT INTO public.audit_logs (user_id, action, payload, created_at) VALUES (v_user_id, 'period.closed', jsonb_build_object('period_id', p_period_id, 'cards_generated', v_cards_updated), now());
  INSERT INTO public.school_year_processes (school_year_id, process_type, label, status, executed_at, executed_by)
  VALUES (v_period.school_year_id, 'period_close', 'Período cerrado: ' || v_period.name, 'completed', now(), v_user_id);

  RETURN jsonb_build_object('success', true, 'period_id', p_period_id, 'cards_generated', v_cards_updated);
END;
$$;
GRANT EXECUTE ON FUNCTION public.close_period(bigint) TO authenticated;

-- ============================================================
-- PART 4: INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_tasks_area ON public.tasks(area_id) WHERE area_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_competency ON public.tasks(competency_id) WHERE competency_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_tasks_type ON public.tasks(task_type);
CREATE INDEX IF NOT EXISTS idx_report_cards_areas ON public.report_cards USING gin(areas_summary);
