-- ============================================================
-- 20260806_fix_activate_period.sql
-- Diagnostico y fix de "No se pudo activar el periodo".
--
-- Problema:
--   activate_period terminaba en "EXCEPTION WHEN OTHERS THEN
--   RETURN jsonb_build_object('error','No se pudo activar el periodo')",
--   ocultando la causa real (fechas del periodo fuera del ano escolar,
--   otro periodo activo bloqueado por trigger, columna/relacion faltante
--   por migraciones parciales, etc.). Era imposible diagnosticar.
--
-- Fix:
--   1. Defensa de esquema: crea school_year_processes si la BD se
--      construyo solo con schema.sql y sin 20260723_school_year_engine.
--   2. activate_period ahora devuelve el error REAL (SQLERRM/SQLSTATE)
--      en lugar del mensaje generico, para que el toast de la directora
--      muestre la causa y podamos resolverla.
--
-- Idempotente: seguro de re-ejecutar.
-- ============================================================

-- ============================================================
-- 0. DEFENSA DE ESQUEMA: school_year_processes
--    (no-op si ya existe; replica 20260723_school_year_engine.sql)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.school_year_processes (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_year_id bigint NOT NULL REFERENCES public.school_years(id) ON DELETE CASCADE,
  process_type  text NOT NULL CHECK (process_type IN (
    'config','periods_created','enrollment_open','enrollment_close',
    'reenrollment_open','reenrollment_close','classes_started',
    'period_open','period_close','evaluations_open','evaluations_close',
    'report_cards','promotion','graduation','year_closed','archived',
    'new_year_ready','custom'
  )),
  label         text,
  status        text DEFAULT 'pending' CHECK (status IN ('pending','in_progress','completed','skipped')),
  executed_at   timestamp with time zone,
  executed_by   uuid REFERENCES public.profiles(id),
  metadata      jsonb DEFAULT '{}'::jsonb,
  created_at    timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_processes_school_year ON public.school_year_processes(school_year_id);
CREATE INDEX IF NOT EXISTS idx_processes_type ON public.school_year_processes(process_type);

ALTER TABLE public.school_year_processes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS school_year_processes_select ON public.school_year_processes;
CREATE POLICY school_year_processes_select ON public.school_year_processes
  FOR SELECT USING (true);
GRANT SELECT ON public.school_year_processes TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.school_year_processes TO service_role;

-- ============================================================
-- 1. activate_period CON ERROR REAL
--    Misma logica que 20260801_fix_year_period_sync.sql, pero el
--    manejador de excepciones devuelve la causa real en lugar de
--    un mensaje generico.
-- ============================================================
CREATE OR REPLACE FUNCTION public.activate_period(p_period_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_user_id uuid; v_role text; v_period periods%ROWTYPE;
  v_old_id bigint; v_year_id bigint; v_year school_years%ROWTYPE;
BEGIN
  v_user_id := auth.uid();
  SELECT role INTO v_role FROM public.profiles WHERE id = v_user_id;
  IF v_role NOT IN ('directora','admin') THEN
    RETURN jsonb_build_object('error', 'Solo la directora puede activar periodos');
  END IF;

  SELECT * INTO v_period FROM public.periods WHERE id = p_period_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('error', 'Periodo no encontrado'); END IF;
  IF v_period.status = 'closed' OR COALESCE(v_period.is_blocked, false) = true THEN
    RETURN jsonb_build_object('error', 'No se puede activar un periodo cerrado');
  END IF;

  v_year_id := public.get_active_school_year_id();
  IF v_year_id IS NULL THEN
    RETURN jsonb_build_object('error', 'No hay ano escolar vigente. Activa el ano escolar primero.');
  END IF;

  IF v_period.school_year_id IS NULL THEN
    IF v_period.start_date <= (SELECT end_date FROM public.school_years WHERE id = v_year_id)
       AND v_period.end_date >= (SELECT start_date FROM public.school_years WHERE id = v_year_id) THEN
      UPDATE public.periods SET school_year_id = v_year_id WHERE id = p_period_id;
      v_period.school_year_id := v_year_id;
    ELSE
      RETURN jsonb_build_object('error', 'El periodo no pertenece al ano escolar vigente.');
    END IF;
  END IF;

  IF v_period.school_year_id <> v_year_id THEN
    RETURN jsonb_build_object('error',
      'El periodo pertenece a otro ano escolar. Solo se puede activar un periodo del ano vigente.');
  END IF;

  SELECT * INTO v_year FROM public.school_years WHERE id = v_year_id;
  IF v_year.status = 'closed' THEN
    RETURN jsonb_build_object('error', 'No se puede activar un periodo de un ano escolar cerrado');
  END IF;

  SELECT id INTO v_old_id FROM public.periods WHERE is_active = true LIMIT 1;
  UPDATE public.periods SET is_active = false WHERE is_active = true;
  UPDATE public.periods SET is_active = true, status = 'open', is_blocked = false WHERE id = p_period_id;

  UPDATE public.classrooms SET active_period_id = NULL;
  IF v_period.classroom_id IS NOT NULL THEN
    UPDATE public.classrooms SET active_period_id = p_period_id WHERE id = v_period.classroom_id;
  END IF;

  DELETE FROM public.school_year_processes
  WHERE school_year_id = v_year_id AND process_type = 'period_open';
  INSERT INTO public.school_year_processes (school_year_id, process_type, label, status, executed_at, executed_by)
  VALUES (v_year_id, 'period_open', 'Periodo activado: ' || v_period.name, 'completed', now(), v_user_id);

  INSERT INTO public.audit_logs (user_id, action, payload, created_at)
  VALUES (v_user_id, 'period.activated', jsonb_build_object(
    'period_id', p_period_id, 'period_name', v_period.name,
    'old_period_id', v_old_id, 'school_year_id', v_year_id), now());

  RETURN jsonb_build_object('success', true, 'period_id', p_period_id,
    'period_name', v_period.name, 'old_period_id', v_old_id, 'school_year_id', v_year_id);
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object(
    'error', 'No se pudo activar el periodo: ' || SQLERRM,
    'sqlstate', SQLSTATE,
    'detail', SQLERRM);
END;
$$;
GRANT EXECUTE ON FUNCTION public.activate_period(bigint) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.activate_period(bigint) FROM anon;
