-- ============================================================
-- 🧾 BOLETÍN INTELIGENTE (Smart Report Card)
-- Reemplaza el Constructor de Evaluaciones por un boletín de
-- presentación unificado Directora/Maestra:
--   - eval_evaluations.activity_labels : 5 actividades compartidas
--     (A1..A5) para TODAS las áreas, con nombre y valor máximo.
--   - eval_evaluations.scale_config    : escala configurable 0-100
--     con niveles editables (AD/A/B/C/D por defecto).
--   - eval_areas.weight                : peso de cada área (promedio).
--   - eval_area_notes                  : observación inteligente POR
--     ÁREA y estudiante (además de la general de eval_boleta_notes).
--   - eval_periods.boletin_sent_at     : marca cuándo se envió el
--     boletín en PDF a los padres (flujo "Enviar Boletín").
--   - boletin_ensure_structure()       : auto-genera la estructura
--     5 áreas × 5 módulos (A1..A5) por período, conservando las
--     calificaciones ya existentes.
-- Autor: Karpus Kids · Fecha: 2026-08-06
-- ============================================================

-- ─────────────────────────────────────────────────────────────
-- 1. ACTIVIDADES COMPARTIDAS (columnas A1..A5 del boletín)
--    Las 5 actividades son las mismas para todas las áreas.
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.eval_evaluations
  ADD COLUMN IF NOT EXISTS activity_labels jsonb DEFAULT '[
    {"name":"Actividad 1","max_value":100},
    {"name":"Actividad 2","max_value":100},
    {"name":"Actividad 3","max_value":100},
    {"name":"Actividad 4","max_value":100},
    {"name":"Actividad 5","max_value":100}
  ]'::jsonb;

-- ─────────────────────────────────────────────────────────────
-- 2. ESCALA DE CALIFICACIÓN (configurable por la directora)
--    Niveles por defecto: AD / A / B / C / D sobre 0-100.
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.eval_evaluations
  ADD COLUMN IF NOT EXISTS scale_config jsonb DEFAULT '{
    "min": 0,
    "max": 100,
    "levels": [
      {"label":"AD","min":90,"max":100,"color":"#10B981"},
      {"label":"A","min":80,"max":89,"color":"#22C55E"},
      {"label":"B","min":70,"max":79,"color":"#F59E0B"},
      {"label":"C","min":60,"max":69,"color":"#F97316"},
      {"label":"D","min":0,"max":59,"color":"#EF4444"}
    ]
  }'::jsonb;

-- ─────────────────────────────────────────────────────────────
-- 3. PESO DE CADA ÁREA (para el promedio general ponderado)
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.eval_areas
  ADD COLUMN IF NOT EXISTS weight numeric(6,2) DEFAULT 0;

-- ─────────────────────────────────────────────────────────────
-- 4. MARCA DE ENVÍO DEL BOLETÍN (por período)
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.eval_periods
  ADD COLUMN IF NOT EXISTS boletin_sent_at timestamptz;

-- ─────────────────────────────────────────────────────────────
-- 5. OBSERVACIÓN INTELIGENTE POR ÁREA (por estudiante + período)
--    La observación general del docente vive en eval_boleta_notes.
-- ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.eval_area_notes (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id  bigint REFERENCES public.students(id)   ON DELETE CASCADE,
  period_id   bigint REFERENCES public.eval_periods(id) ON DELETE CASCADE,
  area_id     bigint REFERENCES public.eval_areas(id)   ON DELETE CASCADE,
  observation text,
  created_by  uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at  timestamptz DEFAULT now() NOT NULL,
  updated_at  timestamptz DEFAULT now() NOT NULL,
  UNIQUE (student_id, period_id, area_id)
);

CREATE INDEX IF NOT EXISTS idx_eval_area_notes_student ON public.eval_area_notes (student_id, period_id);
CREATE INDEX IF NOT EXISTS idx_eval_area_notes_area    ON public.eval_area_notes (area_id);

-- ─────────────────────────────────────────────────────────────
-- 6. RLS — eval_area_notes (staff total, padres lectura de su hijo)
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.eval_area_notes ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  EXECUTE 'DROP POLICY IF EXISTS "staff_all_eval_area_notes" ON public.eval_area_notes';
  EXECUTE 'CREATE POLICY "staff_all_eval_area_notes" ON public.eval_area_notes FOR ALL
             TO authenticated
             USING (COALESCE(get_my_role(),'''') IN (''directora'',''admin'',''asistente'',''encargada'',''maestra''))
             WITH CHECK (COALESCE(get_my_role(),'''') IN (''directora'',''admin'',''asistente'',''encargada'',''maestra''))';

  EXECUTE 'DROP POLICY IF EXISTS "parent_read_eval_area_notes" ON public.eval_area_notes';
  EXECUTE 'CREATE POLICY "parent_read_eval_area_notes" ON public.eval_area_notes FOR SELECT
             TO authenticated
             USING (is_parent_of_student(student_id))';
END $$;

-- ─────────────────────────────────────────────────────────────
-- 6b. VÍNCULO DE TAREAS CON ACTIVIDADES DEL BOLETÍN
--     tasks.eval_module_id   : módulo (ya creado en 20260805).
--     tasks.eval_activity_id : actividad concreta del módulo a la
--       que alimenta la nota al calificar la tarea (doble escritura
--       task_evidences → eval_scores).
-- ─────────────────────────────────────────────────────────────
ALTER TABLE public.tasks
  ADD COLUMN IF NOT EXISTS eval_activity_id bigint REFERENCES public.eval_activities(id) ON DELETE SET NULL;

-- ─────────────────────────────────────────────────────────────
-- 7. RPC: boletin_ensure_structure(p_evaluation_id)
--    Auto-genera: períodos (desde el año escolar) → áreas por
--    defecto (si no hay) → 5 módulos A1..A5 por área×período →
--    1 actividad por módulo. Conserva las calificaciones previas.
-- ─────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.boletin_ensure_structure(p_evaluation_id bigint)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_role text := COALESCE(get_my_role(), '');
  v_eval  record;
  v_year  record;
  v_labels jsonb;
  v_scale  jsonb;
  v_areas_count int;
  v_periods_count int;
  v_default_areas int;
  v_default_modules int;
  v_area record;
  v_period record;
  v_global_period record;
  v_modules_count int;
  v_mod record;
  v_acts_count int;
  v_i int;
  v_label jsonb;
  v_created_periods int := 0;
  v_created_areas int := 0;
  v_created_modules int := 0;
  v_created_activities int := 0;
  v_period_type text;
  v_new_period_id bigint;
BEGIN
  IF v_role NOT IN ('directora','admin','asistente','encargada','maestra') THEN
    RETURN jsonb_build_object('error','No autorizado');
  END IF;

  SELECT * INTO v_eval FROM public.eval_evaluations WHERE id = p_evaluation_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error','Evaluación/Boletín no encontrado');
  END IF;

  SELECT * INTO v_year FROM public.school_years WHERE id = v_eval.school_year_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object('error','Año escolar no encontrado');
  END IF;

  v_labels := COALESCE(v_eval.activity_labels, '[]'::jsonb);
  IF jsonb_array_length(v_labels) < 1 THEN
    v_labels := '[{"name":"Actividad 1","max_value":100},{"name":"Actividad 2","max_value":100},{"name":"Actividad 3","max_value":100},{"name":"Actividad 4","max_value":100},{"name":"Actividad 5","max_value":100}]'::jsonb;
  END IF;
  v_default_areas   := COALESCE(v_eval.default_areas, 5);
  v_default_modules := COALESCE(v_eval.default_modules, 5);

  -- ── ÁREAS: crear solo si no hay ninguna (respeta personalización)
  SELECT count(*) INTO v_areas_count FROM public.eval_areas
    WHERE evaluation_id = p_evaluation_id AND deleted_at IS NULL;
  IF v_areas_count = 0 THEN
    INSERT INTO public.eval_areas (evaluation_id, name, description, color, icon, sort_order, weight, created_by) VALUES
      (p_evaluation_id, 'Lenguaje',         'Comunicación, lenguaje y lectoescritura.', '#0EA5E9', 'message-circle', 1, 20, auth.uid()),
      (p_evaluation_id, 'Matemática',       'Pensamiento lógico, conteo y nociones.',  '#6366F1', 'calculator',     2, 20, auth.uid()),
      (p_evaluation_id, 'Motricidad',       'Desarrollo motor fino y grueso.',         '#F97316', 'activity',       3, 20, auth.uid()),
      (p_evaluation_id, 'Socioemocional',   'Emociones, convivencia y autonomía.',     '#F43F5E', 'heart',          4, 20, auth.uid()),
      (p_evaluation_id, 'Ciencias',         'Exploración del entorno y la naturaleza.', '#22C55E', 'leaf',           5, 20, auth.uid());
    v_created_areas := 5;
  END IF;

  -- ── PERÍODOS: importar del año escolar si el boletín no tiene
  --    y sincronizar (agregar) los períodos nuevos que cree la
  --    directora en public.periods después de la primera vez.
  SELECT count(*) INTO v_periods_count FROM public.eval_periods
    WHERE evaluation_id = p_evaluation_id AND deleted_at IS NULL;
  IF v_periods_count = 0 THEN
    FOR v_global_period IN
      SELECT id, name, start_date, end_date, status, sort_order
      FROM public.periods
      WHERE school_year_id = v_eval.school_year_id
      ORDER BY COALESCE(sort_order, 0), start_date, id
    LOOP
      v_period_type := CASE
        WHEN COALESCE(v_year.period_model,'trimestres') = 'semestres' THEN 'bimestre'
        WHEN COALESCE(v_year.period_model,'trimestres') = 'mensual' THEN 'mes'
        ELSE 'periodo'
      END;
      INSERT INTO public.eval_periods
        (evaluation_id, name, period_type, start_date, end_date, weight, status, sort_order, created_by)
      VALUES
        (p_evaluation_id, v_global_period.name, v_period_type,
         v_global_period.start_date, v_global_period.end_date,
         0,
         CASE WHEN v_global_period.status = 'open' THEN 'open' ELSE 'closed' END,
         COALESCE(v_global_period.sort_order, 0), auth.uid())
      RETURNING id INTO v_new_period_id;
      v_created_periods := v_created_periods + 1;
    END LOOP;

    -- Fallback: crear períodos por defecto si el año no tiene ninguno
    IF v_created_periods = 0 THEN
      INSERT INTO public.eval_periods (evaluation_id, name, period_type, status, sort_order, created_by) VALUES
        (p_evaluation_id, 'Primer Período', 'periodo', 'open',  1, auth.uid()),
        (p_evaluation_id, 'Segundo Período','periodo', 'open',  2, auth.uid()),
        (p_evaluation_id, 'Tercer Período', 'periodo', 'open',  3, auth.uid());
      v_created_periods := 3;
    END IF;
  ELSE
    FOR v_global_period IN
      SELECT name, start_date, end_date, status, sort_order
      FROM public.periods
      WHERE school_year_id = v_eval.school_year_id
        AND NOT EXISTS (
          SELECT 1 FROM public.eval_periods ep
          WHERE ep.evaluation_id = p_evaluation_id
            AND ep.deleted_at IS NULL
            AND ep.name = public.periods.name
        )
      ORDER BY COALESCE(sort_order, 0), start_date, id
    LOOP
      v_period_type := CASE
        WHEN COALESCE(v_year.period_model,'trimestres') = 'semestres' THEN 'bimestre'
        WHEN COALESCE(v_year.period_model,'trimestres') = 'mensual' THEN 'mes'
        ELSE 'periodo'
      END;
      INSERT INTO public.eval_periods
        (evaluation_id, name, period_type, start_date, end_date, weight, status, sort_order, created_by)
      VALUES
        (p_evaluation_id, v_global_period.name, v_period_type,
         v_global_period.start_date, v_global_period.end_date,
         0,
         CASE WHEN v_global_period.status = 'open' THEN 'open' ELSE 'closed' END,
         COALESCE(v_global_period.sort_order, 0), auth.uid())
      RETURNING id INTO v_new_period_id;
      v_created_periods := v_created_periods + 1;
    END LOOP;
  END IF;

  -- ── MÓDULOS + ACTIVIDADES: por cada área × período, garantizar A1..A5
  FOR v_area IN
    SELECT id FROM public.eval_areas
    WHERE evaluation_id = p_evaluation_id AND deleted_at IS NULL
    ORDER BY sort_order, id
  LOOP
    FOR v_period IN
      SELECT id FROM public.eval_periods
      WHERE evaluation_id = p_evaluation_id AND deleted_at IS NULL
      ORDER BY sort_order, id
    LOOP
      SELECT count(*) INTO v_modules_count FROM public.eval_modules
        WHERE period_id = v_period.id AND area_id = v_area.id AND deleted_at IS NULL;

      FOR v_i IN (v_modules_count + 1)..v_default_modules LOOP
        v_label := v_labels -> (v_i - 1);
        INSERT INTO public.eval_modules
          (period_id, area_id, name, eval_type, config, weight, sort_order, created_by)
        VALUES
          (v_period.id, v_area.id,
           COALESCE(v_label ->> 'name', 'Actividad ' || v_i),
           'numeric',
           jsonb_build_object('min', 0, 'max', 100, 'decimals', 0, 'allowDecimal', false),
           0, v_i, auth.uid())
        RETURNING id INTO v_mod.id;
        v_created_modules := v_created_modules + 1;

        INSERT INTO public.eval_activities
          (module_id, name, max_value, activity_type, activity_date, sort_order, created_by)
        VALUES
          (v_mod.id,
           COALESCE(v_label ->> 'name', 'Actividad ' || v_i),
           COALESCE((v_label ->> 'max_value')::numeric, 100),
           'actividad', NULL, 1, auth.uid());
        v_created_activities := v_created_activities + 1;
      END LOOP;

      -- Garantizar al menos 1 actividad por módulo existente
      FOR v_mod IN
        SELECT id FROM public.eval_modules
        WHERE period_id = v_period.id AND area_id = v_area.id AND deleted_at IS NULL
        ORDER BY sort_order, id
      LOOP
        SELECT count(*) INTO v_acts_count FROM public.eval_activities
          WHERE module_id = v_mod.id AND deleted_at IS NULL;
        IF v_acts_count = 0 THEN
          INSERT INTO public.eval_activities
            (module_id, name, max_value, activity_type, sort_order, created_by)
          SELECT v_mod.id, COALESCE(name, 'Actividad'), COALESCE(max_value, 100), 'actividad', 1, auth.uid()
          FROM jsonb_to_record(v_labels -> 0) AS t(name text, max_value numeric);
          v_created_activities := v_created_activities + 1;
        END IF;
      END LOOP;
    END LOOP;
  END LOOP;

  -- ── Backfill: asegurar config por defecto en evaluaciones antiguas
  IF v_eval.activity_labels IS NULL THEN
    UPDATE public.eval_evaluations
    SET activity_labels = '[
      {"name":"Actividad 1","max_value":100},
      {"name":"Actividad 2","max_value":100},
      {"name":"Actividad 3","max_value":100},
      {"name":"Actividad 4","max_value":100},
      {"name":"Actividad 5","max_value":100}
    ]'::jsonb WHERE id = p_evaluation_id;
  END IF;
  IF v_eval.scale_config IS NULL THEN
    UPDATE public.eval_evaluations
    SET scale_config = '{
      "min":0,"max":100,
      "levels":[
        {"label":"AD","min":90,"max":100,"color":"#10B981"},
        {"label":"A","min":80,"max":89,"color":"#22C55E"},
        {"label":"B","min":70,"max":79,"color":"#F59E0B"},
        {"label":"C","min":60,"max":69,"color":"#F97316"},
        {"label":"D","min":0,"max":59,"color":"#EF4444"}
      ]
    }'::jsonb WHERE id = p_evaluation_id;
  END IF;

  RETURN jsonb_build_object(
    'success', true,
    'evaluation_id', p_evaluation_id,
    'periods_created', v_created_periods,
    'areas_created', v_created_areas,
    'modules_created', v_created_modules,
    'activities_created', v_created_activities
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.boletin_ensure_structure(bigint) TO authenticated;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;
