-- ============================================================
-- 20260912_chat_social_upgrade.sql
-- Chat avanzado estilo Messenger (CHAT.MD)
--
-- Contenido:
--   1. messages: message_type, reply_to_id, edited_at, deleted_at
--   2. message_attachments (multimedia)
--   3. message_reactions (reacciones por emoji)
--   4. conversation_participants: last_read_at
--   5. Trigger: conversations.updated_at se actualiza al enviar mensaje
--   6. mark_messages_read: setea read_at + last_read_at
--   7. get_unread_counts: retorna array JSON (compatibilidad con JS)
--   8. Índices de rendimiento
--   9. RLS: tablas nuevas + messages update/delete
--
-- Idempotente: seguro de re-ejecutar.
-- Ejecutar en Supabase SQL Editor con rol postgres/supabase_admin.
-- ============================================================

-- ============================================================
-- 1. MESSAGES: MESSAGE_TYPE, REPLY_TO, EDITED_AT, DELETED_AT
-- ------------------------------------------------------------
DO $$ BEGIN
  ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS message_type text NOT NULL DEFAULT 'text'
    CHECK (message_type IN ('text','image','file','system'));
EXCEPTION WHEN OTHERS THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS reply_to_id bigint
    REFERENCES public.messages(id) ON DELETE SET NULL;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS edited_at timestamp with time zone;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

DO $$ BEGIN
  ALTER TABLE public.messages ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

COMMENT ON COLUMN public.messages.message_type  IS 'text | image | file | system';
COMMENT ON COLUMN public.messages.reply_to_id   IS 'NULL = mensaje normal; no NULL = respuesta a otro mensaje de la misma conversación';
COMMENT ON COLUMN public.messages.edited_at     IS 'NULL = sin editar; con valor = fecha de última edición';
COMMENT ON COLUMN public.messages.deleted_at    IS 'NULL = activo; con valor = borrado lógico (el contenido se reemplaza por Este mensaje fue eliminado)';

-- ============================================================
-- 2. MESSAGE ATTACHMENTS (multimedia)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.message_attachments (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id  bigint NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
  url         text NOT NULL,
  file_name   text,
  file_type   text,            -- 'image', 'video', 'audio', 'document', etc.
  file_size   bigint,          -- bytes
  created_at  timestamp with time zone DEFAULT now() NOT NULL
);

COMMENT ON TABLE  public.message_attachments IS 'Archivos multimedia asociados a un mensaje';
COMMENT ON COLUMN public.message_attachments.url IS 'URL pública del archivo (Supabase Storage o externa)';

-- ============================================================
-- 3. MESSAGE REACTIONS (reacciones estilo Messenger/WhatsApp)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.message_reactions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
  user_id    uuid NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  emoji      text NOT NULL DEFAULT '👍',
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(message_id, user_id)   -- un usuario = un emoji por mensaje
);

COMMENT ON TABLE  public.message_reactions IS 'Reacciones (emoji) por mensaje. Un usuario = un solo emoji por mensaje.';
COMMENT ON COLUMN public.message_reactions.emoji IS 'Emojis válidos: 👍 ❤️ 😂 😮 😢 😡 👏 🔥';

-- ============================================================
-- 4. CONVERSATION_PARTICIPANTS: LAST_READ_AT
-- ------------------------------------------------------------
DO $$ BEGIN
  ALTER TABLE public.conversation_participants ADD COLUMN IF NOT EXISTS last_read_at timestamp with time zone;
EXCEPTION WHEN OTHERS THEN NULL; END $$;

COMMENT ON COLUMN public.conversation_participants.last_read_at IS 'Timestamp del último mensaje leído por este usuario en esta conversación';

-- ============================================================
-- 5. TRIGGER: CONVERSATIONS.UPDATED_AT se actualiza al enviar mensaje
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.update_conversation_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.conversations SET updated_at = now() WHERE id = NEW.conversation_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_messages_updated_at ON public.messages;
CREATE TRIGGER trg_messages_updated_at
  AFTER INSERT ON public.messages
  FOR EACH ROW
  EXECUTE FUNCTION public.update_conversation_updated_at();

-- ============================================================
-- 6. MARK_MESSAGES_READ: ahora también setea read_at y last_read_at
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.mark_messages_read(p_conversation_id bigint)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF auth.uid() IS NULL OR p_conversation_id IS NULL THEN RETURN; END IF;

  -- Marcar mensajes recibidos como leídos (setear read_at)
  UPDATE public.messages
  SET is_read = true,
      read_at = COALESCE(read_at, now())
  WHERE conversation_id = p_conversation_id
    AND sender_id <> auth.uid()
    AND (is_read IS NULL OR is_read = false);

  -- Actualizar last_read_at del participante
  UPDATE public.conversation_participants
  SET last_read_at = now()
  WHERE conversation_id = p_conversation_id
    AND user_id = auth.uid();
END;
$$;
GRANT EXECUTE ON FUNCTION public.mark_messages_read(bigint) TO authenticated;

-- ============================================================
-- 7. GET_UNREAD_COUNTS: retorna ARRAY (no jsonb) para compatibilidad con JS
--    El JS original hace .forEach(r => { counts[r.user_id] = r.unread })
--    así que necesitamos un array de objetos, no un jsonb.
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_unread_counts()
RETURNS SETOF json LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE v_user_id uuid := auth.uid();
BEGIN
  IF v_user_id IS NULL THEN RETURN; END IF;
  RETURN QUERY
  SELECT json_build_object('user_id', m.sender_id, 'unread', count(*)::int)
  FROM public.messages m
  JOIN public.conversation_participants cp ON cp.conversation_id = m.conversation_id AND cp.user_id = v_user_id
  WHERE m.sender_id <> v_user_id AND (m.is_read IS NULL OR m.is_read = false)
  GROUP BY m.sender_id;
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_unread_counts() TO authenticated;

-- ============================================================
-- 8. ÍNDICES DE RENDIMIENTO
-- ------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_messages_reply       ON public.messages(reply_to_id) WHERE reply_to_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_messages_active      ON public.messages(conversation_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_messages_type        ON public.messages(message_type);
CREATE INDEX IF NOT EXISTS idx_attachments_msg      ON public.message_attachments(message_id);
CREATE INDEX IF NOT EXISTS idx_reactions_msg        ON public.message_reactions(message_id);
CREATE INDEX IF NOT EXISTS idx_reactions_user       ON public.message_reactions(user_id);
CREATE INDEX IF NOT EXISTS idx_conv_participants_lr ON public.conversation_participants(conversation_id, last_read_at);

-- ============================================================
-- 9. RLS — TABLAS NUEVAS + POLÍTICAS ACTUALIZADAS
-- ------------------------------------------------------------
ALTER TABLE public.message_attachments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.message_reactions    ENABLE ROW LEVEL SECURITY;

-- message_attachments: solo participantes de la conversación
DROP POLICY IF EXISTS "attachments_participant" ON public.message_attachments;
CREATE POLICY "attachments_participant" ON public.message_attachments FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.messages m
      WHERE m.id = message_attachments.message_id
        AND public.user_is_participant(m.conversation_id, auth.uid())
    )
  );

-- message_reactions: solo participantes de la conversación
DROP POLICY IF EXISTS "reactions_participant" ON public.message_reactions;
CREATE POLICY "reactions_participant" ON public.message_reactions FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM public.messages m
      WHERE m.id = message_reactions.message_id
        AND public.user_is_participant(m.conversation_id, auth.uid())
    )
  )
  WITH CHECK (
    auth.uid() = user_id AND
    EXISTS (
      SELECT 1 FROM public.messages m
      WHERE m.id = message_reactions.message_id
        AND public.user_is_participant(m.conversation_id, auth.uid())
    )
  );

-- Messages: lecturas para participantes; escrituras propias; directora administra
DROP POLICY IF EXISTS "messages_participant" ON public.messages;
DROP POLICY IF EXISTS "messages_delete" ON public.messages;

CREATE POLICY "messages_select" ON public.messages FOR SELECT
  USING (public.user_is_participant(conversation_id, auth.uid()));

CREATE POLICY "messages_insert" ON public.messages FOR INSERT
  WITH CHECK (
    public.user_is_participant(conversation_id, auth.uid()) AND
    sender_id = auth.uid()
  );

-- Edición / borrado lógico (deleted_at): solo remitente, o directora/admin
CREATE POLICY "messages_update" ON public.messages FOR UPDATE
  USING (
    public.user_is_participant(conversation_id, auth.uid()) AND
    (auth.uid() = sender_id OR COALESCE(public.get_my_role(), '') IN ('directora','admin'))
  )
  WITH CHECK (
    public.user_is_participant(conversation_id, auth.uid()) AND
    (auth.uid() = sender_id OR COALESCE(public.get_my_role(), '') IN ('directora','admin'))
  );

-- Borrado físico (DELETE opcional): solo remitente, o directora/admin
CREATE POLICY "messages_delete" ON public.messages FOR DELETE
  USING (
    public.user_is_participant(conversation_id, auth.uid()) AND
    (auth.uid() = sender_id OR COALESCE(public.get_my_role(), '') IN ('directora','admin'))
  );
