-- ============================================================
-- 20260807_sync_periodo_ano_escolar.sql
-- Sincroniza Periodo Escolar <-> Año Escolar
-- ("Sin periodo activo" en Calificaciones aunque el periodo
--  aparece como "Activo" en Períodos del Año Escolar).
--
-- Causas raíz que corrige:
--   1. Ningún año escolar tenía is_current = true (o estaba
--      soft-deleted), por lo que get_active_period devolvía
--      no_school_year / no_period aunque existiera un periodo
--      con is_active = true.
--   2. Periodos activos con school_year_id NULL o apuntando a
--      otro año (migraciones parciales o inserción directa).
--   3. Varios periodos con is_active = true a la vez.
--   4. classrooms.active_period_id desincronizado.
--   5. get_active_period era ESTRICTO: si el periodo activo no
--      pertenecía al año is_current, no se devolvía nada.
--
-- Solución:
--   A. Recrea (de forma idempotente) todas las columnas y la
--      función auxiliar get_active_school_year_id.
--   B. Sincroniza los DATOS: un solo año is_current, backfill
--      de school_year_id, un solo periodo activo y
--      classrooms.active_period_id alineado.
--   C. get_active_period / get_current_period ahora son
--      RESILIENTES: prefieren el periodo activo del año vigente,
--      pero SIEMPRE caen al periodo activo que ve la directora
--      (is_active = true) y luego al primer periodo abierto.
--   D. activate_period autoasigna el año, mantiene un solo
--      periodo activo y sincroniza las aulas, devolviendo el
--      error REAL si algo falla (en lugar de un mensaje genérico).
--
-- Idempotente: seguro de re-ejecutar.
-- ============================================================

-- ============================================================
-- 0. COLUMNAS DEFENSIVAS (no-op si ya existen)
-- ============================================================
ALTER TABLE public.school_years ADD COLUMN IF NOT EXISTS is_current boolean DEFAULT false;
ALTER TABLE public.school_years ADD COLUMN IF NOT EXISTS deleted_at timestamp with time zone;
ALTER TABLE public.school_years ADD COLUMN IF NOT EXISTS status text DEFAULT 'active' CHECK (status IN ('active','closed','upcoming'));
ALTER TABLE public.school_years ADD COLUMN IF NOT EXISTS period_model text DEFAULT 'trimestres';
ALTER TABLE public.school_years ADD COLUMN IF NOT EXISTS num_periods int DEFAULT 3;
ALTER TABLE public.school_years ADD COLUMN IF NOT EXISTS closed_at timestamp with time zone;
ALTER TABLE public.school_years ADD COLUMN IF NOT EXISTS closed_by uuid REFERENCES public.profiles(id);

ALTER TABLE public.periods ADD COLUMN IF NOT EXISTS school_year_id bigint REFERENCES public.school_years(id) ON DELETE SET NULL;
ALTER TABLE public.periods ADD COLUMN IF NOT EXISTS status text DEFAULT 'open' CHECK (status IN ('open','closed'));
ALTER TABLE public.periods ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT false;
ALTER TABLE public.periods ADD COLUMN IF NOT EXISTS start_date date;
ALTER TABLE public.periods ADD COLUMN IF NOT EXISTS end_date date;
ALTER TABLE public.periods ADD COLUMN IF NOT EXISTS classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE;
ALTER TABLE public.periods ADD COLUMN IF NOT EXISTS sort_order int DEFAULT 1;
ALTER TABLE public.periods ADD COLUMN IF NOT EXISTS is_blocked boolean DEFAULT false;
ALTER TABLE public.periods ADD COLUMN IF NOT EXISTS closed_at timestamp with time zone;
ALTER TABLE public.periods ADD COLUMN IF NOT EXISTS closed_by uuid REFERENCES public.profiles(id);

ALTER TABLE public.classrooms ADD COLUMN IF NOT EXISTS active_period_id bigint REFERENCES public.periods(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_periods_active_year ON public.periods(school_year_id, is_active)
  WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_school_years_is_current ON public.school_years(is_current)
  WHERE is_current = true;

-- ============================================================
-- 1. DEFENSA DE ESQUEMA: school_year_processes
--    (no-op si ya existe; replicado de 20260723_school_year_engine)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.school_year_processes (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  school_year_id bigint NOT NULL REFERENCES public.school_years(id) ON DELETE CASCADE,
  process_type  text NOT NULL CHECK (process_type IN (
    'config','periods_created','enrollment_open','enrollment_close',
    'reenrollment_open','reenrollment_close','classes_started',
    'period_open','period_close','evaluations_open','evaluations_close',
    'report_cards','promotion','graduation','year_closed','archived',
    'new_year_ready','custom'
  )),
  label         text,
  status        text DEFAULT 'pending' CHECK (status IN ('pending','in_progress','completed','skipped')),
  executed_at   timestamp with time zone,
  executed_by   uuid REFERENCES public.profiles(id),
  metadata      jsonb DEFAULT '{}'::jsonb,
  created_at    timestamp with time zone DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_processes_school_year ON public.school_year_processes(school_year_id);
CREATE INDEX IF NOT EXISTS idx_processes_type ON public.school_year_processes(process_type);

ALTER TABLE public.school_year_processes ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS school_year_processes_select ON public.school_year_processes;
CREATE POLICY school_year_processes_select ON public.school_year_processes
  FOR SELECT USING (true);
GRANT SELECT ON public.school_year_processes TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.school_year_processes TO service_role;

-- ============================================================
-- 2. HELPER: año escolar vigente (única fuente de verdad)
-- ============================================================
CREATE OR REPLACE FUNCTION public.get_active_school_year_id()
RETURNS bigint LANGUAGE sql SECURITY DEFINER STABLE SET search_path = public AS $$
  SELECT id FROM public.school_years
  WHERE is_current = true AND deleted_at IS NULL
  LIMIT 1;
$$;
GRANT EXECUTE ON FUNCTION public.get_active_school_year_id() TO authenticated;

-- ============================================================
-- 3. SINCRONIZACIÓN DE DATOS (idempotente)
--    Se desactivan TEMPORALMENTE los triggers de regla de periods
--    (enforce_single_active_period / enforce_period_valid_dates)
--    para poder reparar estados corruptos (fechas fuera del año,
--    dos periodos activos, etc.) sin que las reglas bloqueen la
--    reparación. Se usa DISABLE/ENABLE TRIGGER USER para NO tocar
--    los triggers del sistema (FK), que requieren superusuario.
--    Si el rol no puede gestionar triggers (no es dueño de la
--    tabla), la sincronización igual corre usando operaciones
--    seguras para las reglas.
-- ============================================================
DO $$
DECLARE
  v_cur_year bigint;
  v_win      bigint;
  v_winner_year bigint;
  v_manage_triggers boolean;
BEGIN
  -- 3-pre) Recuperación: re-activar triggers de periods por si una
  --        ejecución anterior falló a mitad de camino.
  BEGIN
    ALTER TABLE public.periods ENABLE TRIGGER ALL;
  EXCEPTION WHEN OTHERS THEN
    ALTER TABLE public.periods ENABLE TRIGGER USER;
  END;

  SELECT has_table_privilege(current_user, 'public.periods', 'TRIGGER') INTO v_manage_triggers;
  IF v_manage_triggers THEN
    ALTER TABLE public.periods DISABLE TRIGGER USER;
  END IF;

  -- 3a) Determinar el año escolar vigente (is_current), con respaldo
  SELECT id INTO v_cur_year FROM public.school_years
  WHERE is_current = true AND deleted_at IS NULL LIMIT 1;

  IF v_cur_year IS NULL THEN
    SELECT p.school_year_id INTO v_cur_year
    FROM public.periods p
    JOIN public.school_years y ON y.id = p.school_year_id
    WHERE p.is_active = true AND p.school_year_id IS NOT NULL AND y.deleted_at IS NULL
    ORDER BY p.created_at DESC, p.id DESC LIMIT 1;
  END IF;

  IF v_cur_year IS NULL THEN
    SELECT id INTO v_cur_year FROM public.school_years
    WHERE status <> 'closed' AND deleted_at IS NULL
    ORDER BY start_date DESC, id DESC LIMIT 1;
  END IF;

  IF v_cur_year IS NULL THEN
    SELECT id INTO v_cur_year FROM public.school_years
    ORDER BY start_date DESC, id DESC LIMIT 1;
  END IF;

  IF v_cur_year IS NOT NULL THEN
    UPDATE public.school_years SET is_current = (id = v_cur_year);
  END IF;

  -- 3b) Backfill: periodos activos huérfanos sin school_year_id.
  --     Solo se asigna a un año cuyo rango CONTENGA las fechas del
  --     periodo (así la regla de fechas nunca lo rechaza). Si no
  --     hay año que encaje, se deja NULL y get_active_period igual
  --     lo devuelve por su fallback "cualquier periodo activo".
  UPDATE public.periods p
  SET school_year_id = sub.fit
  FROM (
    SELECT p2.id AS pid, (
      SELECT y.id FROM public.school_years y
      WHERE y.deleted_at IS NULL
        AND p2.start_date >= y.start_date AND p2.end_date <= y.end_date
      ORDER BY y.start_date DESC, y.id DESC LIMIT 1
    ) AS fit
    FROM public.periods p2
    WHERE p2.is_active = true AND p2.school_year_id IS NULL
  ) sub
  WHERE p.id = sub.pid AND sub.fit IS NOT NULL;

  -- 3c) Un solo periodo activo: el del año vigente; si no, el más reciente
  IF v_cur_year IS NOT NULL THEN
    SELECT id INTO v_win FROM public.periods
    WHERE is_active = true AND school_year_id = v_cur_year
    ORDER BY created_at DESC, id DESC LIMIT 1;
  END IF;
  IF v_win IS NULL THEN
    SELECT id INTO v_win FROM public.periods
    WHERE is_active = true
    ORDER BY created_at DESC, id DESC LIMIT 1;
  END IF;

  IF v_win IS NOT NULL THEN
    UPDATE public.periods SET is_active = false
    WHERE id IN (SELECT id FROM public.periods WHERE is_active = true AND id <> v_win);
  ELSE
    -- 3d) Ninguno activo: activar el periodo abierto más reciente del año vigente
    IF v_cur_year IS NOT NULL THEN
      SELECT id INTO v_win FROM public.periods
      WHERE status = 'open' AND COALESCE(is_blocked, false) = false AND school_year_id = v_cur_year
      ORDER BY created_at DESC, id DESC LIMIT 1;
    END IF;
    IF v_win IS NULL THEN
      SELECT id INTO v_win FROM public.periods
      WHERE status = 'open' AND COALESCE(is_blocked, false) = false
      ORDER BY created_at DESC, id DESC LIMIT 1;
    END IF;
    IF v_win IS NOT NULL THEN
      UPDATE public.periods SET is_active = true WHERE id = v_win;
    END IF;
  END IF;

  -- 3e) Sincronizar classrooms.active_period_id y asegurar que el
  --     año del periodo ganador sea el is_current
  UPDATE public.classrooms SET active_period_id = NULL
  WHERE id IN (SELECT id FROM public.classrooms WHERE active_period_id IS NOT NULL);

  IF v_win IS NOT NULL THEN
    SELECT school_year_id INTO v_winner_year FROM public.periods WHERE id = v_win;
    IF v_winner_year IS NOT NULL THEN
      UPDATE public.school_years SET is_current = (id = v_winner_year);
    END IF;

    IF EXISTS (SELECT 1 FROM public.periods WHERE id = v_win AND classroom_id IS NOT NULL) THEN
      UPDATE public.classrooms SET active_period_id = v_win
      WHERE id = (SELECT classroom_id FROM public.periods WHERE id = v_win);
    ELSE
      UPDATE public.classrooms SET active_period_id = v_win;
    END IF;
  END IF;

  IF v_manage_triggers THEN
    ALTER TABLE public.periods ENABLE TRIGGER USER;
  END IF;

  RAISE NOTICE 'SYNC periodo/anio: anio vigente=%, periodo activo=%', v_cur_year, v_win;
EXCEPTION WHEN OTHERS THEN
  IF v_manage_triggers THEN
    ALTER TABLE public.periods ENABLE TRIGGER USER;
  END IF;
  RAISE;
END;
$$;

-- ============================================================
-- 4. get_active_period RESILIENTE
--    Prefiere el periodo activo del año vigente y cae SIEMPRE al
--    periodo activo que ve la directora (is_active = true), y
--    después al primer periodo abierto. Nunca lanza error.
-- ============================================================
DROP FUNCTION IF EXISTS public.get_active_period();

CREATE OR REPLACE FUNCTION public.get_active_period(p_classroom_id bigint DEFAULT NULL)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_year_id bigint;
  v_period periods%ROWTYPE;
BEGIN
  v_year_id := public.get_active_school_year_id();

  -- 1) Periodo activo del año vigente (con alcance al aula si se pide)
  IF p_classroom_id IS NOT NULL THEN
    SELECT * INTO v_period FROM public.periods
    WHERE is_active = true
      AND (v_year_id IS NULL OR school_year_id = v_year_id)
      AND (classroom_id = p_classroom_id OR classroom_id IS NULL)
    ORDER BY (classroom_id IS NULL) ASC, created_at DESC, id DESC
    LIMIT 1;
  END IF;
  IF NOT FOUND THEN
    SELECT * INTO v_period FROM public.periods
    WHERE is_active = true
      AND (v_year_id IS NULL OR school_year_id = v_year_id)
    ORDER BY created_at DESC, id DESC LIMIT 1;
  END IF;

  -- 2) Cualquier periodo activo (el "Activo" que ve la directora)
  IF NOT FOUND THEN
    SELECT * INTO v_period FROM public.periods
    WHERE is_active = true
    ORDER BY created_at DESC, id DESC LIMIT 1;
  END IF;

  -- 3) Cualquier periodo abierto (último recurso)
  IF NOT FOUND THEN
    SELECT * INTO v_period FROM public.periods
    WHERE status = 'open' AND COALESCE(is_blocked, false) = false
    ORDER BY created_at DESC, id DESC LIMIT 1;
  END IF;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('found', false, 'status', 'no_period', 'school_year_id', v_year_id);
  END IF;

  RETURN jsonb_build_object(
    'found', true, 'id', v_period.id, 'name', v_period.name,
    'status', v_period.status, 'is_active', v_period.is_active,
    'start_date', v_period.start_date, 'end_date', v_period.end_date,
    'classroom_id', v_period.classroom_id, 'school_year_id', v_period.school_year_id,
    'is_blocked', COALESCE(v_period.is_blocked, false)
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_active_period(bigint) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_active_period(bigint) FROM anon;

-- ============================================================
-- 5. get_current_period RESILIENTE (misma lógica, sin aula)
-- ============================================================
CREATE OR REPLACE FUNCTION public.get_current_period()
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_year_id bigint;
  v_period periods%ROWTYPE;
BEGIN
  v_year_id := public.get_active_school_year_id();

  SELECT * INTO v_period FROM public.periods
  WHERE is_active = true
    AND (v_year_id IS NULL OR school_year_id = v_year_id)
  ORDER BY created_at DESC, id DESC LIMIT 1;

  IF NOT FOUND THEN
    SELECT * INTO v_period FROM public.periods
    WHERE is_active = true
    ORDER BY created_at DESC, id DESC LIMIT 1;
  END IF;

  IF NOT FOUND THEN
    SELECT * INTO v_period FROM public.periods
    WHERE status = 'open' AND COALESCE(is_blocked, false) = false
    ORDER BY created_at DESC, id DESC LIMIT 1;
  END IF;

  IF NOT FOUND THEN
    RETURN jsonb_build_object('found', false, 'status', 'no_period', 'school_year_id', v_year_id);
  END IF;

  RETURN jsonb_build_object(
    'found', true, 'id', v_period.id, 'name', v_period.name,
    'status', v_period.status, 'is_active', v_period.is_active,
    'start_date', v_period.start_date, 'end_date', v_period.end_date,
    'classroom_id', v_period.classroom_id, 'school_year_id', v_period.school_year_id,
    'is_blocked', COALESCE(v_period.is_blocked, false)
  );
END;
$$;
GRANT EXECUTE ON FUNCTION public.get_current_period() TO authenticated;
REVOKE EXECUTE ON FUNCTION public.get_current_period() FROM anon;

-- ============================================================
-- 6. activate_period ROBUSTO
--    Autoasigna el año escolar, valida fechas, mantiene un solo
--    periodo activo, sincroniza aulas y devuelve el error REAL.
-- ============================================================
CREATE OR REPLACE FUNCTION public.activate_period(p_period_id bigint)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_user_id uuid; v_role text; v_period periods%ROWTYPE;
  v_old_id bigint; v_year_id bigint; v_year school_years%ROWTYPE;
  v_fit_year bigint;
BEGIN
  v_user_id := auth.uid();
  IF v_user_id IS NULL THEN
    RETURN jsonb_build_object('error', 'Sesión no válida');
  END IF;
  SELECT role INTO v_role FROM public.profiles WHERE id = v_user_id;
  IF v_role NOT IN ('directora','admin') THEN
    RETURN jsonb_build_object('error', 'Solo la directora puede activar periodos');
  END IF;

  SELECT * INTO v_period FROM public.periods WHERE id = p_period_id;
  IF NOT FOUND THEN RETURN jsonb_build_object('error', 'Periodo no encontrado'); END IF;
  IF v_period.status = 'closed' OR COALESCE(v_period.is_blocked, false) = true THEN
    RETURN jsonb_build_object('error', 'No se puede activar un periodo cerrado');
  END IF;

  v_year_id := public.get_active_school_year_id();
  IF v_year_id IS NULL THEN
    RETURN jsonb_build_object('error', 'No hay año escolar vigente. Activa el año escolar primero.');
  END IF;

  IF v_period.school_year_id IS NULL THEN
    IF v_period.start_date <= (SELECT end_date FROM public.school_years WHERE id = v_year_id)
       AND v_period.end_date >= (SELECT start_date FROM public.school_years WHERE id = v_year_id) THEN
      UPDATE public.periods SET school_year_id = v_year_id WHERE id = p_period_id;
      v_period.school_year_id := v_year_id;
    ELSE
      SELECT id INTO v_fit_year FROM public.school_years
      WHERE deleted_at IS NULL
        AND v_period.start_date >= start_date AND v_period.end_date <= end_date
      ORDER BY start_date DESC, id DESC LIMIT 1;
      IF v_fit_year IS NULL THEN
        RETURN jsonb_build_object('error',
          'El periodo no pertenece a ningún año escolar. Revisa sus fechas.');
      END IF;
      UPDATE public.periods SET school_year_id = v_fit_year WHERE id = p_period_id;
      v_period.school_year_id := v_fit_year;
    END IF;
  END IF;

  IF v_period.school_year_id <> v_year_id THEN
    SELECT * INTO v_year FROM public.school_years WHERE id = v_period.school_year_id;
    IF NOT FOUND OR v_year.deleted_at IS NOT NULL OR v_year.status = 'closed' THEN
      RETURN jsonb_build_object('error',
        'El periodo pertenece a un año escolar cerrado o no vigente.');
    END IF;
    v_year_id := v_period.school_year_id;
  ELSE
    SELECT * INTO v_year FROM public.school_years WHERE id = v_year_id;
  END IF;
  IF v_year.status = 'closed' THEN
    RETURN jsonb_build_object('error', 'No se puede activar un periodo de un año escolar cerrado');
  END IF;

  -- El año del periodo pasa a ser el vigente (única fuente de verdad)
  UPDATE public.school_years SET is_current = (id = v_year_id);

  SELECT id INTO v_old_id FROM public.periods WHERE is_active = true LIMIT 1;
  UPDATE public.periods SET is_active = false WHERE id IN (SELECT id FROM public.periods WHERE is_active = true);
  UPDATE public.periods SET is_active = true, status = 'open', is_blocked = false WHERE id = p_period_id;

  UPDATE public.classrooms SET active_period_id = NULL WHERE id IN (SELECT id FROM public.classrooms WHERE active_period_id IS NOT NULL);
  IF v_period.classroom_id IS NOT NULL THEN
    UPDATE public.classrooms SET active_period_id = p_period_id WHERE id = v_period.classroom_id;
  END IF;

  DELETE FROM public.school_year_processes
  WHERE id IN (SELECT id FROM public.school_year_processes
               WHERE school_year_id = v_year_id AND process_type = 'period_open');
  INSERT INTO public.school_year_processes (school_year_id, process_type, label, status, executed_at, executed_by)
  VALUES (v_year_id, 'period_open', 'Periodo activado: ' || v_period.name, 'completed', now(), v_user_id);

  INSERT INTO public.audit_logs (user_id, action, payload, created_at)
  VALUES (v_user_id, 'period.activated', jsonb_build_object(
    'period_id', p_period_id, 'period_name', v_period.name,
    'old_period_id', v_old_id, 'school_year_id', v_year_id), now());

  RETURN jsonb_build_object('success', true, 'period_id', p_period_id,
    'period_name', v_period.name, 'old_period_id', v_old_id, 'school_year_id', v_year_id);
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object(
    'error', 'No se pudo activar el periodo: ' || SQLERRM,
    'sqlstate', SQLSTATE,
    'detail', SQLERRM);
END;
$$;
GRANT EXECUTE ON FUNCTION public.activate_period(bigint) TO authenticated;
REVOKE EXECUTE ON FUNCTION public.activate_period(bigint) FROM anon;

-- ============================================================
-- 7. VERIFICACIÓN (mensaje en el editor SQL)
-- ============================================================
SELECT
  (SELECT id FROM public.school_years WHERE is_current = true AND deleted_at IS NULL LIMIT 1) AS anio_vigente_id,
  (SELECT name FROM public.school_years WHERE is_current = true AND deleted_at IS NULL LIMIT 1) AS anio_vigente,
  (SELECT count(*) FROM public.periods WHERE is_active = true) AS periodos_activos,
  (SELECT id FROM public.periods WHERE is_active = true ORDER BY created_at DESC, id DESC LIMIT 1) AS periodo_activo_id,
  (SELECT name FROM public.periods WHERE is_active = true ORDER BY created_at DESC, id DESC LIMIT 1) AS periodo_activo;
