-- ============================================================
-- Migración: Schedule Events — Rutina Express v5
-- Agrega tabla de horarios persistentes y tracking de eventos
-- Fecha: 2026-07-22
-- ============================================================

-- Tabla de horarios configurados por la maestra
CREATE TABLE IF NOT EXISTS public.teacher_schedules (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE NOT NULL,
  event_key    text NOT NULL,
  emoji        text DEFAULT '📌',
  label        text NOT NULL,
  color        text DEFAULT '#94A3B8',
  start_time   time NOT NULL,
  duration     integer DEFAULT 30 CHECK (duration > 0 AND duration <= 480),
  event_type   text DEFAULT 'colectivo' CHECK (event_type IN ('individual', 'colectivo', 'automatico')),
  auto         boolean DEFAULT false,
  needs_confirm boolean DEFAULT false,
  visible_parents boolean DEFAULT true,
  visible_director boolean DEFAULT true,
  active_days  integer[] DEFAULT '{1,2,3,4,5,6}',
  is_active    boolean DEFAULT true,
  created_at   timestamp with time zone DEFAULT now() NOT NULL,
  updated_at   timestamp with time zone DEFAULT now() NOT NULL,
  UNIQUE(classroom_id, event_key)
);

-- Tabla de logs de activación de eventos del horario
CREATE TABLE IF NOT EXISTS public.schedule_event_logs (
  id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id bigint REFERENCES public.classrooms(id) ON DELETE CASCADE NOT NULL,
  event_key    text NOT NULL,
  activated_at timestamp with time zone DEFAULT now() NOT NULL,
  activated_by uuid REFERENCES public.profiles(id),
  student_count integer DEFAULT 0,
  metadata     jsonb DEFAULT '{}'::jsonb,
  created_at   timestamp with time zone DEFAULT now() NOT NULL
);

-- Índices para performance
CREATE INDEX IF NOT EXISTS idx_teacher_schedules_classroom ON public.teacher_schedules(classroom_id);
CREATE INDEX IF NOT EXISTS idx_schedule_event_logs_classroom_date ON public.schedule_event_logs(classroom_id, activated_at);
CREATE INDEX IF NOT EXISTS idx_schedule_event_logs_event_key ON public.schedule_event_logs(event_key);

-- RLS Policies
ALTER TABLE public.teacher_schedules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.schedule_event_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "teacher_schedules_staff_all" ON public.teacher_schedules;
CREATE POLICY "teacher_schedules_staff_all" ON public.teacher_schedules FOR ALL
  USING (EXISTS (SELECT 1 FROM public.classrooms c WHERE c.id = teacher_schedules.classroom_id AND c.teacher_id = auth.uid()));

DROP POLICY IF EXISTS "schedule_event_logs_staff_all" ON public.schedule_event_logs;
CREATE POLICY "schedule_event_logs_staff_all" ON public.schedule_event_logs FOR ALL
  USING (EXISTS (SELECT 1 FROM public.classrooms c WHERE c.id = schedule_event_logs.classroom_id AND c.teacher_id = auth.uid()));

DROP POLICY IF EXISTS "schedule_event_logs_parent_select" ON public.schedule_event_logs;
CREATE POLICY "schedule_event_logs_parent_select" ON public.schedule_event_logs FOR SELECT
  USING (EXISTS (
    SELECT 1 FROM public.students s
    WHERE s.classroom_id = schedule_event_logs.classroom_id AND s.parent_id = auth.uid()
  ));
