-- ============================================================
-- 20260801_routine_catalog_v8.sql
-- Arquitectura V8 — Catalogo de Eventos de Rutina
--
-- Objetivo: un unico catalogo de eventos consumido por TODO el
-- sistema (cronologia, panel colectivo, modal individual, panel
-- de padres), en lugar de constantes hardcodeadas en el frontend.
--
-- Modelo:
--   1. routine_categories       -> 14 categorias (Animo, Salud, ...)
--   2. routine_events           -> catalogo maestro de eventos
--   3. classroom_routine_settings -> que eventos usa cada aula + overrides
--   4. classroom_schedule_blocks  -> cronologia por aula (bloques)
--   5. classroom_schedule_block_events -> bloque <-> eventos del catalogo
--
-- El registro diario sigue usando public.daily_logs.infant_data (jsonb),
-- pero cada evento guardara: event_id (catalogo), occurrence_id (uuid
-- compartido por un lote colectivo) y origin ('cronologia'|'colectivo'|
-- 'manual'|'individual'). Se anade legacy_key para migrar los eventos
-- hardcodeados actuales sin romper la vista de padres.
--
-- Idempotente: seguro de re-ejecutar.
-- ============================================================

-- ============================================================
-- 1. CATEGORIAS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.routine_categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  emoji       text NOT NULL DEFAULT '📌',
  color       text NOT NULL DEFAULT '#0B63C7',
  sort_order  integer NOT NULL DEFAULT 0,
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamp with time zone NOT NULL DEFAULT now()
);

INSERT INTO public.routine_categories (name, emoji, color, sort_order) VALUES
  ('Ánimo',       '😊', '#3B82F6', 0),
  ('Salud',       '❤️', '#EF4444', 1),
  ('Alimentación','🍽️', '#FF8A00', 2),
  ('Descanso',    '😴', '#8B5CF6', 3),
  ('Higiene',     '🚽', '#0B63C7', 4),
  ('Actividades', '🧩', '#7C3AED', 5),
  ('Arte',        '🎨', '#EC4899', 6),
  ('Aprendizaje', '📚', '#6366F1', 7),
  ('Social',      '🤝', '#F59E0B', 8),
  ('Juego',       '🎮', '#16A34A', 9),
  ('Exterior',    '🌳', '#28B54D', 10),
  ('Momentos',    '📸', '#06B6D4', 11),
  ('Incidentes',  '⚠️', '#EF4444', 12),
  ('Personalizados','⭐', '#64748B', 13)
ON CONFLICT (name) DO NOTHING;

-- ============================================================
-- 2. CATALOGO DE EVENTOS
-- ============================================================
CREATE TABLE IF NOT EXISTS public.routine_events (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id        bigint NOT NULL REFERENCES public.routine_categories(id) ON DELETE CASCADE,
  name               text NOT NULL,
  emoji              text NOT NULL DEFAULT '📌',
  color              text NOT NULL DEFAULT '#0B63C7',
  kind               text NOT NULL DEFAULT 'toggle'
                     CHECK (kind IN ('toggle','quantity','value','temp','comment','photo')),
  value_options      jsonb,
  legacy_key         text,
  is_collective      boolean NOT NULL DEFAULT false,
  is_repeatable      boolean NOT NULL DEFAULT false,
  is_required        boolean NOT NULL DEFAULT false,
  requires_comment   boolean NOT NULL DEFAULT false,
  requires_photo     boolean NOT NULL DEFAULT false,
  requires_quantity  boolean NOT NULL DEFAULT false,
  requires_temp      boolean NOT NULL DEFAULT false,
  requires_time      boolean NOT NULL DEFAULT false,
  visible_parents    boolean NOT NULL DEFAULT true,
  visible_director   boolean NOT NULL DEFAULT true,
  visible_teachers   boolean NOT NULL DEFAULT true,
  notify_parents     boolean NOT NULL DEFAULT false,
  notify_email       boolean NOT NULL DEFAULT false,
  track_stats        boolean NOT NULL DEFAULT true,
  sort_order         integer NOT NULL DEFAULT 0,
  is_active          boolean NOT NULL DEFAULT true,
  created_by         uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at         timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (name, category_id)
);

CREATE INDEX IF NOT EXISTS idx_routine_events_category ON public.routine_events(category_id);
CREATE INDEX IF NOT EXISTS idx_routine_events_legacy_key ON public.routine_events(legacy_key);
CREATE INDEX IF NOT EXISTS idx_routine_events_active ON public.routine_events(is_active, sort_order);

-- Seed — Ánimo
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, legacy_key, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'toggle', v.legacy_key, v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Feliz',           '😊', 0, 'mood:feliz'),
  ('Muy feliz',       '😄', 1, NULL),
  ('Tranquilo',       '🙂', 2, 'mood:tranquilo'),
  ('Normal',          '😐', 3, 'mood:normal'),
  ('Participativo',   '🙋', 4, NULL),
  ('Activo',          '⚡', 5, NULL),
  ('Muy activo',      '🔥', 6, NULL),
  ('Somnoliento',     '😴', 7, 'mood:somnoliento'),
  ('Triste',          '😢', 8, 'mood:triste'),
  ('Irritable',       '😤', 9, 'mood:irritable'),
  ('Ansioso',         '😰', 10, NULL),
  ('Lloró',           '😭', 11, 'mood:llanto'),
  ('Enfermo',         '🤒', 12, 'mood:enfermo'),
  ('Se calmó',        '🧘', 13, NULL),
  ('Compartió',       '🤝', 14, NULL),
  ('Necesitó consuelo','💛', 15, NULL),
  ('Excelente actitud','⭐', 16, NULL)
) AS v(name, emoji, sort_order, legacy_key)
WHERE c.name = 'Ánimo'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Salud
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, legacy_key, requires_comment, requires_temp, notify_parents, sort_order)
SELECT c.id, v.name, v.emoji, c.color, v.kind, v.legacy_key, v.requires_comment, v.requires_temp, v.notify_parents, v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Temperatura',   '🌡️', 'temp',    'infant:temp',            false, true,  false, 0),
  ('Fiebre',        '🤒', 'temp',    'incident:fever',         false, true,  true,  1),
  ('Medicamento',   '💊', 'comment', 'infant:med',             true,  false, false, 2),
  ('Golpe',         '🤕', 'comment', 'incident:hit',           true,  false, true,  3),
  ('Rasguño',       '🩹', 'comment', NULL,                     true,  false, true,  4),
  ('Tos',           '😷', 'toggle',  'health:cough',           false, false, false, 5),
  ('Congestión',    '🤧', 'toggle',  NULL,                     false, false, false, 6),
  ('Dolor',         '😖', 'toggle',  NULL,                     false, false, false, 7),
  ('Vomitó',        '🤮', 'toggle',  'health:vomit',           false, false, true,  8),
  ('Caída',         '🦵', 'comment', NULL,                     true,  false, true,  9),
  ('Enfermería',    '🏥', 'toggle',  NULL,                     false, false, true,  10),
  ('Llamada a padres','📞', 'toggle', 'incident:parent_call',  false, false, true,  11)
) AS v(name, emoji, kind, legacy_key, requires_comment, requires_temp, notify_parents, sort_order)
WHERE c.name = 'Salud'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Alimentación
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, value_options, legacy_key, requires_quantity, sort_order)
SELECT c.id, v.name, v.emoji, c.color, v.kind, v.value_options, v.legacy_key, v.requires_quantity, v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Desayuno',    '🍞', 'value',    '["Todo","Poco","No quiso","Ayuda"]'::jsonb, 'food:breakfast', false, 0),
  ('Almuerzo',    '🥗', 'value',    '["Todo","Poco","No quiso","Ayuda"]'::jsonb, 'food:lunch',     false, 1),
  ('Merienda',    '🍪', 'value',    '["Todo","Poco","No quiso","Ayuda"]'::jsonb, 'food:snack',     false, 2),
  ('Refrigerio',  '🍎', 'value',    '["Todo","Poco","No quiso","Ayuda"]'::jsonb, 'food:snack',     false, 3),
  ('Agua',        '💧', 'quantity', NULL,                                         'infant:water',   false, 4),
  ('Leche',       '🥛', 'quantity', NULL,                                         'infant:milk',    false, 5),
  ('Biberón',     '🍼', 'quantity', NULL,                                         'infant:milk',    true,  6),
  ('Frutas',      '🍌', 'toggle',   NULL,                                         NULL,             false, 7),
  ('Vegetales',   '🥦', 'toggle',   NULL,                                         NULL,             false, 8),
  ('Todo',        '✅', 'value',    '["Todo"]'::jsonb,                             NULL,             false, 9),
  ('Poco',        '⚠️', 'value',    '["Poco"]'::jsonb,                             NULL,             false, 10),
  ('Nada',        '❌', 'value',    '["Nada"]'::jsonb,                             NULL,             false, 11),
  ('Necesitó ayuda','🆘', 'value',  '["Ayuda"]'::jsonb,                            NULL,             false, 12)
) AS v(name, emoji, kind, value_options, legacy_key, requires_quantity, sort_order)
WHERE c.name = 'Alimentación'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Descanso
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, legacy_key, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'toggle', v.legacy_key, v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Siesta',            '😴', 'infant:sleep',     0),
  ('Durmió',            '💤', NULL,               1),
  ('No durmió',         '☀️', NULL,               2),
  ('Despertó',          '⏰', 'infant:sleep_end', 3),
  ('Descansó bien',     '🌙', NULL,               4),
  ('Se despertó llorando','🌧️', NULL,            5),
  ('Siesta corta',      '⏳', NULL,               6),
  ('Siesta larga',      '🛏️', NULL,              7)
) AS v(name, emoji, legacy_key, sort_order)
WHERE c.name = 'Descanso'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Higiene
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, legacy_key, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'toggle', v.legacy_key, v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Lavado manos', '🧼', 'infant:handwash',       0),
  ('Cepillado',    '🪥', 'infant:toothbrush',     1),
  ('Pipí',         '💧', 'infant:diaper:wet',     2),
  ('Popó',         '💩', 'infant:diaper:soiled',  3),
  ('Cambio pañal', '🧻', 'infant:diaper_change',  4),
  ('Inodoro',      '🚽', 'infant:toilet',         5),
  ('Baño',         '🛁', 'infant:bath',           6),
  ('Lavado cara',  '🫧', NULL,                    7)
) AS v(name, emoji, legacy_key, sort_order)
WHERE c.name = 'Higiene'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Actividades
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, legacy_key, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'toggle', v.legacy_key, v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Actividad educativa','🎨', 'infant:activity',    0),
  ('Pintura',      '🖌️', NULL,                       1),
  ('Dibujo',       '✏️', NULL,                        2),
  ('Colorear',     '🖍️', NULL,                        3),
  ('Manualidades', '✂️', NULL,                        4),
  ('Música',       '🎵', NULL,                        5),
  ('Danza',        '💃', NULL,                        6),
  ('Lectura',      '📖', NULL,                        7),
  ('Rompecabezas', '🧩', NULL,                        8),
  ('Sensorial',    '🔬', 'infant:sensorial',          9),
  ('Montessori',   '🏗️', NULL,                        10),
  ('Matemáticas',  '🔢', NULL,                        11),
  ('Lenguaje',     '💬', NULL,                        12),
  ('Ciencia',      '🔭', NULL,                        13)
) AS v(name, emoji, legacy_key, sort_order)
WHERE c.name = 'Actividades'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Arte
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'toggle', v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Canto',       '🎤', 0),
  ('Plastilina',  '🟠', 1),
  ('Collage',     '🖼️', 2),
  ('Teatro',      '🎭', 3),
  ('Origami',     '🎏', 4),
  ('Instrumentos','🥁', 5)
) AS v(name, emoji, sort_order)
WHERE c.name = 'Arte'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Aprendizaje
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'toggle', v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Reconoció colores','🎨', 0),
  ('Reconoció letras', '🔤', 1),
  ('Reconoció números','🔢', 2),
  ('Conteo',           '🧮', 3),
  ('Trazos',           '✍️', 4),
  ('Memoria',          '🧠', 5),
  ('Atención',         '👂', 6),
  ('Concentración',    '🎯', 7)
) AS v(name, emoji, sort_order)
WHERE c.name = 'Aprendizaje'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Social
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'toggle', v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Compartió',              '🤝', 0),
  ('Esperó turno',           '⏸️', 1),
  ('Ayudó',                  '🫶', 2),
  ('Trabajó en equipo',      '👥', 3),
  ('Resolución de conflictos','🕊️', 4),
  ('Lideró actividad',       '🚀', 5)
) AS v(name, emoji, sort_order)
WHERE c.name = 'Social'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Juego
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, legacy_key, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'toggle', v.legacy_key, v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Juego libre',     '🎮', NULL,        0),
  ('Juego exterior',  '🌳', NULL,        1),
  ('Juego grupal',    '🧑‍🤝‍🧑', NULL,  2),
  ('Juego individual', '🧍', NULL,       3),
  ('Patio',           '🏞️', 'infant:playground', 4),
  ('Columpio',        '🛝', NULL,        5),
  ('Arena',           '🏖️', NULL,       6),
  ('Pelotas',         '⚽', NULL,        7),
  ('Bloques',         '🧱', NULL,        8)
) AS v(name, emoji, legacy_key, sort_order)
WHERE c.name = 'Juego'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Exterior
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, legacy_key, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'toggle', v.legacy_key, v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Patio',                '🌳', 'infant:playground', 0),
  ('Jardín',               '🌻', NULL,                1),
  ('Huerto',               '🌱', NULL,                2),
  ('Educación física',     '🏃', NULL,                3),
  ('Caminata',             '🚶', NULL,                4),
  ('Observación naturaleza','🔍', NULL,               5)
) AS v(name, emoji, legacy_key, sort_order)
WHERE c.name = 'Exterior'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Momentos
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, legacy_key, requires_photo, sort_order)
SELECT c.id, v.name, v.emoji, c.color, v.kind, v.legacy_key, v.requires_photo, v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Llegada',         '🖐️', 'toggle', 'group:welcome',      false, 0),
  ('Pase de Lista',   '📋', 'toggle', 'group:roll_call',    false, 1),
  ('Entrega de niños','👋', 'toggle', 'group:departure',    false, 2),
  ('Foto',            '📷', 'photo',  'photo',              true,  3),
  ('Canción',         '🎶', 'toggle', 'infant:welcome_song', false, 4)
) AS v(name, emoji, kind, legacy_key, requires_photo, sort_order)
WHERE c.name = 'Momentos'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Incidentes (siempre notifican a padres)
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, legacy_key, requires_comment, notify_parents, notify_email, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'comment', v.legacy_key, true, true, v.notify_email, v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Caída',          '🤕', 'incident:hit',           false, 0),
  ('Mordida',        '🦷', NULL,                     false, 1),
  ('Arañazo',        '🐾', NULL,                     false, 2),
  ('Empujón',        '👊', NULL,                     false, 3),
  ('Llamada a padres','📞', 'incident:parent_call',  false, 4),
  ('Accidente leve', '🩹', 'incident:accident',      false, 5),
  ('Accidente mayor','🚑', NULL,                     true,  6)
) AS v(name, emoji, legacy_key, notify_email, sort_order)
WHERE c.name = 'Incidentes'
ON CONFLICT (name, category_id) DO NOTHING;

-- Seed — Personalizados (la escuela puede agregar más)
INSERT INTO public.routine_events (category_id, name, emoji, color, kind, sort_order)
SELECT c.id, v.name, v.emoji, c.color, 'toggle', v.sort_order
FROM public.routine_categories c
CROSS JOIN (VALUES
  ('Festival Patrio',    '🎆', 0),
  ('Huerto Escolar',     '🌽', 1),
  ('Piscina',            '🏊', 2),
  ('Excursión',          '🚌', 3),
  ('Día del Libro',      '📚', 4),
  ('Cumpleaños',         '🎂', 5),
  ('Proyecto Montessori','🧩', 6),
  ('Actividad STEM',     '🤖', 7)
) AS v(name, emoji, sort_order)
WHERE c.name = 'Personalizados'
ON CONFLICT (name, category_id) DO NOTHING;

-- ============================================================
-- 3. CONFIGURACION POR AULA (qué eventos usa cada aula)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.classroom_routine_settings (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id     bigint NOT NULL REFERENCES public.classrooms(id) ON DELETE CASCADE,
  event_id         bigint NOT NULL REFERENCES public.routine_events(id) ON DELETE CASCADE,
  is_active        boolean NOT NULL DEFAULT true,
  visible_parents  boolean,   -- NULL = hereda el catálogo
  visible_director boolean,   -- NULL = hereda el catálogo
  is_required      boolean,   -- NULL = hereda el catálogo
  sort_order       integer NOT NULL DEFAULT 0,
  created_at       timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (classroom_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_classroom_routine_settings_classroom
  ON public.classroom_routine_settings(classroom_id, is_active);

-- ============================================================
-- 4. CRONOLOGIA POR AULA (bloques del día)
-- ============================================================
CREATE TABLE IF NOT EXISTS public.classroom_schedule_blocks (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  classroom_id  bigint NOT NULL REFERENCES public.classrooms(id) ON DELETE CASCADE,
  days          smallint[] NOT NULL DEFAULT '{1,2,3,4,5,6}',  -- 0=Dom ... 6=Sáb
  start_time    time NOT NULL DEFAULT '08:00',
  duration_min  integer NOT NULL DEFAULT 30,
  label         text NOT NULL,
  emoji         text NOT NULL DEFAULT '📌',
  color         text NOT NULL DEFAULT '#0B63C7',
  sort_order    integer NOT NULL DEFAULT 0,
  is_active     boolean NOT NULL DEFAULT true,
  created_at    timestamp with time zone NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_classroom_schedule_blocks_classroom
  ON public.classroom_schedule_blocks(classroom_id, sort_order);

-- ============================================================
-- 5. BLOQUE <-> EVENTOS DEL CATALOGO
-- ============================================================
CREATE TABLE IF NOT EXISTS public.classroom_schedule_block_events (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  block_id   bigint NOT NULL REFERENCES public.classroom_schedule_blocks(id) ON DELETE CASCADE,
  event_id   bigint NOT NULL REFERENCES public.routine_events(id) ON DELETE CASCADE,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  UNIQUE (block_id, event_id)
);

CREATE INDEX IF NOT EXISTS idx_classroom_schedule_block_events_block
  ON public.classroom_schedule_block_events(block_id);

-- ============================================================
-- 6. RLS
-- ============================================================
ALTER TABLE public.routine_categories           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.routine_events               ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_routine_settings   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_schedule_blocks    ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.classroom_schedule_block_events ENABLE ROW LEVEL SECURITY;

-- Catálogo: staff puede todo; cualquier usuario autenticado puede leer
-- (los padres necesitan emoji/color/label para renderizar el reporte).
DROP POLICY IF EXISTS "routine_categories_staff_all" ON public.routine_categories;
CREATE POLICY "routine_categories_staff_all" ON public.routine_categories FOR ALL
  USING (COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada'));

DROP POLICY IF EXISTS "routine_categories_read" ON public.routine_categories;
CREATE POLICY "routine_categories_read" ON public.routine_categories FOR SELECT
  USING (auth.role() = 'authenticated');

DROP POLICY IF EXISTS "routine_events_staff_all" ON public.routine_events;
CREATE POLICY "routine_events_staff_all" ON public.routine_events FOR ALL
  USING (COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada'));

DROP POLICY IF EXISTS "routine_events_read" ON public.routine_events;
CREATE POLICY "routine_events_read" ON public.routine_events FOR SELECT
  USING (auth.role() = 'authenticated');

-- Config por aula: solo staff (nunca visible para padres)
DROP POLICY IF EXISTS "classroom_routine_settings_staff_all" ON public.classroom_routine_settings;
CREATE POLICY "classroom_routine_settings_staff_all" ON public.classroom_routine_settings FOR ALL
  USING (COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada'));

DROP POLICY IF EXISTS "classroom_schedule_blocks_staff_all" ON public.classroom_schedule_blocks;
CREATE POLICY "classroom_schedule_blocks_staff_all" ON public.classroom_schedule_blocks FOR ALL
  USING (COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada'));

DROP POLICY IF EXISTS "classroom_schedule_block_events_staff_all" ON public.classroom_schedule_block_events;
CREATE POLICY "classroom_schedule_block_events_staff_all" ON public.classroom_schedule_block_events FOR ALL
  USING (COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada'));

-- ============================================================
-- 7. AUTO-SEED: config por aula al crear un classroom
-- ============================================================
CREATE OR REPLACE FUNCTION public.seed_classroom_routine_settings()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  INSERT INTO public.classroom_routine_settings (classroom_id, event_id, sort_order)
  SELECT NEW.id, e.id, e.sort_order
  FROM public.routine_events e
  WHERE e.is_active = true
  ON CONFLICT (classroom_id, event_id) DO NOTHING;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS trg_seed_classroom_routine_settings ON public.classrooms;
CREATE TRIGGER trg_seed_classroom_routine_settings
  AFTER INSERT ON public.classrooms
  FOR EACH ROW EXECUTE FUNCTION public.seed_classroom_routine_settings();

-- ============================================================
-- 8. BACKFILL para aulas existentes (idempotente)
-- ============================================================
DO $$
BEGIN
  -- 8.1 settings
  INSERT INTO public.classroom_routine_settings (classroom_id, event_id, sort_order)
  SELECT c.id, e.id, e.sort_order
  FROM public.classrooms c
  CROSS JOIN public.routine_events e
  WHERE c.deleted_at IS NULL AND e.is_active = true
  ON CONFLICT (classroom_id, event_id) DO NOTHING;

  -- 8.2 cronología predeterminada (solo aulas sin bloques)
  INSERT INTO public.classroom_schedule_blocks
    (classroom_id, days, start_time, duration_min, label, emoji, color, sort_order)
  SELECT c.id, b.days, b.start_time, b.duration_min, b.label, b.emoji, b.color, b.sort_order
  FROM public.classrooms c
  CROSS JOIN (VALUES
    ('{1,2,3,4,5,6}'::smallint[], '07:30'::time, 15, 'Bienvenida',        '🖐️', '#FF8A00', 0),
    ('{1,2,3,4,5,6}'::smallint[], '07:45'::time, 15, 'Pase de Lista',     '📋', '#0B63C7', 1),
    ('{1,2,3,4,5,6}'::smallint[], '08:00'::time, 30, 'Desayuno',          '🍞', '#FF8A00', 2),
    ('{1,2,3,4,5,6}'::smallint[], '08:30'::time, 10, 'Lavado de manos',   '🧼', '#0B63C7', 3),
    ('{1,2,3,4,5,6}'::smallint[], '09:00'::time, 45, 'Actividad educativa','🎨', '#7C3AED', 4),
    ('{1,2,3,4,5,6}'::smallint[], '09:45'::time, 30, 'Salida al Patio',   '🌳', '#16A34A', 5),
    ('{1,2,3,4,5,6}'::smallint[], '10:15'::time, 30, 'Refrigerio',        '🍎', '#28B54D', 6),
    ('{1,2,3,4,5,6}'::smallint[], '11:00'::time, 45, 'Actividad sensorial','🔬', '#6366F1', 7),
    ('{1,2,3,4,5,6}'::smallint[], '11:45'::time, 30, 'Almuerzo',          '🍽️', '#28B54D', 8),
    ('{1,2,3,4,5,6}'::smallint[], '12:15'::time, 15, 'Cepillado',         '🪥', '#06B6D4', 9),
    ('{1,2,3,4,5,6}'::smallint[], '12:30'::time, 120,'Siesta',            '😴', '#8B5CF6', 10),
    ('{1,2,3,4,5,6}'::smallint[], '14:30'::time, 15, 'Despertar',         '😊', '#FFD43B', 11),
    ('{1,2,3,4,5,6}'::smallint[], '15:00'::time, 30, 'Merienda',          '🍪', '#F59E0B', 12),
    ('{1,2,3,4,5,6}'::smallint[], '15:30'::time, 30, 'Juego libre',       '🎮', '#EC4899', 13),
    ('{1,2,3,4,5,6}'::smallint[], '16:00'::time, 60, 'Entrega de niños',  '👋', '#EF4444', 14)
  ) AS b(days, start_time, duration_min, label, emoji, color, sort_order)
  WHERE c.deleted_at IS NULL
    AND NOT EXISTS (SELECT 1 FROM public.classroom_schedule_blocks x WHERE x.classroom_id = c.id);

  -- 8.3 mapeo bloque <-> eventos del catálogo
  INSERT INTO public.classroom_schedule_block_events (block_id, event_id, sort_order)
  SELECT b.id, e.id, m.sort_order
  FROM public.classroom_schedule_blocks b
  JOIN (VALUES
    ('Bienvenida',         'Momentos',    'Llegada',           0),
    ('Pase de Lista',      'Momentos',    'Pase de Lista',     0),
    ('Desayuno',           'Alimentación','Desayuno',          1),
    ('Desayuno',           'Alimentación','Agua',              2),
    ('Lavado de manos',    'Higiene',     'Lavado manos',      0),
    ('Actividad educativa','Actividades', 'Actividad educativa',0),
    ('Salida al Patio',    'Exterior',    'Patio',             0),
    ('Refrigerio',         'Alimentación','Refrigerio',        0),
    ('Refrigerio',         'Alimentación','Frutas',            1),
    ('Actividad sensorial','Actividades', 'Sensorial',         0),
    ('Almuerzo',           'Alimentación','Almuerzo',          0),
    ('Almuerzo',           'Alimentación','Agua',              1),
    ('Cepillado',          'Higiene',     'Cepillado',         0),
    ('Siesta',             'Descanso',    'Siesta',            0),
    ('Despertar',          'Descanso',    'Despertar',         0),
    ('Merienda',           'Alimentación','Merienda',          0),
    ('Merienda',           'Alimentación','Agua',              1),
    ('Juego libre',        'Juego',       'Juego libre',       0),
    ('Entrega de niños',   'Momentos',    'Entrega de niños',  0)
  ) AS m(block_label, cat_name, event_name, sort_order)
    ON b.label = m.block_label
  JOIN public.routine_categories c ON c.name = m.cat_name
  JOIN public.routine_events e ON e.category_id = c.id AND e.name = m.event_name
  WHERE NOT EXISTS (
    SELECT 1 FROM public.classroom_schedule_block_events x
    WHERE x.block_id = b.id AND x.event_id = e.id
  );

  -- 8.4 garantiza que los eventos vinculados a bloques existan y estén
  -- activos en classroom_routine_settings (idempotente; no toca sort_order
  -- configurado manualmente por el aula).
  INSERT INTO public.classroom_routine_settings (classroom_id, event_id, sort_order)
  SELECT DISTINCT b.classroom_id, be.event_id, e.sort_order
  FROM public.classroom_schedule_blocks b
  JOIN public.classroom_schedule_block_events be ON be.block_id = b.id
  JOIN public.routine_events e ON e.id = be.event_id
  WHERE e.is_active = true
  ON CONFLICT (classroom_id, event_id)
  DO UPDATE SET is_active = true;
END $$;
