
-- ============================================================
-- 📄 Sistema de Facturación / Recibos Karpus Kids
-- ============================================================
-- Este migration:
-- 1. Crea la tabla `invoice_items` para items de la factura
-- 2. Actualiza la tabla `invoices` con campos adicionales
-- 3. Crea funciones para generar números de factura y el recibo ASCII
-- ============================================================

-- 1. Tabla de items de factura
CREATE TABLE IF NOT EXISTS public.invoice_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id BIGINT NOT NULL REFERENCES public.invoices(id) ON DELETE CASCADE,
    concept TEXT NOT NULL,
    quantity NUMERIC(10, 2) NOT NULL DEFAULT 1,
    unit_price NUMERIC(10, 2) NOT NULL,
    total NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- 2. Actualizar tabla invoices con campos adicionales
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS receipt_number TEXT;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS payment_method TEXT;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS payment_reference TEXT;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS attended_by TEXT;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS period TEXT;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS next_payment_date DATE;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS next_payment_amount NUMERIC(10, 2);
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS digital_folio UUID DEFAULT uuid_generate_v4();
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS fiscal_receipt_url TEXT;
ALTER TABLE public.invoices ADD COLUMN IF NOT EXISTS ascii_receipt TEXT;

-- 3. Función para generar número de recibo
CREATE OR REPLACE FUNCTION public.generate_receipt_number()
RETURNS TEXT LANGUAGE PLPGSQL SECURITY DEFINER AS $$
DECLARE
    v_prefix TEXT;
    v_year TEXT;
    v_counter BIGINT;
    v_receipt_number TEXT;
BEGIN
    v_prefix := 'REC';
    v_year := TO_CHAR(NOW(), 'YYYY');
    
    -- Obtener contador o inicializar en 1
    SELECT invoice_counter INTO v_counter FROM public.school_settings WHERE id = 1;
    IF NOT FOUND THEN v_counter := 1; END IF;
    v_counter := COALESCE(v_counter, 1);
    
    v_receipt_number := v_prefix || '-' || v_year || '-' || LPAD(v_counter::TEXT, 6, '0');
    
    -- Incrementar contador
    UPDATE public.school_settings
    SET invoice_counter = invoice_counter + 1,
        updated_at = NOW()
    WHERE id = 1;
    
    RETURN v_receipt_number;
END;
$$;
GRANT EXECUTE ON FUNCTION public.generate_receipt_number() TO authenticated;

-- 4. Función para generar el recibo ASCII
CREATE OR REPLACE FUNCTION public.generate_ascii_receipt(p_invoice_id BIGINT)
RETURNS TEXT LANGUAGE PLPGSQL SECURITY DEFINER AS $$
DECLARE
    v_inv public.invoices%ROWTYPE;
    v_items RECORD;
    v_school public.school_settings%ROWTYPE;
    v_total NUMERIC(10,2) := 0;
    v_receipt TEXT := '';
BEGIN
    SELECT * INTO v_inv FROM public.invoices WHERE id = p_invoice_id;
    SELECT * INTO v_school FROM public.school_settings WHERE id = 1;
    
    v_receipt := v_receipt || '┌─────────────────────────────────────────────────────────────┐' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  ╔══════════════════════════════════════════════════════╗  │' || E'\n';
    v_receipt := v_receipt || '│  ║                                                      ║  │' || E'\n';
    v_receipt := v_receipt || '│  ║              🏫 KARPUS KIDS                          ║  │' || E'\n';
    v_receipt := v_receipt || '│  ║         ESTANCIA INFANTIL                            ║  │' || E'\n';
    v_receipt := v_receipt || '│  ║                                                      ║  │' || E'\n';
    v_receipt := v_receipt || '│  ║    ' || RPAD(COALESCE(v_school.address, 'Calle Principal #123, Col. Centro'), 38) || '║  │' || E'\n';
    v_receipt := v_receipt || '│  ║    ' || RPAD(COALESCE(v_school.city || ', ' || v_school.state || ', C.P. ' || v_school.zip_code, 'San Cristóbal, Rep. Dom.'), 38) || '║  │' || E'\n';
    v_receipt := v_receipt || '│  ║    Tel: ' || RPAD(COALESCE(v_school.phone, '(829) 803-8424'), 33) || '║  │' || E'\n';
    v_receipt := v_receipt || '│  ║    Email: ' || RPAD(COALESCE(v_school.email, 'contacto@montessorisonrisascreativas.com'), 30) || '║  │' || E'\n';
    v_receipt := v_receipt || '│  ║    RFC/RNC: ' || RPAD(COALESCE(v_school.rnc, 'KKI123456ABC'), 27) || '║  │' || E'\n';
    v_receipt := v_receipt || '│  ║                                                      ║  │' || E'\n';
    v_receipt := v_receipt || '│  ╚══════════════════════════════════════════════════════╝  │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  ┌────────────────────────────────────────────────────┐  │' || E'\n';
    v_receipt := v_receipt || '│  │                  RECIBO DE PAGO                    │  │' || E'\n';
    v_receipt := v_receipt || '│  │              ' || RPAD(COALESCE(v_inv.receipt_number, v_inv.invoice_number, 'SIN NUMERO'), 38) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  └────────────────────────────────────────────────────┘  │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  ┌────────────────────────────────────────────────────┐  │' || E'\n';
    v_receipt := v_receipt || '│  │  INFORMACIÓN DEL RECIBO                            │  │' || E'\n';
    v_receipt := v_receipt || '│  ├────────────────────────────────────────────────────┤  │' || E'\n';
    v_receipt := v_receipt || '│  │  Fecha de Emisión:    ' || RPAD(TO_CHAR(v_inv.issued_date, 'DD "de" FMMonth "de" YYYY'), 30) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  │  Hora:                ' || RPAD(TO_CHAR(v_inv.issued_date, 'HH24:MI "hrs"'), 30) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  │  Método de Pago:      ' || RPAD(COALESCE(v_inv.payment_method, 'N/A'), 30) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  │  Referencia:          ' || RPAD(COALESCE(v_inv.payment_reference, 'N/A'), 30) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  │  Atendió:             ' || RPAD(COALESCE(v_inv.attended_by, 'Sistema'), 30) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  └────────────────────────────────────────────────────┘  │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  ┌────────────────────────────────────────────────────┐  │' || E'\n';
    v_receipt := v_receipt || '│  │  DATOS DEL CLIENTE                                 │  │' || E'\n';
    v_receipt := v_receipt || '│  ├────────────────────────────────────────────────────┤  │' || E'\n';
    v_receipt := v_receipt || '│  │  Nombre:              ' || RPAD(COALESCE(v_inv.parent_name, 'N/A'), 30) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  │                                                     │  │' || E'\n';
    v_receipt := v_receipt || '│  │  ESTUDIANTE                                         │  │' || E'\n';
    v_receipt := v_receipt || '│  │  Nombre:              ' || RPAD(COALESCE(v_inv.student_name, 'N/A'), 30) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  │  Matrícula:           ' || RPAD(COALESCE(v_inv.student_matricula, 'N/A'), 30) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  │  Aula:                ' || RPAD(COALESCE(v_inv.classroom_name, 'N/A'), 30) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  └────────────────────────────────────────────────────┘  │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  ┌────────────────────────────────────────────────────┐  │' || E'\n';
    v_receipt := v_receipt || '│  │  DETALLE DEL PAGO                                  │  │' || E'\n';
    v_receipt := v_receipt || '│  ├────────────────────────────────────────────────────┤  │' || E'\n';
    v_receipt := v_receipt || '│  │                                                     │  │' || E'\n';
    v_receipt := v_receipt || '│  │  Concepto                    Cantidad    Importe   │  │' || E'\n';
    v_receipt := v_receipt || '│  │  ─────────────────────────────────────────────────│  │' || E'\n';
    
    v_total := 0;
    FOR v_items IN SELECT * FROM public.invoice_items WHERE invoice_id = p_invoice_id LOOP
        v_receipt := v_receipt || '│  │  ' || RPAD(SUBSTR(COALESCE(v_items.concept, ''), 1, 26), 26) || 
            ' ' || RPAD(TO_CHAR(v_items.quantity, 'FM999999999999'), 8) || 
            '  ' || RPAD('$' || TO_CHAR(v_items.total, 'FM9999999999.99'), 10) || '│  │' || E'\n';
        v_total := v_total + v_items.total;
    END LOOP;
    
    v_receipt := v_receipt || '│  │                                                     │  │' || E'\n';
    v_receipt := v_receipt || '│  │  ─────────────────────────────────────────────────│  │' || E'\n';
    v_receipt := v_receipt || '│  │                                                     │  │' || E'\n';
    v_receipt := v_receipt || '│  │                          Subtotal:     ' || RPAD('$' || TO_CHAR(v_total, 'FM9999999999.99'), 12) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  │                          IVA (0%):         $0.00  │  │' || E'\n';
    v_receipt := v_receipt || '│  │                          ────────────────────────│  │' || E'\n';
    v_receipt := v_receipt || '│  │                          TOTAL:        ' || RPAD('$' || TO_CHAR(v_total, 'FM9999999999.99'), 12) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  │                                                     │  │' || E'\n';
    v_receipt := v_receipt || '│  └────────────────────────────────────────────────────┘  │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  ┌────────────────────────────────────────────────────┐  │' || E'\n';
    v_receipt := v_receipt || '│  │  INFORMACIÓN ADICIONAL                             │  │' || E'\n';
    v_receipt := v_receipt || '│  ├────────────────────────────────────────────────────┤  │' || E'\n';
    v_receipt := v_receipt || '│  │  Período:             ' || RPAD(COALESCE(v_inv.period, 'N/A'), 30) || '│  │' || E'\n';
    v_receipt := v_receipt || '│  │  Estado:              ✅ PAGADO                     │  │' || E'\n';
    IF v_inv.next_payment_date IS NOT NULL THEN
        v_receipt := v_receipt || '│  │  Próximo Pago:        ' || RPAD(TO_CHAR(v_inv.next_payment_date, 'DD "de" FMMonth "de" YYYY'), 30) || '│  │' || E'\n';
    END IF;
    IF v_inv.next_payment_amount IS NOT NULL THEN
        v_receipt := v_receipt || '│  │  Monto Próximo:       ' || RPAD('$' || TO_CHAR(v_inv.next_payment_amount, 'FM9999999999.99'), 30) || '│  │' || E'\n';
    END IF;
    v_receipt := v_receipt || '│  └────────────────────────────────────────────────────┘  │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  ┌────────────────────────────────────────────────────┐  │' || E'\n';
    v_receipt := v_receipt || '│  │  NOTAS                                              │  │' || E'\n';
    v_receipt := v_receipt || '│  ├────────────────────────────────────────────────────┤  │' || E'\n';
    v_receipt := v_receipt || '│  │  • Este recibo es válido como comprobante de pago  │  │' || E'\n';
    v_receipt := v_receipt || '│  │  • Conserve este documento para cualquier          │  │' || E'\n';
    v_receipt := v_receipt || '│  │    aclaración                                      │  │' || E'\n';
    v_receipt := v_receipt || '│  │  • Para dudas contacte a administración            │  │' || E'\n';
    v_receipt := v_receipt || '│  └────────────────────────────────────────────────────┘  │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  ─────────────────────────────────────────────────────────  │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│              ¡Gracias por su confianza!                     │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  ─────────────────────────────────────────────────────────  │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  Firma: _____________________    Sello: [SELLO ESCUELA]   │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '│  ─────────────────────────────────────────────────────────  │' || E'\n';
    v_receipt := v_receipt || '│  Documento generado electrónicamente                        │' || E'\n';
    v_receipt := v_receipt || '│  Folio Digital: ' || RPAD(COALESCE(v_inv.digital_folio::TEXT, 'N/A'), 38) || ' │' || E'\n';
    v_receipt := v_receipt || '│  Fecha de Generación: ' || RPAD(TO_CHAR(NOW(), 'YYYY-MM-DD HH24:MI:SS'), 36) || ' │' || E'\n';
    v_receipt := v_receipt || '│  ─────────────────────────────────────────────────────────  │' || E'\n';
    v_receipt := v_receipt || '│                                                             │' || E'\n';
    v_receipt := v_receipt || '└─────────────────────────────────────────────────────────────┘' || E'\n';
    
    RETURN v_receipt;
END;
$$;
GRANT EXECUTE ON FUNCTION public.generate_ascii_receipt(BIGINT) TO authenticated;

-- 5. Trigger para actualizar ascii_receipt cuando se actualiza la factura
CREATE OR REPLACE FUNCTION public.trigger_update_ascii_receipt()
RETURNS TRIGGER LANGUAGE PLPGSQL AS $$
BEGIN
    IF TG_OP = 'INSERT' OR TG_OP = 'UPDATE' THEN
        NEW.ascii_receipt := public.generate_ascii_receipt(NEW.id);
    END IF;
    RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trigger_update_ascii_receipt ON public.invoices;
CREATE TRIGGER trigger_update_ascii_receipt
BEFORE INSERT OR UPDATE ON public.invoices
FOR EACH ROW EXECUTE FUNCTION public.trigger_update_ascii_receipt();
