-- ============================================================
-- Migracion: Sistema de Pre-inscripciones v2
-- Tabla student_preregistrations completa
-- ============================================================

-- Eliminar tabla anterior si existe (para recrear limpia)
DROP TABLE IF EXISTS public.student_preregistrations CASCADE;

-- Tabla de Pre-inscripciones completa
CREATE TABLE IF NOT EXISTS public.student_preregistrations (
  id                    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- PASO 1: Datos del Estudiante
  student_name          text NOT NULL,
  student_last_name     text,
  birth_date            date,
  gender                text,
  nationality           text,
  student_photo_url     text,
  school_year_requested text,
  level_requested       text,
  schedule              text,
  estimated_entry_date  date,
  has_siblings          boolean DEFAULT false,
  sibling_name          text,

  -- PASO 2: Padre o Tutor Principal
  p1_name               text NOT NULL,
  p1_relationship       text,
  p1_cedula             text,
  p1_birth_date         date,
  p1_phone              text NOT NULL,
  p1_whatsapp           text,
  p1_email              text NOT NULL,
  p1_address            text,
  p1_occupation         text,
  p1_profession         text,
  p1_workplace          text,

  -- PASO 2: Madre o Segundo Tutor
  p2_name               text,
  p2_relationship       text,
  p2_cedula             text,
  p2_birth_date         date,
  p2_phone              text,
  p2_whatsapp           text,
  p2_email              text,
  p2_address            text,
  p2_occupation         text,
  p2_profession         text,
  p2_workplace          text,

  -- PASO 3: Contacto de Emergencia
  emergency_name        text,
  emergency_relationship text,
  emergency_cedula      text,
  emergency_phone       text,
  emergency_observations text,

  -- PASO 3: Personas Autorizadas (JSON array)
  authorized_persons    jsonb DEFAULT '[]'::jsonb,

  -- PASO 4: Informacion Medica
  blood_type            text,
  allergies             text,
  medical_conditions    text,
  medications           text,
  food_restrictions     text,
  medical_notes         text,

  -- PASO 5: Documentos (URLs)
  photo_url             text,
  birth_certificate_url text,
  cedula_front_url      text,
  cedula_back_url       text,

  -- PASO 6: Autorizaciones y Firma
  auth_data_treatment   boolean DEFAULT false,
  auth_correct_info     boolean DEFAULT false,
  auth_contact          boolean DEFAULT false,
  auth_regulations      boolean DEFAULT false,
  digital_signature     text,
  signature_date        timestamp with time zone,

  -- Informacion adicional
  reference             text,
  comments              text,

  -- Estado y revision
  status                text DEFAULT 'pending' CHECK (status IN ('pending', 'admitted', 'rejected', 'converted')),
  reviewed_at           timestamp with time zone,
  reviewed_by           uuid REFERENCES public.profiles(id) ON DELETE SET NULL,

  -- Metadata
  created_at            timestamp with time zone DEFAULT now() NOT NULL,
  updated_at            timestamp with time zone DEFAULT now() NOT NULL
);

-- Indices para rendimiento
CREATE INDEX IF NOT EXISTS idx_preregistrations_status ON public.student_preregistrations(status);
CREATE INDEX IF NOT EXISTS idx_preregistrations_created ON public.student_preregistrations(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_preregistrations_student_name ON public.student_preregistrations(lower(student_name));
CREATE INDEX IF NOT EXISTS idx_preregistrations_level ON public.student_preregistrations(level_requested);

-- Trigger para actualizar updated_at automaticamente
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS update_student_preregistrations_updated_at ON public.student_preregistrations;
CREATE TRIGGER update_student_preregistrations_updated_at
  BEFORE UPDATE ON public.student_preregistrations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Habilitar RLS
ALTER TABLE public.student_preregistrations ENABLE ROW LEVEL SECURITY;

-- Politicas RLS: Permitir insercion anonima (para el formulario publico)
DROP POLICY IF EXISTS "Permitir insercion anonima de preinscripciones" ON public.student_preregistrations;
CREATE POLICY "Permitir insercion anonima de preinscripciones"
  ON public.student_preregistrations
  FOR INSERT
  TO anon, authenticated
  WITH CHECK (true);

-- Politicas RLS: Permitir lectura y escritura a usuarios autenticados (directora, asistente)
DROP POLICY IF EXISTS "Permitir lectura completa a autenticados" ON public.student_preregistrations;
CREATE POLICY "Permitir lectura completa a autenticados"
  ON public.student_preregistrations
  FOR SELECT
  TO authenticated
  USING (true);

DROP POLICY IF EXISTS "Permitir actualizacion a autenticados" ON public.student_preregistrations;
CREATE POLICY "Permitir actualizacion a autenticados"
  ON public.student_preregistrations
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- Funcion RPC: Convertir preinscripcion a estudiante
-- ============================================================
CREATE OR REPLACE FUNCTION public.convert_preregistration(
  p_preinsc_id bigint,
  p_school_year_id bigint,
  p_classroom_id bigint DEFAULT NULL,
  p_payment_plan_id bigint DEFAULT NULL,
  p_matricula text DEFAULT NULL
)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_preinsc record;
  v_student_id bigint;
  v_enrollment_id bigint;
BEGIN
  SELECT * INTO v_preinsc FROM student_preregistrations WHERE id = p_preinsc_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Preinscripcion no encontrada';
  END IF;

  IF v_preinsc.status = 'converted' THEN
    RAISE EXCEPTION 'Esta preinscripcion ya ha sido convertida';
  END IF;

  -- 1. Crear estudiante
  INSERT INTO students (
    name, classroom_id, allergies, matricula,
    p1_name, p1_phone, p1_email,
    p2_name, p2_phone,
    created_at
  ) VALUES (
    v_preinsc.student_name || ' ' || COALESCE(v_preinsc.student_last_name, ''),
    p_classroom_id,
    v_preinsc.allergies,
    p_matricula,
    v_preinsc.p1_name,
    v_preinsc.p1_phone,
    v_preinsc.p1_email,
    v_preinsc.p2_name,
    v_preinsc.p2_phone,
    now()
  ) RETURNING id INTO v_student_id;

  -- 2. Crear inscripcion
  INSERT INTO student_enrollments (
    student_id, school_year_id, classroom_id, payment_plan_id,
    status, preinscription_date, created_at
  ) VALUES (
    v_student_id, p_school_year_id, p_classroom_id, p_payment_plan_id,
    'admitted', v_preinsc.created_at, now()
  ) RETURNING id INTO v_enrollment_id;

  -- 3. Actualizar estado de preinscripcion
  UPDATE student_preregistrations
  SET status = 'converted', reviewed_at = now()
  WHERE id = p_preinsc_id;

  RETURN jsonb_build_object(
    'success', true,
    'student_id', v_student_id,
    'enrollment_id', v_enrollment_id
  );
END;
$$;

GRANT EXECUTE ON FUNCTION public.convert_preregistration TO authenticated;

-- ============================================================
-- Completado
-- ============================================================
