-- ============================================================
-- 06_vistas.sql — Colegio Montessori Sonrisas Creativas
-- Contenido: vistas para reportes (dashboard) y seguridad (fuerza bruta)
-- ============================================================

-- ---------------------------------------------------------------------------
-- 6.0 Tablas que la app usa pero que faltaban en el esquema base:
--     'reports' (reportes de padres) y su historial 'report_history'.
--     Se crean aquí (IF NOT EXISTS) para que las vistas 6.2 las puedan leer.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reports (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id          uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  student_id         bigint REFERENCES public.students(id) ON DELETE SET NULL,
  classroom_id       bigint REFERENCES public.classrooms(id) ON DELETE SET NULL,
  report_type        text,
  target_teacher_id  uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  target_student_id  bigint REFERENCES public.students(id) ON DELETE SET NULL,
  category           text,
  description        text,
  severity           text NOT NULL DEFAULT 'media' CHECK (severity IN ('leve','media','alta')),
  status             text NOT NULL DEFAULT 'open' CHECK (status IN ('open','pending','in_review','resolved','closed')),
  is_anonymous       boolean NOT NULL DEFAULT false,
  evidence_url       text,
  response           text,
  response_by        uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  response_at        timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.report_history (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id  bigint NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  changed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  old_status text,
  new_status text,
  note       text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reports_parent   ON public.reports(parent_id);
CREATE INDEX IF NOT EXISTS idx_reports_status   ON public.reports(status);
CREATE INDEX IF NOT EXISTS idx_report_history_report ON public.report_history(report_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.reports TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.report_history TO authenticated, service_role;

-- RLS: el padre ve/gestiona sus propios reportes; el staff ve todo.
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "reports_select" ON public.reports;
CREATE POLICY "reports_select" ON public.reports FOR SELECT USING (
  parent_id = auth.uid()
  OR COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada')
);
DROP POLICY IF EXISTS "reports_insert" ON public.reports;
CREATE POLICY "reports_insert" ON public.reports FOR INSERT WITH CHECK (
  parent_id = auth.uid()
  OR COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada')
);
DROP POLICY IF EXISTS "reports_update" ON public.reports;
CREATE POLICY "reports_update" ON public.reports FOR UPDATE USING (
  COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada')
) WITH CHECK (
  COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada')
);

ALTER TABLE public.report_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "report_history_read" ON public.report_history;
CREATE POLICY "report_history_read" ON public.report_history FOR SELECT USING (true);
DROP POLICY IF EXISTS "report_history_write" ON public.report_history;
CREATE POLICY "report_history_write" ON public.report_history FOR INSERT WITH CHECK (
  COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada')
  OR EXISTS (
    SELECT 1 FROM public.reports r
    WHERE r.id = report_history.report_id AND r.parent_id = auth.uid()
  )
);

-- ---------------------------------------------------------------------------
-- 6.1 get_reports — RPC que usan los paneles (padre y directora)
--     SECURITY INVOKER: respeta las políticas RLS de 'reports'.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.get_reports(p_status text DEFAULT NULL)
RETURNS SETOF public.reports
LANGUAGE sql STABLE
AS $$
  SELECT * FROM public.reports
  WHERE (p_status IS NULL OR status = p_status)
  ORDER BY created_at DESC;
$$;
GRANT EXECUTE ON FUNCTION public.get_reports(text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 6.2 v_reports_dashboard — resumen para el dashboard de reportes
--     (columnas esperadas por js/shared/reports.js y directora/reports.module.js)
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.v_reports_dashboard AS
SELECT
  COUNT(*)::bigint AS total_reports,
  COUNT(*) FILTER (WHERE status IN ('open','pending','in_review'))::bigint AS open_reports,
  COUNT(*) FILTER (WHERE status = 'resolved')::bigint AS resolved_reports,
  COUNT(*) FILTER (WHERE status = 'pending')::bigint AS pending_reports,
  COUNT(*) FILTER (WHERE status IN ('open','pending','in_review')
                   AND created_at < now() - interval '5 days')::bigint AS overdue_reports,
  ROUND(AVG(
    CASE WHEN response_at IS NOT NULL
         THEN EXTRACT(EPOCH FROM (response_at - created_at)) / 86400.0
    END
  )::numeric, 1) AS avg_resolution_days
FROM public.reports;
GRANT SELECT ON public.v_reports_dashboard TO authenticated;

-- ---------------------------------------------------------------------------
-- 6.3 v_brute_force_attempts — monitor de fuerza bruta (últimas 24h)
--     (columnas esperadas por control/main.js)
--     Solo visible para administración: protege emails de ataques/curiosos.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE VIEW public.v_brute_force_attempts AS
SELECT
  p.id AS user_id,
  la.email,
  COUNT(*) FILTER (WHERE la.success = false)::int AS failed_attempts,
  MAX(la.created_at) AS last_attempt,
  MAX(la.ip_hash) AS ip_address,
  (COUNT(*) FILTER (WHERE la.success = false) >= 5) AS is_blocked,
  (COUNT(*) FILTER (WHERE la.success = false) >= 3) AS is_suspicious
FROM public.login_attempts la
LEFT JOIN public.profiles p ON lower(p.email) = lower(la.email)
WHERE la.created_at > now() - interval '24 hours'
  AND COALESCE(get_my_role(), '') IN ('admin','directora')
GROUP BY p.id, la.email
ORDER BY failed_attempts DESC;
GRANT SELECT ON public.v_brute_force_attempts TO authenticated;