-- ============================================================
-- 06_vistas.sql — Colegio Montessori Sonrisas Creativas
-- Contenido: vistas para reportes (dashboard) y seguridad (fuerza bruta)
-- ============================================================

-- ---------------------------------------------------------------------------
-- 6.0 Tablas que la app usa pero que faltaban en el esquema base:
--     'reports' (reportes de padres) y su historial 'report_history'.
--     Se crean aquí (IF NOT EXISTS) para que las vistas 6.2 las puedan leer.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reports (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_id          uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  student_id         bigint REFERENCES public.students(id) ON DELETE SET NULL,
  classroom_id       bigint REFERENCES public.classrooms(id) ON DELETE SET NULL,
  report_type        text,
  target_teacher_id  uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  target_student_id  bigint REFERENCES public.students(id) ON DELETE SET NULL,
  category           text,
  description        text,
  severity           text NOT NULL DEFAULT 'media' CHECK (severity IN ('leve','media','alta')),
  status             text NOT NULL DEFAULT 'open' CHECK (status IN ('open','pending','in_review','resolved','closed')),
  is_anonymous       boolean NOT NULL DEFAULT false,
  evidence_url       text,
  response           text,
  response_by        uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  response_at        timestamptz,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);

-- Si la tabla ya existe (instalación antigua) pero le faltan columnas,
-- se agregan aquí para que los índices/políticas de abajo no fallen (error 42703).
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS parent_id          uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS student_id         bigint REFERENCES public.students(id) ON DELETE SET NULL;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS classroom_id       bigint REFERENCES public.classrooms(id) ON DELETE SET NULL;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS report_type        text;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS target_teacher_id  uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS target_student_id  bigint REFERENCES public.students(id) ON DELETE SET NULL;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS category           text;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS description        text;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS severity           text NOT NULL DEFAULT 'media' CHECK (severity IN ('leve','media','alta'));
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS status             text NOT NULL DEFAULT 'open' CHECK (status IN ('open','pending','in_review','resolved','closed'));
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS is_anonymous       boolean NOT NULL DEFAULT false;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS evidence_url       text;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS response           text;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS response_by        uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS response_at        timestamptz;
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS created_at         timestamptz NOT NULL DEFAULT now();
ALTER TABLE public.reports ADD COLUMN IF NOT EXISTS updated_at         timestamptz NOT NULL DEFAULT now();

CREATE TABLE IF NOT EXISTS public.report_history (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id  bigint NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE,
  changed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL,
  old_status text,
  new_status text,
  note       text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.report_history ADD COLUMN IF NOT EXISTS report_id  bigint NOT NULL REFERENCES public.reports(id) ON DELETE CASCADE;
ALTER TABLE public.report_history ADD COLUMN IF NOT EXISTS changed_by uuid REFERENCES public.profiles(id) ON DELETE SET NULL;
ALTER TABLE public.report_history ADD COLUMN IF NOT EXISTS old_status text;
ALTER TABLE public.report_history ADD COLUMN IF NOT EXISTS new_status text;
ALTER TABLE public.report_history ADD COLUMN IF NOT EXISTS note       text;
ALTER TABLE public.report_history ADD COLUMN IF NOT EXISTS created_at timestamptz NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS idx_reports_parent   ON public.reports(parent_id);
CREATE INDEX IF NOT EXISTS idx_reports_status   ON public.reports(status);
CREATE INDEX IF NOT EXISTS idx_report_history_report ON public.report_history(report_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.reports TO authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.report_history TO authenticated, service_role;

-- RLS: el padre ve/gestiona sus propios reportes; el staff ve todo.
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "reports_select" ON public.reports;
CREATE POLICY "reports_select" ON public.reports FOR SELECT USING (
  parent_id = auth.uid()
  OR COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada')
);
DROP POLICY IF EXISTS "reports_insert" ON public.reports;
CREATE POLICY "reports_insert" ON public.reports FOR INSERT WITH CHECK (
  parent_id = auth.uid()
  OR COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada')
);
DROP POLICY IF EXISTS "reports_update" ON public.reports;
CREATE POLICY "reports_update" ON public.reports FOR UPDATE USING (
  COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada')
) WITH CHECK (
  COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada')
);

ALTER TABLE public.report_history ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "report_history_read" ON public.report_history;
CREATE POLICY "report_history_read" ON public.report_history FOR SELECT USING (true);
DROP POLICY IF EXISTS "report_history_write" ON public.report_history;
CREATE POLICY "report_history_write" ON public.report_history FOR INSERT WITH CHECK (
  COALESCE(get_my_role(), '') IN ('directora','asistente','admin','maestra','encargada')
  OR EXISTS (
    SELECT 1 FROM public.reports r
    WHERE r.id = report_history.report_id AND r.parent_id = auth.uid()
  )
);

-- ---------------------------------------------------------------------------
-- 6.1 get_reports — RPC que usan los paneles (padre y directora)
--     SECURITY INVOKER: respeta las políticas RLS de 'reports'.
-- ---------------------------------------------------------------------------
DROP FUNCTION IF EXISTS public.get_reports(text);
CREATE OR REPLACE FUNCTION public.get_reports(p_status text DEFAULT NULL)
RETURNS SETOF public.reports
LANGUAGE sql STABLE
AS $$
  SELECT * FROM public.reports
  WHERE (p_status IS NULL OR status = p_status)
  ORDER BY created_at DESC;
$$;
GRANT EXECUTE ON FUNCTION public.get_reports(text) TO authenticated;

-- ---------------------------------------------------------------------------
-- 6.2 v_reports_dashboard — resumen para el dashboard de reportes
--     (columnas esperadas por js/shared/reports.js y directora/reports.module.js)
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS public.v_reports_dashboard;
CREATE OR REPLACE VIEW public.v_reports_dashboard AS
SELECT
  COUNT(*)::bigint AS total_reports,
  COUNT(*) FILTER (WHERE status IN ('open','pending','in_review'))::bigint AS open_reports,
  COUNT(*) FILTER (WHERE status = 'resolved')::bigint AS resolved_reports,
  COUNT(*) FILTER (WHERE status = 'pending')::bigint AS pending_reports,
  COUNT(*) FILTER (WHERE status IN ('open','pending','in_review')
                   AND created_at < now() - interval '5 days')::bigint AS overdue_reports,
  ROUND(AVG(
    CASE WHEN response_at IS NOT NULL
         THEN EXTRACT(EPOCH FROM (response_at - created_at)) / 86400.0
    END
  )::numeric, 1) AS avg_resolution_days
FROM public.reports;
GRANT SELECT ON public.v_reports_dashboard TO authenticated;

-- ---------------------------------------------------------------------------
-- 6.3 v_brute_force_attempts — monitor de fuerza bruta (últimas 24h)
--     (columnas esperadas por control/main.js)
--     Solo visible para administración: protege emails de ataques/curiosos.
-- ---------------------------------------------------------------------------
DROP VIEW IF EXISTS public.v_brute_force_attempts;
CREATE OR REPLACE VIEW public.v_brute_force_attempts AS
SELECT
  p.id AS user_id,
  la.email,
  COUNT(*) FILTER (WHERE la.success = false)::int AS failed_attempts,
  MAX(la.created_at) AS last_attempt,
  MAX(la.ip_hash) AS ip_address,
  (COUNT(*) FILTER (WHERE la.success = false) >= 5) AS is_blocked,
  (COUNT(*) FILTER (WHERE la.success = false) >= 3) AS is_suspicious
FROM public.login_attempts la
LEFT JOIN public.profiles p ON lower(p.email) = lower(la.email)
WHERE la.created_at > now() - interval '24 hours'
  AND COALESCE(get_my_role(), '') IN ('admin','directora')
GROUP BY p.id, la.email
ORDER BY failed_attempts DESC;
GRANT SELECT ON public.v_brute_force_attempts TO authenticated;

-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•
-- CONSOLIDADO DESDE migrations\ (historial) â€” aÃ±adido automÃ¡ticamente
-- Fecha: 2026-09-12 21:41
-- â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•

DROP VIEW IF EXISTS public.daily_routine;
CREATE OR REPLACE VIEW daily_routine AS
WITH routine_times AS (
  SELECT
    'desayuno' AS event_type, '08:00' AS ideal_time, '🍞' AS emoji, 'Desayuno' AS title, 'Desayuno' AS subtitle UNION ALL
  SELECT
    'merienda' AS event_type, '10:00' AS ideal_time, '🍎' AS emoji, 'Merienda' AS title, 'Merienda' AS subtitle UNION ALL
  SELECT
    'dormir' AS event_type, '10:30' AS ideal_time, '😴' AS emoji, 'Siesta' AS title, 'Hora de dormir' AS subtitle UNION ALL
  SELECT
    'despertar' AS event_type, '12:00' AS ideal_time, '😊' AS emoji, 'Despertar' AS title, 'Despertó' AS subtitle UNION ALL
  SELECT
    'almuerzo' AS event_type, '12:30' AS ideal_time, '🥗' AS emoji, 'Almuerzo' AS title, 'Almuerzo' AS subtitle UNION ALL
  SELECT
    'biberon' AS event_type, '14:00' AS ideal_time, '🍼' AS emoji, 'Biberón' AS title, 'Biberón' AS subtitle UNION ALL
  SELECT
    'panal' AS event_type, '10:15' AS ideal_time, '🚼' AS emoji, 'Pañal' AS title, 'Cambio de pañal' AS subtitle UNION ALL
  SELECT
    'bano' AS event_type, '09:00' AS ideal_time, '🚽' AS emoji, 'Baño' AS title, 'Baño' AS subtitle UNION ALL
  SELECT
    'temperatura' AS event_type, '07:45' AS ideal_time, '🌡' AS emoji, 'Temperatura' AS title, 'Tomar temperatura' AS subtitle UNION ALL
  SELECT
    'medicamento' AS event_type, NULL AS ideal_time, '💊' AS emoji, 'Medicamento' AS title, 'Medicamento' AS subtitle UNION ALL
  SELECT
    'foto' AS event_type, NULL AS ideal_time, '📷' AS emoji, 'Foto' AS title, 'Foto' AS subtitle UNION ALL
  SELECT
    'nota' AS event_type, NULL AS ideal_time, '📝' AS emoji, 'Nota' AS title, 'Nota' AS subtitle
)
SELECT * FROM routine_times;
